### PR TITLE
BUGFIX: Add missing documentation of third parameter in sort operation

### LINKED ISSUE #3238: Missing documentation for PR 2989
With PR #2989 a third parameter was introduced to the sort function in Flow Query. But in the comment above the function, the description of this third parameter is missing. https://github.com/neos/neos-development-collection/blob/7.0/Neos.Neos/Classes/Eel/FlowQueryOperations/SortOperation.php#L44-L53

### PR DESCRIPTION
**Pull request by jonnitto**
This will fix #3238

### CODE REVIEW

**Comment by sorenmalling** [comment]
@jonnitto Does this also require a update of the rst doc files 

https://github.com/neos/neos-development-collection/blob/master/Neos.Neos/Documentation/References/FlowQueryOperationReference.rst

**Comment by jonnitto** [comment]
The rst will be automatically generated

**Review by markusguenther — APPROVED** [review]

**Review by mhsdesign — APPROVED** [review]
Looks fine by reading as this is just #3285 recreated.

**Comment by sorenmalling** [comment]
> The rst will be automatically generated

Dang.. Then my PR for the RST file wasn't nescessary? https://github.com/neos/neos-development-collection/pull/3512

**Pull request merged**
