### PR TITLE
BUGFIX: Changed Domains by UriConstraints will not no longer get destroyed by the LinkingService

### PR DESCRIPTION
**Pull request by MarcoPNS**
With `UriConstraints` we have the ability to modify the Host but there is a problem with the `LinkingService` in combination with `UriConstraints`. If you ask the `LinkingService` for a absolut Uri then it add the current base to the Url. Issue #2398

### CODE REVIEW

**Comment by daniellienert** [comment]
Hey @MarcoPNS, 

thank you very much for that patch! As I assume, the bug also exists in previous versions, would you please open this PR to the lowest maintained branch, where this issue exists (probably Neos 3.3)?

Thanks!

**Comment by MarcoPNS** [comment]
Hey @daniellienert,

I just checked it and the problem exist since Neos 3.3 / Flow 4.3. I changed the base branch. Hope that this is correct. 

Thanks!

**Comment by MarcoPNS** [comment]
@kdambekalns Why is the `ltrim` call useless? Did you tested it? 

If I invert the clause and remove the else then it will not work correctly anymore.

**Comment by MarcoPNS** [comment]
moved to #2523

**Pull request closed without merging**
