### PR TITLE
FEATURE: Add StaticResource helper to Fusion defaults

### PR DESCRIPTION
**Pull request by mficzel**
Add the StaticResource EEL Helper from https://github.com/neos/flow-development-collection/pull/2174 to the Fusion defaultContext. 

StaticResource.uri (packageKey, pathAndFilename, localize)
- (string) packageKey
- (string) pathAndFilename
- (boolean, optional) localize = false

StaticResource.content (packageKey, pathAndFilename, localize)
- (string) packageKey
- (string) pathAndFilename
- (boolean, optional) localize = false

This makes this helper available in afx:

```
  <!-- create static resource uri -->
  <link rel="stylesheet" href={StaticResource.uri('Neos.Demo', 'Public/Styles/Main.css')} media="all" />

  <!-- get static resource content -->
  <style>{StaticResource.content('Neos.Demo', 'Public/Styles/Main.css')}</style>
```

Resolves: #3133

### CODE REVIEW

**Comment by mficzel** [comment]
!!! https://github.com/neos/flow-development-collection/pull/2174 has to be merged to flow first.

**Comment by markuspfeifenberger** [comment]
Should the second Helper only be limited to StaticResource? The second parameter can be `Private/Styles/Main.css` - then this would make sense:    
`<style>{`**`Resource.content`**`('Neos.Demo', 'Private/Styles/Main.css')}</style>`  
  
And if the first should have the same Syntax, like  
 `<link rel="stylesheet" href={Resource.uri('Neos.Demo', 'Public/Styles/Main.css')} media="all" />` the helper can throw an Exception, if the second Parameter start with `Private`

**Comment by mficzel** [comment]
FYI: the tests in this pr fail currently because the StaticResource helper is not in Flow master yet. So this should become green once this is merged t flow

**Comment by mficzel** [comment]
@markuspfeifenberger

> Should the second Helper only be limited to StaticResource? 

That is intended, that way you can use the content of private static resources like json, svg or css without making them public.

> the helper can throw an Exception, if the second Parameter start with Private

If you try to create a public uri for a non public resource you will get an exception that is totally justified. I nevertheless preferred to keep the path-api the same for both methods

**Comment by markuspfeifenberger** [comment]
@mficzel My suggestion is, to name the Helpers `Resource.content` and `Resource.uri` cause you can use them for `Public/*` and `Private/*` resources, where only the `Public/*` are made available as 'Static' - so imho the `Static`in the naming `StaticResource.uri` and `StaticResource.content` suggesting, that only Static files can be passed as `pathAndFilename`

**Comment by mficzel** [comment]
I chose StaticResouce to make sure the distinction from persisted-resouces is clear.

- StaticResporces are all resources in Packages/Resources Public and Private. Offcourse only the public ones have a uri but all can be read,
- PersistedResources are the Flow concept behind Assets. Those can be already handled in Neos but it may make sense in the furture to add a PersistentResource Helper aswell.

I would really like to keep those two helpers separated for clean and sensible apis. If you want to know why i recommend a look at the ResourceUri view helper that handles both resource types in one method.

**Review by daniellienert — APPROVED** [review]
Merged the flow part and restarted test here.

**Review by jonnitto — APPROVED** [review]

**Comment by mficzel** [comment]
Close and reopen to trigger travis

**Comment by mficzel** [comment]
I will merge now. The old travis job is not updated and stuck in a state that did not install neos because of unrelated composer issues

**Pull request merged**
