### PR TITLE
TASK: Removed duplicate condition in Login template

### PR DESCRIPTION
**Pull request by ComiR**

### CODE REVIEW

**Comment by johannessteu** [comment]
Wouldn't this be a problem if you set `settings.userInterface.backendLoginForm.backgroundImage` to null / remove the bg image?

**Comment by ComiR** [comment]
The check is still made, but already in the surrounding `f:if` ;)

**Comment by johannessteu** [comment]
Oh, just checked the red/green lines, you're right 👍

**Comment by aertmann** [comment]
yeah it's left over because the inline `f:if`'s `then` gets evaluated even though the condition returns false

thanks for the fix

**Pull request merged**
