### PR TITLE
TASK: Remove legacy cr functional test artifacts

### PR DESCRIPTION
**Pull request by mhsdesign**
- the sort operation test will be rewritten via https://github.com/neos/neos-development-collection/pull/5015#issuecomment-2102168505
- the content cache test will be rewritten via https://github.com/neos/neos-development-collection/issues/5037
- the `TestObjectForSerialization` has not been used or tested against in Neos 8.3 as well
- the other test things were not referenced and orphaned and thus removed

**Upgrade instructions**

**Review instructions**

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Comment by nezaniel** [comment]
Do we already want to merge this as long as there are references like "xyz test will be rewritten in..." in here?
I'd like to first merge those new tests before removing old ones. Or are the old ones not being run anyway?

**Comment by mhsdesign** [comment]
Yes they are really not, but i put in issues what has to be migrated. Its just super annoying to always come across these in string replacements.

This pr mostly removes the site.xml things ... the real legacy tests ... the Neos ones are still there to be migrated with markAsSkipped.

So this removes just a super small portion that really annoyed me :D

**Review by nezaniel — APPROVED** [review]
Kill it with fire

**Comment by bwaidelich** [comment]
FYI: this one broke `composer test` script => #5095

**Pull request merged**
