### PR TITLE
BUGFIX: Add background color to select option

### PR DESCRIPTION
**Pull request by gerhard-boden**
Add background color to select option for the electronic addresses select box, because it was white text on white background for Windows users.

NEOS-1823 #close

### CODE REVIEW

**Comment by gerhard-boden** [comment]
image

image

**Comment by bwaidelich** [comment]
setting background color on option tags doesn't seem to be supported on Mac OS (tested on Chrome, Firefox and Safari).
BTW: It's a good idea to provide some basic context in the commit/PR message. I was wondering which "electronic addresses select box" this was about. Besides, the fix is actually not limited to that single select box

**Comment by gerhard-boden** [comment]
@bwaidelich: Thanks for the review!

You're right: they are hard to find without context. I added directions in my comment.

It's the only select box i found that uses that specific class. Others  use a different class, or get their styles from a different stylesheet like `Setup.scss` for example. 

Can you post a screenshot how it looks on Mac? Because if the text inside the box is not white on white it's okay i guess.

**Comment by bwaidelich** [comment]
> I added directions in my comment.

Thanks. Even better would be to add the description (first comment) as that will be rendered into the changelog. But don't worry in this case, just in general.

> It's the only select box i found that uses that specific class

Is it? The name suggests otherwise and it is at least also used in the new site package selector.. anyways, didn't mean to split hairs

> Can you post a screenshot how it looks on Mac?

On Chrome & Safari the style has no effect so it looks the same with and without the patch:

image

Of Firefox it *is* supported to change the option but it defaults to the same color anyways so I didn't realize:

image

**Comment by gerhard-boden** [comment]
@bwaidelich 
>Is it? The name suggests otherwise and it is at least also used in the new site package selector.. anyways, didn't mean to split hairs

The CSS and markup in the backend keep confusing me on a regular basis. You're right this particular class  (`.neos-select`) is only used in `EditUser.html`  and `NewSite.html`. All the other select fields are either `.neos-select2` or look similar, but use different styles. But also the box in `EditUser.html` it looks different:
image

So basically this is the only section where the problem occurs (I hope). 

Thanks a lot for your screenshots! As far as I can tell it's currently only a Windows issue, since it looks at least OK (compared to Windows) in your Chrome and correct in Firefox.

**Comment by gerhard-boden** [comment]
> So the "white-on-white" bug also occurs in ``NewSite.html`` and should be fixed by this change

confirmed

>Will also try to get the correct background-color working in Chrome on OS X. 

Added another commit, would need another check by someone with OS X (I know it's annoying, but I can't check it myself)

**Comment by kdambekalns** [comment]
Works fine, as in "doesn't change anything in Chrome on Mac".

**Pull request merged**
