### PR TITLE
FEATURE: Add support for image presets in Fusion

### PR DESCRIPTION
**Pull request by gerhard-boden**
Add image preset support for `Neos.Neos:ImageUri` and `Neos.Neos:ImageTag`.

### CODE REVIEW

**Comment by aertmann** [comment]
Thanks for pushing, personally I consider it a bug that it was not introduced with the original change tbh. so would prefer adding this to 2.2 instead as it's non-breaking and low risk. But others might object.

**Comment by mficzel** [comment]
I like this and i have no problem with this in 2.2 but please add the preset option to the fusion-documentation aswell. 

Note:  There is already another pr that adds the missing width and height to the ImageUri-docs (https://github.com/neos/neos-development-collection/pull/1431).

**Comment by kitsunet** [comment]
No backports of features please!

**Comment by gerhard-boden** [comment]
Thanks for your feedback guys!

yeah we had this discussion already and i've grown very cautious when it comes to features in bugfix releases, because I already brought in some breaky stuff not too long ago:
https://neos-project.slack.com/archives/teams/p1485878810000377

No `@api` markers in here, but I think it's still safer not do it.

@mficzel: For < 3.0 you could provide a custom `ImageUriImplementation` with preset support if needed. Should be pretty safe to do that. 

I will provide the documentation part tomorrow evening.

**Comment by gerhard-boden** [comment]
documentation turned out to be a one liner:
https://github.com/neos/neos-development-collection/pull/1437/files#diff-820865815992bff5216cadb67a052866R829

**Pull request merged**
