### PR TITLE
Fix/rebuild compiled files

### PR DESCRIPTION
**Pull request by fcool**
**What I did**
I suspected my problems described in #3382 are the result of outdated code in compiled sources. So I tried to rebuild them.

**How I did it**

```
cd Packages/Neos/Neos.Neos/
git clone -b 4.3 https://github.com/neos/neos-development-collection /tmp/neos-development-collection
cp -a /tmp/neos-development-collection/Scripts/ Scripts/
cd Scripts/

mkdir gems
bundler install --path gems

sed -i "s/ContentModuleBootstrap/LegacyUiBootstrap/; s/ContentModule-built/LegacyUiBootstrap-built/; s/Content\/Inspector\/.*,//g" build.js

npx grunt build-js
```

and for the yarn part:
```
cd Packages/Neos/Neos.Neos
yarn build:production
```

### CODE REVIEW

**Comment by Sebobo** [comment]
Seems to work, thx a lot! :) 

Question is whether to add the scripts also again to the repo in the 5.x branch so that next time the build can be achieved without further headache. We still support the 5.3 LTS version for quite a while

**Comment by Sebobo** [comment]
Also seems to fix #3297 properly for all cases ...

**Review by Sebobo — APPROVED** [review]
Works well for me

**Review by markusguenther — APPROVED** [review]
Thanks, @fcool for this PR and investigation.
Like @Sebobo already said, it works fine. We just need to be careful with the upmerges

**Pull request merged**
