### PR TITLE
TASK: Corrected naming in documentation

### PR DESCRIPTION
**Pull request by iseries**
Replaces ``TYPO3.Neos`` with ``Neos.Neos``

### CODE REVIEW

**Comment by kdambekalns** [comment]
Thanks @iseries – and congratulations to your first PR. 🚀

**Comment by iseries** [comment]
Jordi Boggiano's speak at the neos conference was very inspiring. So, to help on github is "very important, even it is a very small change in the documentation" ;D

**Comment by daniellienert** [comment]
👍🏼🎁 Thanks again!

**Comment by kitsunet** [comment]
Awesome, thanks!

**Comment by skurfuerst** [comment]
thanks for your contribution 👍 ❤️

**Pull request merged**
