### PR TITLE
TASK: Rename TYPO3CR where possible

### PR DESCRIPTION
**Pull request by jonnitto**
Affects #2842 and #3137

### CODE REVIEW

**Comment by kdambekalns** [comment]
Phew… I need to check that in depth. When it comes to these old migrations… changing them might be futile. I mean, they needd to be adjusted, to have PHP run the code as a whole. But this week I upgraded a Neos 1.1 to 5.3, and had to do intermediate steps anyway (PHP 5.6 and Neos 2.0 to adjust from serialized node properties to JSON).

But I guess revisiting migrations is a topic on it's own… _sigh_

**Comment by bwaidelich** [comment]
@kdambekalns What do you mean? As far as I can tell, the migrations has only been moved

**Comment by kdambekalns** [comment]
> @kdambekalns What do you mean? As far as I can tell, the migrations has only been moved

True, true. They need to be moved. But in general, we need to investigate migrations and can trim some, that won't be able to run in a current setup anymore.

**Comment by bwaidelich** [comment]
> True, true. They need to be moved. But in general, we need to investigate migrations and can trim some, that won't be able to run in a current setup anymore.

OK, but that can be done separately from this change. Or do you think we should block this one?

**Comment by kdambekalns** [comment]
> Or do you think we should block this one?

No, that's what I wanted to express with

> But I guess revisiting migrations is a topic on it's own… sigh

**Review by kdambekalns — APPROVED** [review]

**Review by markusguenther — APPROVED** [review]
Works fine 👍

**Pull request merged**
