### PR TITLE
Update doc

### PR DESCRIPTION
**Pull request by tdausner**
**What I did**
update of doc in function evaluate()

**Checklist**
no change of code

### CODE REVIEW

**Comment by jonnitto** [comment]
This will fix #3238

**Review by daniellienert — CHANGES_REQUESTED** [review]
@tdausner Hey Thomas, something went wrong with you PR, it should only contain the documentation changes but currently contains a lot more commits.

**Comment by tdausner** [comment]
> @tdausner Hey Thomas, something went wrong with you PR, it should only contain the documentation changes but currently contains a lot more commits.

@daniellienert Hi Daniel, I have no clue what happened. This is my latest commit: https://github.com/neos/neos-development-collection/pull/3285/commits/2b5d74ec65cdef0b74fdcc1f7db5dcef1de7b5a0. Any idea?

**Comment by jonnitto** [comment]
I think your `master` branch was outdated. And your PR should be done against the 7.0 branch

**Comment by jonnitto** [comment]
Perhaps it is the easiest way to close this PR and create a new one…

**Comment by jonnitto** [comment]
Close this in favor of https://github.com/neos/neos-development-collection/pull/3527

**Pull request closed without merging**
