### PR TITLE
BUGFIX: Avoid Array.push on NULL value

### LINKED ISSUE #3657: Rendering results in $array must be of type iterable|scalar got: NULL
### Description

`$array must be of type iterable|scalar got: NULL`

### Steps to Reproduce

1. On master, import demo site
2. Create user, log in to backend

#### Expected behavior

The homepage is shown in the content module

#### Actual behavior

image

### Affected Versions

Neos:  master as of 2022-03-23 22:19 CET

### PR DESCRIPTION
**Pull request by kdambekalns**
Fixes #3657

### CODE REVIEW

**Comment by kdambekalns** [comment]
Or should `Array.push()` accept NULL and treat it like an empty string or empty array?

**Comment by mhsdesign** [comment]
i actually thought about this case and what happens when you do:
`Array.push(null, 'someclass')` results in => `[null, 'someclass']`

but this works for fusion as the rendered html would look like `class="someclass"` `null` will be ignored.

or doesnt fusion like this?

**Comment by mhsdesign** [comment]
wait sorry my assumtion was, that `is_scalar()` would pass on `null`

**Comment by mhsdesign** [comment]
we should allow `Array.push(null, 'foo')` , by extending the `is_scalar()` check to also check for `null`

... sorry for messign this up so short before the release @kdambekalns  (i messed this up with: https://github.com/neos/neos-development-collection/pull/3654)
i think we should roll with this pr to make the backend usable right?

**Review by mhsdesign — DISMISSED** [review]

**Comment by kdambekalns** [comment]
I think we should really rather fix `Array.push()`, as in neos/flow-development-collection#2760

**Pull request closed without merging**
