### PR TITLE
TASK: Pass ContentStreamId to NodeFactory

### PR DESCRIPTION
**Pull request by dlubitz**

### CODE REVIEW

**Review by ahaeslich — APPROVED** [review]
by reading 👀

**Comment by kitsunet** [comment]
Why is this necessary?

**Comment by dlubitz** [comment]
@mhsdesign requested that as preparation for the node identity.

**Comment by kitsunet** [comment]
Mmmm, @mhsdesign gimme some more background. Shouldn't we resolve this some other place before hitting this?

**Comment by mhsdesign** [comment]
@kitsunet Thats what we discussed in the weekly from the 01-03-2024.

1. NodeFactory::mapNodeRowToNode  must accept WorkspaceName and ContentStreamId from outside.
2. returned array  $nodeRow does not need to contain $csId as this is part of the query (optional)

**Comment by mhsdesign** [comment]
And its good to see that all tests pass, because that means we never fetch foreign nodes in a subgraph.
The question is if we should do also 2, to remove the returned csStreamId field from the node data to reduce transferred things?

**Comment by mhsdesign** [comment]
Bastians subtree tag pr goes first.

And yes we discussed that we can remove the csStreamId from the selects, which might even be noticeable for recursive queries.

**Review by kitsunet — APPROVED** [review]

**Review by bwaidelich — APPROVED** [review]
+1 by reading

**Pull request merged**
