### PR TITLE
BUGFIX: Fix the document list in the Aloha Link Editor styling

### PR DESCRIPTION
**Pull request by dfeyer**

### CODE REVIEW

**Comment by dfeyer** [comment]
:+1:

**Comment by kdambekalns** [comment]
Works, even though the styling is a bit off, somehow…
icon-offset

**Comment by dfeyer** [comment]
Last version fix the vertical alignement in Firefox ... without breaking Chrome ... don't ask if I want to book IE please

**Comment by kdambekalns** [comment]
:+1:

**Comment by kdambekalns** [comment]
Feel free to merge once Travis turns green… :)

**Pull request merged**
