### PR TITLE
FEATURE: Show the default asset-collection in the sites listing

### PR DESCRIPTION
**Pull request by daniellienert**
image

### CODE REVIEW

**Review by albe — APPROVED** [review]
Looks good by reading. Can someone make a screenshot?

**Comment by daniellienert** [comment]
@albe screenshot added

**Comment by daniellienert** [comment]
The colspans needed to be adjusted as well, which is done now.

**Comment by albe** [comment]
One additional review and I'll merge :)

**Review by Sebobo — APPROVED** [review]
Looks good to me :)

**Comment by albe** [comment]
Ka-ching! Thanks :)

**Pull request merged**
