### PR TITLE
FEATURE: Add ModulePrivilege to protect Neos Backend modules

### PR DESCRIPTION
**Pull request by bwaidelich**
Introduces a new Privilege `ModulePrivilege` that should be used to
access-protect Neos Backend modules.

Usage:

    privilegeTargets:

      'Neos\Neos\Security\Authorization\Privilege\ModulePrivilege':

        'SomePrivilegeTargetIdentifier':
          matcher: 'module/path'

This new privilege will be used to hide links to inaccessible modules
in the Backend. Furthermore they automatically protect access to all
actions of the configured controller of the affected module.

Setting a `privilegeTarget` in the module settings is still supported
but deprecated as of Neos 3.2.

Related: #964

### CODE REVIEW

**Comment by aertmann** [comment]
Hey @bwaidelich, got some things that would be great to clarify.

1. The privilege targets are still hardcoded in the module configuration in settings, is that intended? They should be unnecessary right?

2. Now it depends solely on the configuration path, hence you'd have to create new privilege targets if you move/rename module paths. Did you consider that?

3. It's still possible to make more fine grained policies on top right? 

4. The ticket is about an administrator being able to control access to modules for users, this change doesn't solve that. Is this simply a step to make that possible or?

5. Also get this error when displaying the content module I get

```Access denied for method

Method: Neos\ContentRepository\Domain\Service\Context::validateWorkspace()```

**Comment by bwaidelich** [comment]
@aertmann FYI thanks a lot for your valuable feedback! I didn't get around it yet, but I'll try to address your comments in a follow-up later today or next week

**Comment by bwaidelich** [comment]
@aertmann ..and finally:

> 1. The privilege targets are still hardcoded in the module configuration in settings

Good catch. They are gone now!

> 2. Now it depends solely on the configuration path, hence you'd have to create new privilege targets if you move/rename module paths. Did you consider that?

Yes, thought about it but I doubt that those paths get changed a lot. And if they do you immediately get an exception during compile time:
```
The module "<old-module-path>" specified in privilege target "<module-privilegeTarget-identifier>" is not configured
```
so I guess this is fine. I added a phrase to the corresponding documentation to make that clearer.

> 3. It's still possible to make more fine grained policies on top right?

Yes. The `ModulePrivilege` basically just protects all public actions of the configured module controller by default  (btw: using `./flow security:showmethodsforprivilegetarget` I found out that we forgot to protect some of the actions previously!).
I added a phrase to the documentation explaining that additional privileges can be configured as before

> 4. The ticket is about an administrator being able to control access to modules for users [...]

Right! I adjusted the ticket for now, as the whole "ACL via Backend"-topic is a separate chapter that requires https://github.com/neos/flow-development-collection/issues/593 as basis

> 5. Also get this error when displaying the content module I get
Access denied for method
Method: Neos\ContentRepository\Domain\Service\Context::validateWorkspace()

Mh.. I can't reproduce that and I can't see how this could be related.
`\Neos\ContentRepository\Domain\Service\Context::validateWorkspace()` is covered only by the "fake" privilegeTarget `Neos.Neos:Backend.OtherUsersPersonalWorkspaceAccess` to prevent publishing of foreign workspaces.
With which roles do you get the exception and did you try flushing the caches?

**Comment by aertmann** [comment]
> Yes, thought about it but I doubt that those paths get changed a lot. And if they do you immediately get an exception during compile time:

This would make it breaking though right? In case someone renamed them. Can be discussed if that's a problem or not of course.

> I found out that we forgot to protect some of the actions previously!).

Uh oh. We have to fix that in the released versions right?

> With which roles do you get the exception and did you try flushing the caches?

Figured it out, for some reason the workspace had lost it's owner relation. Didn't do anything in the database, so watch out if something similar happens to you.

**Comment by kdambekalns** [comment]
Hah. Better! :)

**Comment by kdambekalns** [comment]
@aertmann Feel free to merge, if you agree…

**Comment by bwaidelich** [comment]
> This would make it breaking though right? In case someone renamed them. Can be discussed if that's a problem or not of course.

Personally I think it's a breaking change we can live with (if documented in the release notes).

>> I found out that we forgot to protect some of the actions previously!).

> Uh oh. We have to fix that in the released versions right?

I checked it, nothing to be fixed!

**Comment by aertmann** [comment]
@bwaidelich Thanks for the update.

Tested it and tried renaming a module which worked if you override the path in the matching policy, so that should be fine.

Also I agree that it should be fine as a breaking change, doubt anyone has really done it.

However if you unset a module, there's no way of unsetting the matching privilege target, blocking you from removing that module. There are some other issue related to unsetting modules, so won't block this change because of that, but will bring up that issue in general on Slack.

So 👍 from my side and thanks for implementing @bwaidelich

**Comment by bwaidelich** [comment]
> However if you unset a module, there's no way of unsetting the matching privilege target

Ha, good point. It should be possible to write
```yaml
privilegeTargets:
  '<PrivilegeClassName>':
    '<PrivilegeName>': ~
```
If that's not possible yet, we should fix it in Flow.

Thanks for merging!

**Comment by aertmann** [comment]
Tried that actually, doesn't work currently.

**Comment by bwaidelich** [comment]
For the record: There's an `enable` flag in the module settings (as you just pointed out in Slack)

**Pull request merged**
