### PR TITLE
TASK: Use the new ResourceManager API in ResourceUriImplementation

### PR DESCRIPTION
**Pull request by dfeyer**
This change refactor ResourceUriImplementation to use the new API provided
by the ResourceManager

### CODE REVIEW

**Comment by dfeyer** [comment]
Require https://github.com/neos/flow-development-collection/pull/188

**Comment by aertmann** [comment]
shouldn't this to into 2.1 or?

**Comment by kitsunet** [comment]
would make sense somehow

**Comment by dfeyer** [comment]
Just to have travis running now that the Flow dependencies have been merged

**Comment by dfeyer** [comment]
Closed in favor of https://github.com/neos/neos-development-collection/pull/377

**Pull request closed without merging**
