### PR TITLE
FEATURE: Add additionalParams to ConvertUrisImplementation

### PR DESCRIPTION
**Pull request by jonnitto**
If you create newsletter with Neos, it is crucial to have some additional parameters like `utm_source`, `utm_medium` and `utm_campaign` to every link. This change enables the `ConvertUrisImplementation` to have `additionalParams`.

```
prototype(Neos.Neos:ConvertUris) {
    absolute = true
    forceConversion = true
    additionalParams {
         utm_source = 'newsletter'
         utm_medium = 'email'
         utm_campaign = ${node.label}
    }
}
```

### CODE REVIEW

**Comment by bwaidelich** [comment]
We mix that in other parts already, but additionalParams != query arguments.
IMO we should keep the routing part to the `UriBuilder` and don't mess with the resolved URI "manually".
Depending on your routing setup the resolved URL could already contain query arguments so appending additional ones with `?...` would not work.
Instead we should probably extend `LinkingService::resolveNodeUri()` such that it can accept additional arguments that it passes to https://github.com/neos/neos-development-collection/blob/1427f95582140132c8f4ce92b7e073edf2ae5e83/Neos.Neos/Classes/Service/LinkingService.php#L245

I also wonder if those arguments are always to be appended to node _and_ asset links.

**Comment by markusguenther** [comment]
Something new about this PR? It seems like an ongoing discussion :)

**Comment by markusguenther** [comment]
Can we find a solution here?  As we have feature freeze tomorrow ;)

**Comment by bwaidelich** [comment]
> Can we find a solution here?

I still stand to my suggested solution (extend `LinkingService::resolveNodeUri()`) but it would require proper testing and I can't take care of this atm.

To work around the limitation (i.e. to achieve what @jonnitto described in the original PR message) I would suggest to add a separate processor that just appends query parameters to already converted URLs:
```
@process.convertUris = Neos.Neos:ConvertUris
@process.addNewsletterQueryParams = Some.Package:AddQueryParamsToLinks {
  params {
         utm_source = 'newsletter'
         utm_medium = 'email'
         utm_campaign = ${node.label}
  }
}
```

**Comment by jonnitto** [comment]
I think, it won't make it into 7.3 anyway, but I will look to bring it into Neos 8 with the extended `LinkingService`

**Comment by markusguenther** [comment]
Are you able to work on that for 8.3?

**Comment by bwaidelich** [comment]
This might be related to https://github.com/neos/flow-development-collection/pull/2744

**Comment by bwaidelich** [comment]
..and maybe https://github.com/neos/neos-development-collection/pull/3914

**Comment by mficzel** [comment]
Not sure about this, i would rather use a custom processor for that rather than extend convertUris. 

```
@process.convertUris = Neos.Neos:ConvertUris
@process.addTrackingParams = Vendor.Site:AddTrackingParameters {
    utm_source = 'newsletter'
    utm_medium = 'email'
    utm_campaign = ${node.label}
}
```

Could be distributed as package for reusability so imho there is no need to support this directly from the core. 

Just seen that Bastian already suggested a custom processor for that. So i second that

**Comment by Sebobo** [comment]
@jonnitto you want to take another try at this or should we close it?

**Pull request closed without merging**
