### PR TITLE
TASK: Make ContentObjectProxy act as overlay to NodeData

### PR DESCRIPTION
**Pull request by dfeyer**
Currently the ContentObjectProxy object must implement all the required
property defined in a Node Type. This is not really flexible. Most use
case for the ContentObjectProxy is to expose a Doctrine entity, like a
City, but the developper don't want to bloat the given entity with all
the required node property.

This change change the default behaviour of the ContentObjectProxy. Now
the default behavior is to use the property definied in the
ContentObjectProxy is this property is accessible or fallback the the
NodeData property to all other properties.

This change also add support for reference(s) type property stored in
the ContentObjectProxy.

NEOS-1797 #resolves

### CODE REVIEW

**Comment by dfeyer** [comment]
Check the discussion with @bwaidelich on Gerrit
https://review.typo3.org/#/c/37877/

**Comment by dfeyer** [comment]
PSR2 change

**Comment by dfeyer** [comment]
Break the test by purpose, with this change, if you try to get a property that not exist in the content object proxy, you receive a NULL value, like with a normal node. This change allow more flexibility, like implementing a property in the node. So the CO can implement property "one" and the node can define additional property like "two", "three", ... the first property will get from the CO, the other, like a normal node, in the serialized JSON.

**Comment by kitsunet** [comment]
How can we proceed with this? I think it generally makes sense...

**Comment by dfeyer** [comment]
@kdambekalns Why wrong branch ? It's targeted for master ?

**Comment by kdambekalns** [comment]
TBH I don't remember off the top of my head. But I think it's because master will not be 3.0 as of now, but 2.2, so no breaking changes must be moved.

**Comment by kdambekalns** [comment]
I checked this out and merged master into it, the result lives at https://github.com/kdambekalns/neos-development-collection/tree/37877. Travis build is at https://travis-ci.org/kdambekalns/neos-development-collection/builds/144086094.

@dfeyer if you grant me push permission on your fork, I'll gladly push there to keep this discussion intact. Or we replace this PR. As you wish…

And then, what is the status? Is this breaking (then we must not merge it into 2.3) or not (I assume the latter, mostly because of the "important for 2.3" label)? What about the WIP label?

**Comment by dfeyer** [comment]
> And then, what is the status? Is this breaking (then we must not merge it into 2.3) or not (I assume the latter, mostly because of the "important for 2.3" label)? What about the WIP label?

Basically the feature is broken currently, you need custom node implementation to make it working. I will try to make it more friendly by introducing a new Interface ContentProxyProxyableEntityInterface, and a service to keep the nodedata and the doctrine entity in sync. And if some change happend in the doctrine entity the CR need to emit the proper signal like if the node was edited directly on the CR.

I don't think the PR is breaking, its just try to proxy the doctrine data in the CR and not only update the attached doctrine entity. So it's stay compatible with Elastic, FlowQuery, ... 

I work on this right now, because I need for architectes.ch

**Comment by dfeyer** [comment]
About tests:
> TYPO3\TYPO3CR\Tests\Unit\Domain\Model\NodeDataTest::getPropertyThrowsAnExceptionIfTheSpecifiedPropertyDoesNotExistInTheContentObject

I think we can solve this one to be non breaking. Currently it's allowed to have a property define in the node (stored in the CR), but not on the Doctrine entity. But I think the feature is pretty useful.

**Comment by kdambekalns** [comment]
Ok, pushed my changes. It was a force push, since I decided to reword the commit message of the first change, no other changes to that commit were done.

**Comment by kdambekalns** [comment]
Sounds like a plan…

**Comment by aertmann** [comment]
@dfeyer: I've used the existing feature a couple of times to ease indexing data in ES just fine, will it be easy to migrate to the new stuff? I'm all for improving the content object proxy stuff, but we should try to find a way to make it less breaking or wait for 3.0

**Comment by dfeyer** [comment]
The development continue in a forked version of the CR:
https://github.com/architectesch/neos-development-collection/pull/1

A this is breaking (better but breaking), not not for LTS.

**Comment by mficzel** [comment]
What is the state of this PR. It is labeled WIP and currently has merge conflicts? Also there is a pr to for branch that is not merged.

**Comment by kitsunet** [comment]
@dfeyer I would really like to get this done, you said you continue in the forked CR repository. So do we close this PR and maybe make a concentrated effort to get this back from your fork to here?

**Pull request closed without merging**
