### PR TITLE
TASK: Use whole package key for generating site node name

### PR DESCRIPTION
**Pull request by 2case**
**What I did**

Refactor the siteNodeName generation. It is now based on the complete package key.
Also i did some code cleanup.

**How to verify it**

Simple use the `./flow kickstart:site` command. You can verify the siteNodeName inside the generated `Resources/Private/Content/Sites.xml`

### CODE REVIEW

**Comment by aertmann** [comment]
was wondering, this could potentially be breaking right? is that why it's targeted master?

**Comment by 2case** [comment]
Hu? Did i choose the wrong target branch? I will check/talk/ask about it with christian today at the sprint after breakfast :)

**Comment by kitsunet** [comment]
I don't think it's breaking as it just happens on new sites. But still I wouldn't want to change existing behaviour in older versions, therefore I suggested master.

**Comment by aertmann** [comment]
okay thanks for clarifying, it's a stretch but can be breaking if one uses the generator to create sites and relies on finding the site using the same method for turning the package key into site node name..

fine with master too

**Pull request merged**
