### PR TITLE
BUGFIX: Adapt media CLI command to import resources after vendor name changes

### PR DESCRIPTION
**Pull request by sunweiye**
This change

1. Fixes an by checking Doctrine ORM Entity Manager during calling the command.
2. Renames the used table names to the actual names in the database.
3. Uses `ConfigurationAssetModelMappingStrategy` to determine target asset type.

### CODE REVIEW

**Comment by dfeyer** [comment]
Thanks @sunweiye for your first contribution and sorry for the late answer/review. 

Just tested your PR and work fine.

**Comment by kdambekalns** [comment]
Notes from original PR comment:

---

**How I did it**

1. Add lazy=false in the annotation of entityManager
2. Check the actual table names of in the database and adapt the names in the code
3. Remove the code in the for loop in the method of importResourcesCommand that is only to add image into the repository. The code, that uses the map method of ConfigurationAssetModelMappingStrategy to get the resource model object, is added and the resource model object will be added into the repository. 

**How to verify it**

For point 1 and 2, run the command, and there will not show any error message.
For point 3, the resource should be added.

**Comment by daniellienert** [comment]
Fix #1482 
I Would merge this one if no one objects.

**Comment by kitsunet** [comment]
Go for it

**Pull request merged**
