### PR TITLE
FEATURE: Allow Administrator to impersonate a User

### PR DESCRIPTION
**Pull request by dfeyer**
This change add an action in the user edit and show action to impersonate
this user in the backend if it's possible.

### CODE REVIEW

**Comment by dfeyer** [comment]
First step for this feature. Now an administrator can navigate to the User Management module, edit a user and chosse an Account to impersonate. The backend will be reloader with the new Account.

Features
- [x] Basic impersonate
- [ ] Restore previous session on logout
- [ ] Adapt the user menu to show that you are in "impersonate" mode

When the feature is done done, we should check what can be moved in Flow, to make creating this feature in other application easier. As I don't see this parts of Flow Framework by default, it should be a standalone package la Neos.Impersonate that contains the basic feature.

**Comment by bwaidelich** [comment]
This is a really nice feature, but I have some issues with it:

* I would prefer the core functionality to be implemented in the Authentication Framework (or alternatively within a separate package during incubation).
* In general I would like to have the impersonation more "explicit" somehow:
With the current approach an admin would completely take over another account and all actions will be logged under that account. Impersonation can also mean that you temporarily take over the *roles* of the other account.
* This feature depends on a server session. It's not the only part in Neos, but in general we should not increase the dependency (see https://github.com/neos/neos-ui/pull/2131 for a related discussion)
* This is a very critical change (a similar feature has recently been the attack vector for a major [hack on Facebook](https://newsroom.fb.com/news/2018/09/security-update/)) so it should be covered with tests. And probably it should be possible to disable the feature completely

What about a new marker interface that tokens can implement (similar to the `SessionlessTokenInterface`) and some convenience methods on the `Security\Service`?

**Comment by dfeyer** [comment]
@bwaidelich Thanks for the comments, this is a prototype, I fully agree that this feature should be shipped as an external package, with a really slim API on Flow (and not Neos).

> With the current approach an admin would completely take over another account

Currently the requirement for this feature, is to make it more easy to support editor when they have issue in their own workspace. So the "full" take over is OK. I agree that can be improved, but can be done later.

I agree that this feature MUST be behind a feature flag for security reason and battle tested ;)

**Comment by dfeyer** [comment]
> This feature depends on a server session. It's not the only part in Neos, but in general we should not increase the dependency (see [neos/neos-ui#2131](https://github.com/neos/neos-ui/pull/2131) for a related discussion)

@bwaidelich Not sure how did you want to implement this feature, only on the client side without using a backend session.

**Comment by bwaidelich** [comment]
Sorry for the late response, stale bot brought me here :)

> Not sure how did you want to implement this feature, only on the client side without using a backend session.

For example via a [JWT](https://jwt.io/): The server issues a token that allows users to impersonate other accounts (if they have the privileges).
Thinking about this, that could probably achieved with a custom Auth Provider today already: It would act _on top_ of an existing provider and replace the authenticated account if a corresponding Token is sent with the request

**Comment by lorenzulrich** [comment]
How much sponsoring would it take to finish a package (Neos 4.3+ compatible) with an impersonate feature that can be used by Neos admins to impersonate another user by switching from the User Management module? Would someone be willing to do this if money is raised?

**Comment by bwaidelich** [comment]
@lorenzulrich To make this a solid feature, this should be implemented in Flow I think and we'd have to decide on the "impersonation mode" (i.e. should it simulate another account, only their roles or actually switch to the other account). See my points from [November](https://github.com/neos/neos-development-collection/pull/2269#issuecomment-438654683).

A first version (compatible with Neos 4.3) could probably be implemented in a separate package (augmenting/hijacking the User Module).
I could imagine that this should work with a special Auth Provider/Token that can switch to an account while keeping record of the actual authenticated account so that it can switch back.

It would need some more thought, but I imagine that this could be done in 3-5 days

**Pull request closed without merging**
