### PR TITLE
TASK: Allow using the context variable in node privileges

### PR DESCRIPTION
**Pull request by Sebobo**
This makes it possible to access global objects via the context variable in node privileges.

For example this can be used to hide nodes based on a node property which needs to
match a username or group. One use case is to have several sites in one Neos and restrict
each user to one site.

How it works: The values given to the `ConditionGenerator` of the node privileges are
first put through `getValueForOperand` instead of treating them just as string.

### CODE REVIEW

**Comment by kdambekalns** [comment]
Review hints from original description:

---
**How to verify it**

Use a matcher like this:
```
    privilegeTargets:
      'Neos\ContentRepository\Security\Authorization\Privilege\Node\ReadNodePrivilege':
        'Neos.ContentRepository:Workspace':
          matcher: 'isInWorkspace("context.userInformation.personalWorkspaceName“))’
```

**Comment by kdambekalns** [comment]
@Sebobo Ah, wait. A feature to go into 3.0? Might this need to be adjusted to target master?

**Comment by Sebobo** [comment]
@kdambekalns I discussed this with @kitsunet during the sprint and he called this change a "Non delivered promise", that's why I targeted to 3.0.
Bugfix is also not completely correct...

**Comment by kitsunet** [comment]
I would like to see it in 3.0 as we never said that the global context is not available in those privileges and I definitely expected it...

**Comment by gerhard-boden** [comment]
Do we have documentation for this yet?

**Comment by kdambekalns** [comment]
@Sebobo What about the documentation @gerhard-boden asked about? Anything else missing? @kitsunet – would you review this "officially"?

**Comment by Sebobo** [comment]
@gerhard-boden @kdambekalns I can't find any documentation to the global objects at all. Thought I would just add it to that.
Did we never document them? Or am I just blind?

**Comment by kdambekalns** [comment]
[PR #1661](https://trello.com/c/BWXpE5lQ/4-pr-1661)

**Comment by kdambekalns** [comment]
I added documentation (and also created the related https://github.com/neos/flow-development-collection/pull/1095)…

**Comment by Sebobo** [comment]
Awesome thanks

**Pull request merged**
