### PR TITLE
TASK: Exchange Wallpaper for Neos 7.2

### PR DESCRIPTION
**Pull request by daniellienert**
The picture is taken by myself and can be used free of charge.

I used a webp this time for the wallpaper, as it is only 286k
instead of 1.2M for the jpg variant.

Voting result: https://discuss.neos.io/t/neos-7-2-login-wallpaper/5571/12

### CODE REVIEW

**Review by jonnitto — APPROVED** [review]

**Comment by markusguenther** [comment]
Hmm I like WebP as format but what happens if you use a Mac with safari 13? It's from 2020 and still a supported macOS.

Or what when the php has no imagewebp installed? Guess we have this actually not as required dependency right?

Or do I miss something?

**Comment by daniellienert** [comment]
@markusguenther 
1. Mhm. I get your point. I would say, if there are people out there using an old Safari (Safari 14 can be installed since Catalina from 2019) to work with Neos and complaining that they do not this see beautiful picture, we add a fallback image as bugfix.
2. The image is a local resource and should not face the PHP process, so no PHP extension is needed to serve the image.

**Comment by kdambekalns** [comment]
> @markusguenther
> 
>     1. Mhm. I get your point. I would say, if there are people out there using an old Safari (Safari 14 can be installed since Catalina from 2019) 

Yes, but per https://caniuse.com/webp the WebP support in Safari 14 is limited to Big Sur or later. I could not find a source for this, though and have no pre-Big Sur Mac at hand. I'd say it's not a big deal, but would still be interesting to kow more.

**Comment by markusguenther** [comment]
I have an older iMac that is used just as second screen right now. I can check the OS Version and maybe downgrade for a check. I just had in mind that for end users this could be an issue.

**Comment by markusguenther** [comment]
Ok we have Mojave on the 5k iMac with Safari 12. So will set up a neos with the PR and test it later. Also need to check if I can easily update the safari. When the Neos works (will have it public) I can also test some other versions with browserstack or so.

**Comment by daniellienert** [comment]
@markusguenther that sounds like a lot of work. Wouldn't it be better to just add a fallback image or skip the webp and use jpg again

**Comment by daniellienert** [comment]
@kdambekalns from Wikipedia:

Safari 14 was released as a standalone update to macOS Catalina and Mojave users on September 16, 2020.[97]

**Comment by kdambekalns** [comment]
> Safari 14 was released as a standalone update to macOS Catalina and Mojave users on September 16, 2020.[97]

Yes, but if WebP support depends on the underlying macOS, that won't help. And that's what I don't know…

**Comment by jonnitto** [comment]
I'll create a PR who use a jpeg if webp is not supported

**Comment by markusguenther** [comment]
Just for the better understanding in the future.

**MacOS Mojave with Safari 12:**
Bildschirmfoto 2021-08-20 um 12 42 05

**MacOS Mojave with Safari 14:**
Bildschirmfoto 2021-08-20 um 12 45 47

**Pull request merged**
