### PR TITLE
BUGFIX: Fix typo in error message

### PR DESCRIPTION
**Pull request by gerhard-boden**

### CODE REVIEW

**Comment by johannessteu** [comment]
Should be fixed in 2.0 @gerhard-boden, at least i can see the typo there too. Could you recreate the PR against 2.0?

**Comment by gerhard-boden** [comment]
Hi,

The older maintained branches are fine, issue was introduced in 2.2 

Can't see the typo here:
https://github.com/neos/neos-development-collection/blob/2.0/TYPO3.Neos/Resources/Public/JavaScript/Content/Components/ContentDimensionController.js#L288
https://github.com/neos/neos-development-collection/blob/2.1/TYPO3.Neos/Resources/Public/JavaScript/Content/Components/ContentDimensionController.js#L288

**Comment by johannessteu** [comment]
Ah, then it's another issue :D

https://github.com/neos/neos-development-collection/blob/2.0/TYPO3.Neos/Resources/Public/JavaScript/Content/Components/ContentDimensionController.js#L248

**Comment by gerhard-boden** [comment]
sorry, worked too much overtime this week:
https://github.com/neos/neos-development-collection/pull/630

**Pull request closed without merging**
