### PR TITLE
[TASK] Make the ConvertUrisImplementation extensible

### PR DESCRIPTION
**Pull request by michaelgerdemann**
With this change the ConvertUrisImplementation is more extensible.
The anonymous function is now a normal method, so now the URLs are better
expandable via an aspect.

Resolves: NEOS-1477

### CODE REVIEW

**Comment by reflexxion** [comment]
Wouldn't it be nicer to have some configuration options to register `uriResolvers`?


BTW: Comments here or in jira?

**Comment by kitsunet** [comment]
Good step, IMHO we should leave the whole logic about schemas to the linking service and just call it and then make that extensible.

**Comment by aertmann** [comment]
Making something extensible with aspects is a code smell. If it should be extensible, there should be a proper API for it.

+1 for what @kitsunet said as well

**Comment by michaelgerdemann** [comment]
Okay, i close this PR and we should build an API for it.

**Pull request closed without merging**
