### PR TITLE
BUGFIX: Use media type of new resource during asset replacement

### LINKED ISSUE #3365: Replacing an asset with a different type and "keep filename" is broken
### Description

Replacing an asset with an asset of a different type (e.g. an SVG with a PNG) works fine unless the option to keep the original filename is used.

### Steps to Reproduce

1. Upload an SVG asset
2. Replace that asset with a PNG and check "Keep the filename …"

#### Expected behavior

The asset is replaced and the type reflects what has been uploaded, regardless of the original filename.

#### Actual behavior

The type is left unchanged, leading to errors for operations that rely on that type (e.g. thumbnail rendering).

### Affected Versions

Neos: 7.1.0 (and probably earlier)

Flow: 7.1.0 (and probably earlier)

### PR DESCRIPTION
**Pull request by kdambekalns**
When the resource of an asset is replaced but the filename kept, the
media type of the new asset is replaced by whatever the original
filename indicates.

This change fixes that by re-setting the media type from the new
resource after the original filename has been set.

Fixes #3365

### CODE REVIEW

**Review by Sebobo — APPROVED** [review]

**Review by grebaldi — APPROVED** [review]
There's no way to change the filename afterwards, right?

I tested the svg example and though I got a preview image, opening it in a new tab still leads to a browser error:

image

Would it make sense to replace the file extension as well? Or would that be out of scope?

**Comment by kdambekalns** [comment]
@grebaldi That's caused by the browser thinking it knows the type from the filename? Or is the server (still) sending a wong mime type header (because of the filename?)

I'd consider that out of scope, to be honest – unless we decide that replacing an existing resource with a different type while keeping the name is a stupid idea anyway. In that case another option would be to reject that replacement, if the types don't match.

Changing the name, even though it should be kept seems wrong, so I don't really consider that an option.

🤔

**Comment by grebaldi** [comment]
I tested again:

The server is indeed sending the wrong content type:
image

In Firefox, the image is displayed correctly when used via ``-Tag. In Chrome however (well, actually Chromium and Brave - but should be the same), the ``-Tag is displayed as empty.

I have no idea, which component is causing this, though. Might be nginx even. I mean - the image should be served out of `Web/` without Flow being involved at all, right?

Considering our options:

> Changing the name, even though it should be kept seems wrong, so I don't really consider that an option.

Well, I would argue, that if an editor cares to keep the name, the reason would be entirely focused around the basename and not necessarily the extension. Having a readable name may be important for SEO (full disclaimer: I have no idea, whether this is true), but I'd expect the file extension to be irrelevant here as well.

> [...] another option would be to reject that replacement, if the types don't match.

I would agree that this would be better than to leave the image in a broken state. But considering the way I have seen editors use the replacement feature, it is absolutely plausible they'd want to be able to replace an SVG with a PNG image.

Given that, I'd opt for renaming the extension automatically. (Though I have yet to test, whether that actually solves the issue).

**Review by grebaldi — DISMISSED** [review]
See my comment from above. The replaced files continue to be served with a wrong content-type which leads to issues in some browsers. 

There needs to be a decision whether to prohibit the replacement for non-matching mime-types or whether to change the file extension on-the-fly.

**Comment by kdambekalns** [comment]
Vote here, please: https://discuss.neos.io/t/asset-replacement-filenames-and-mime-type/5558

**Comment by markusguenther** [comment]
How do we continue here? The discussion is still ongoing but has no new posts since a while :)

**Comment by kdambekalns** [comment]
I closed the poll (finally, ahem) and will go the way of "change the file extension if needed", keeping an eye on redirect creation as pointed out by @Sebobo.

**Review by jonnitto — APPROVED** [review]

**Comment by kdambekalns** [comment]
pinging @grebaldi …

**Review by markusguenther — APPROVED** [review]
Thanks, @kdambekalns, for taking care :)

**Pull request merged**
