### PR TITLE
TASK: Prevent AssetInterfaceConverter to run into an exception

### PR DESCRIPTION
**Pull request by gradinarufelix**
**What I did**
Prevent `AssetInterfaceConverter` to run into the exception from issue #2753 
**How I did it**
Escaped the relevant code part with an if-statement. When there is no resource of instance `PersistentResource`, don't call `parent::convertFrom()`
**How to verify it**
See commit.

### CODE REVIEW

**Comment by albe** [comment]
Test fails now, exactly because of the missing `isset` check...

**Comment by gradinarufelix** [comment]
Nevermind, I already fixed that. But my first bugfix crapped up the ThumbnailController and maybe other things as well. My current solution looks like this: when you submit an empty resource, the array `$convertedChildProperties` has an element with key `resource` but it's null. When an async Thumbnail is rendered, this array `$convertedChildProperties` is empty. That's how I fixed it right now and it seems to work. Anyway, it feels like a very dirty hack and we should definitely have a look at it from a larger scope.

**Comment by albe** [comment]
Can you by chance check how the `convertedChildProperties` are filled on 5.x in that case?

**Comment by gradinarufelix** [comment]
> Can you by chance check how the `convertedChildProperties` are filled on 5.x in that case?

I can do that when I am back in Vienna. What about the others? Does this look sensible to you?

**Comment by gradinarufelix** [comment]
I now rebased my branch to 5.0. I hope this was correct.

**Comment by albe** [comment]
Hm, there seem to be some commits inside now, that don't belong here. Looks as if the rebase merged some commits from master into the new base.

**Comment by gradinarufelix** [comment]
Can somebody help me fix that issue with the rebase?

**Comment by davidspiola** [comment]
@gradinarufelix I created a PR for your rebase issue. Pls review it real quick just to make sure all your stuff in the PR, thx

FIX: #2806

**Comment by albe** [comment]
Thanks David, I guess this one can be closed now :)

**Pull request closed without merging**
