### PR TITLE
TASK: Add new login wallpaper

### PR DESCRIPTION
**Pull request by jonnitto**

### CODE REVIEW

**Comment by bwaidelich** [comment]
Great, I love it.
Didn't we use to mention the image author in the login screen?

**Comment by markusguenther** [comment]
Looks so awesome... 
Screenshot 2020-11-30 at 17 35 00

**Review by markusguenther — APPROVED** [review]
Awesome thanks to @jonnitto and @larswittenberg ❤️

**Comment by markusguenther** [comment]
> Didn't we use to mention the image author in the login screen?

Nice idea but we did not before :/

**Comment by markusguenther** [comment]
Don't know if we have defined image sizes, but the new image is bigger than the 5.3 one ;)
Screenshot 2020-11-30 at 17 41 18

**Comment by markusguenther** [comment]
The image was no progressive JPEG:

Screenshot 2020-11-30 at 17 48 02

We now have a smaller image size as before at the same size but with progressive encoder:

Screenshot 2020-11-30 at 17 48 10

**Comment by bwaidelich** [comment]
>> Didn't we use to mention the image author in the login screen?

> Nice idea but we did not before :/

Ah, I must have mixed it up then. It was mentioned in the release articles

> We now have a smaller image size as before at the same size but with progressive encoder

Sweet, thank you!

**Review by kdambekalns — APPROVED** [review]

**Comment by jonnitto** [comment]
I missed an option in the Optimizer: Now it is even bigger in size (pixel-vise) but has more compression. This is better for high-resolution monitors. The file size is now only 357kb

**Comment by markusguenther** [comment]
Awesome and also progressive :)
Screenshot 2020-11-30 at 20 24 18

**Comment by markusguenther** [comment]
🎉

**Pull request merged**
