### PR TITLE
BUGFIX: Dynamic cache segments not correctly re-evaluated

### PR DESCRIPTION
**Pull request by kitsunet**
...
Only a test to expose the wrong behavior at this point.

Fixes: #1958

### CODE REVIEW

**Comment by kitsunet** [comment]
This is only the test exposing the problem for now.

**Comment by kitsunet** [comment]
Ok, I fiddled a bit with a possible solution, but it's not _that_ easy. What you want is that dynamic entries are checked against the cache BUT result again in an evalCached wrapping, which needs the current context, so basically what postProcess does. I have a couple of ideas, but can't wrap my head around it anymore tonight.

**Comment by kitsunet** [comment]
Theoretically this is better than the state before... So it could be merged if nothing more happens here, but for now WIP because working on some follow up things that this uncovered (but that were there before).

**Comment by bwaidelich** [comment]
FYI: Removed WIP label as discussed. Further improvements & refactoring can go into separate PRs

**Comment by hlubek** [comment]
Discussed the problem and possible solution with @bwaidelich and we came to the conclusion to tackle the issue at a larger scale (maybe simplify the cache concept and re-implement the content cache implementation) at the next sprint before the conference.

So far this fix solves the issue and should at least improve things.

**Pull request merged**
