### PR TITLE
TASK: Update to latest Font Awesome

### PR DESCRIPTION
**Pull request by Darmstaedter**
Update to Font Awesome version 4.5.0.

All icons are prefixed with "icon-" and old icon-names from version 3.2.1 are still available for backwards compatibility.

Changing the prefix later on is easy because it's just defined in a variable.

 NEOS-582 #close Updates FA, but keeps the prefix

### CODE REVIEW

**Comment by kdambekalns** [comment]
NEOS-582 is targeted at the 2.x branch…

**Comment by Darmstaedter** [comment]
Shall I create a new pull request on the 2.0 or 2.1 branch?

**Comment by kitsunet** [comment]
Uhm, but still this is a major change, a feature. I would say it needs at least a minor release (which means it's just fine here).

**Comment by kdambekalns** [comment]
I got it mixed up, it's the correct branch here, sorry for the confusion.

**Comment by kdambekalns** [comment]
:+1: - Neos UI works like a charm and the new icons are available as well (tested `icon-mixcloud` and `icon-edge`).

**Comment by dfeyer** [comment]
:+1:

**Comment by reflexxion** [comment]
Why don't implement it via [composer](https://packagist.org/packages/fortawesome/font-awesome)? 

That would provide an [icons.yml](https://github.com/FortAwesome/Font-Awesome/blob/master/src/icons.yml) that folks can use to easily build e.g. an icon data source

**Comment by kitsunet** [comment]
@reflexxion @Darmstaedter if that is easily possible I would love that but IMHO not that important, we can refactor to using this package always later on, I would be more happy to finally get this update in.

:+1: from me

**Comment by Darmstaedter** [comment]
Currently we need to use the "icon-" prefix and some parts of Font Awesome are changed accordingly. 

For the next major version it’s possible to change the prefix to FA default ('fa-') and we could use the original FA-Package without any changes. Implementing it with composer or bower would be great then.

**Pull request merged**
