### PR TITLE
FEATURE: Increasing the contrast in module tables

### PR DESCRIPTION
**Pull request by markusguenther**
**What I did**
Adjusted the SCSS of the backend module table to the suggested values of @creative-resort 
to higher the contrast and make it better readable.

**How to verify it**
Just open the package management in the backend.

Thanks to @creative-resort for the suggestion!

Resolves: #2782

### CODE REVIEW

**Comment by markusguenther** [comment]
Bildschirmfoto 2019-11-27 um 10 44 13
Example how it looks now.

**Comment by jonnitto** [comment]
@markusguenther A screenshot before as reference would also be helpful. 😉

**Comment by jonnitto** [comment]
@albe Do you know why the tests fail? The seems nothing to do with this PR

**Comment by albe** [comment]
The second test failure should be fixed with https://github.com/neos/flow-development-collection/pull/1853, the first is in neos/form and I'll take a quick look

**Comment by markusguenther** [comment]
@Jonnitto in the Ticket was a before screen I guess. But when I am done with LEGO construction and advent stuff I can post one ;)

**Comment by albe** [comment]
I restarted the travis jobs now and hopefully all will be green soon.

**Pull request merged**
