### PR TITLE
!!! TASK: Remove plugin views

### PR DESCRIPTION
**Pull request by nezaniel**
Blocked by https://github.com/neos/neos-ui/issues/3534

This removes the deprecated plugin URI aspect 

- [x] Code follows the PSR-12 coding style
- [x] Tests have been created, run and adjusted as needed
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Review by mhsdesign — DISMISSED** [review]
There was actually much more deprecated than just this aspect ;)

See @mficzel deprecation PR to **Deprecate PluginView's** (as discussed at the Dresden 23 sprint) https://github.com/neos/neos-development-collection/pull/4069

**Review by skurfuerst — COMMENTED** [review]
Does this remove plugin views completely? Or are the other parts (node type etc) already gone?

Fine from my side :) @bwaidelich wdyt?

**Comment by nezaniel** [comment]
> Does this remove plugin views completely? Or are the other parts (node type etc) already gone?

That's the idea but gut point, will have a look

**Comment by nezaniel** [comment]
Thanks for the hints, I just followed @mficzel s deprecation PR and removed stuff :)

Things that I noticed and could be done additionally:

I removed the `Neos.Neos:PluginView` node type as well. It uses some special inspector editors:
* `Neos.Neos/Inspector/Editors/MasterPluginEditor`
* `Neos.Neos/Inspector/Editors/PluginViewEditor`

that are used nowhere else. I think the UI package would be happy to have the editors deleted as well.

In `Neos\Neos\Controller\Backend\ContentController` there are two actions `pluginViewsAction` and `masterPluginsAction` that now return empty results, are now deprecated and could be removed, most probably together with the above editors.
See also:
* Neos.Neos/Routes.Backend.yaml `Content Module - Plugin Views` and `Content Module - Master Plugins`
* Neos.Neos/Policy.yaml 
* Neos.Neos/Resources/Private/Translations/*/NodeTypes/PluginView.xlf, wherever these are generated
* Neos.Neos/Resources/Private/Fusion/Root.fusion

**Comment by mhsdesign** [comment]
Sorry i dont feel save to review this one ^^ I have basically 0.5% knowledge about the concepts. (But i do want them to go away ^^)

I remember from a discussion at the sprint that we only want to remove plugin views and not plugins in general but i dont remember the difference 😂 

edit: bernhard explained to me ^^ and i will take care of cleaning up the ui see https://github.com/neos/neos-ui/issues/3534

**Comment by nezaniel** [comment]
This part can actually already be merged, the adjustments listed above can be done after the UI changes

**Review by bwaidelich — APPROVED** [review]
I dare to add my +1 by reading. Thanks for taking care!

**Review by skurfuerst — APPROVED** [review]

**Pull request merged**
