### PR TITLE
BUGFIX: Fix wrong Flow version in ``composer.json``

### PR DESCRIPTION
**Pull request by gerhard-boden**
This will fix the dependency for the Flow version to correct one and prevent `composer update` to upgrade to unwanted minor releases.

### CODE REVIEW

**Comment by johannessteu** [comment]
Doesn't this has to be fixed also in a different way @kdambekalns ?

**Comment by kitsunet** [comment]
Nah, I think this was really a typo and should never have been like this.

**Comment by johannessteu** [comment]
Ah ok, thought that this would also be some kind of auto generated and other scripts would need some adjustements

**Comment by aertmann** [comment]
related to this, the `2.3` version is pretty broken.. https://github.com/neos/neos-development-collection/blob/2.3/TYPO3.Neos/composer.json vs https://github.com/neos/neos-development-collection/blob/2.2/TYPO3.Neos/composer.json

**Comment by johannessteu** [comment]
@aertmann https://github.com/neos/neos-development-collection/pull/705

**Pull request merged**
