### PR TITLE
BUGFIX: Support empty dimension values for default fallbacks

### PR DESCRIPTION
**Pull request by hlubek**
Implement support for empty dimension values (for any number of
dimensions) of a node variant. This allows to have nodes like ``/sites``
that will always be found, independent from the dimensions of the
context.

Another case is the transition to new dimensions that will be much
easier because existing nodes are already visible.

NEOS-1633 #close

### CODE REVIEW

**Comment by kitsunet** [comment]
Looks quite good already

**Comment by kdambekalns** [comment]
@kitsunet _Quite_ good? So what is missing to simply _good_?

**Comment by kitsunet** [comment]
I don't know, it has a WIP flag... Performance check would be good I guess.

**Comment by kdambekalns** [comment]
Ah, true - what about the WIP label, @hlubek?

**Comment by hlubek** [comment]
Well, that's why it has a WIP label. So if someone can do some performance tests with larger data sets and roughly compare the performance before and after that would help to see if we introduce a regression here.

**Comment by kitsunet** [comment]
I currently compare master to https://github.com/kitsunet/neos-development-collection/commit/8e7a2062c8896c24fd3ddb7896a27d6af105b393

I can check this in there as well...

**Comment by kitsunet** [comment]
My change could easily support this feature here as well, I ust didn't add it yet.

**Comment by kdambekalns** [comment]
Ah, so you wanted the "Needs feedback" label… :)

**Comment by skurfuerst** [comment]
@kitsunet so is this change good to go performance-wise or not? :)

**Comment by kitsunet** [comment]
Didn't come around checking yet and thought it was a bit late for 2.1 anyway so didn't see any reason to prioritize this. Will try ASAP and give more feedback.

**Comment by skurfuerst** [comment]
OK, fine, so no need to hurry when we won't include it in 2.1 :)

**Comment by kdambekalns** [comment]
Ping…

**Comment by hlubek** [comment]
...Pong

Question is if we accept the performance penalty of the nested query (which is of the worst kind by referencing each selected row from the outer query) to fix this.

@kitsunet So what about your change of doing the reduction directly in the database? Do you think this behavior could be implemented with it? This is the better direction to me since the current state of querying too many nodes and reducing in PHP was always a workaround.

**Comment by kitsunet** [comment]
Can defininitely be implemented, I think it even is already!

**Comment by kdambekalns** [comment]
Bi-weekly ping… :)

**Comment by robertlemke** [comment]
For me this change works, the tests succeed and it could be merged into current master. I didn't test the performance yet though.

@kitsunet did you have a chance to check the performance? Or any further plans for this?

**Comment by kdambekalns** [comment]
So, two questions:

- Is the performance impact so bad it blocks the bugfix?
- And should this go into master or 2.2 or even 2.1? It is a bugfix, and the original discussion is from fall of 2015, after all.

**Comment by kitsunet** [comment]
Nah, performance is ok

**Comment by kdambekalns** [comment]
So, @robertlemke created a test and will add this, depending on that we decide where to include it.

**Comment by robertlemke** [comment]
Okay, I pushed the other test. For me this looks good now, it at least fixes a nasty bug we currently have in release and unreleased versions. I am sure that there are more fixes needed, but they can be provided as separate PRs.

**Comment by kdambekalns** [comment]
I'll apply this to 2.2 and run all tests again.

**Comment by kdambekalns** [comment]
Just created https://github.com/neos/neos-development-collection/pull/498 against 2.2

**Pull request closed without merging**
