### PR TITLE
FEATURE: Fusion sourceMap

### LINKED ISSUE #784: Show Fusion source location and line number in error messages
Jira issue originally created by user @robertlemke:

In Development context (not necessary in production really!) it would be very, very helpful if error messages caused by TypoScript parsing / objects would contain the path and filename and the line number of the source code where the respective object was defined / error was caused.

Edit: Parsetime exceptions were improved, now its up to runtime exceptions

### LINKED ISSUE #2792: Fusion sourceMap
Introduce fusion source maps to display the file and line of the failing fusion line.

Add the information about the line in the file where the fusion-ast fragment was actually defined to any fusion error message. Other usecases might be possible aswell but this is the primary one.

Probably there should be a setting and this should at least only be done in Development context.

### PR DESCRIPTION
**Pull request by mficzel**
Introduce fusion source maps to display the file and line of the failing fusion line.

Resolves: #2792
Resolves: #784

### CODE REVIEW

**Comment by bwaidelich** [comment]
I really like that one, _too_, but I'm missing some context on how that is meant to be used :)

**Comment by mficzel** [comment]
@bwaidelich currently it adds the information about the line in the file where the fusion-ast fragment was actually defined to any fusion error message. Other usecases might be possible aswell but this is the primary one.

Probably there should be a setting and this should at least only be done in Development context.

**Comment by bwaidelich** [comment]
@mficzel Thanks again for the clarification! I took the freedom to create a ticket for this feature: #2792

**Comment by albe** [comment]
What's needed to get this finished? :)

**Comment by mficzel** [comment]
@albe What is needed is some discussion how useful this actually is. The current prototype only writes the actual line in the fusion file when an exception is thrown. I think this is too little to justify the extension of the fusion ast.

So the discussion should be: Since we can store the origin of each part of the ast. Can we do more useful stuff with this? Otherwise we should drop this.

**Comment by albe** [comment]
Thinking out loud:
- make it possible to step Fusion code in debug tools?
- catch runtime errors and print exactly which line of code caused it?
- better debugging capablities in the fusion fiddle?

**Comment by mhsdesign** [comment]
Due to the parser rewrite this PR would need to get updated. - I would step in here ;)

The parse time exceptions are currently great (they show line number and everything) - but there is a lot to improve for runtime errors - and for analyzing why a certain path was overriden and where.

I think the question is how much data we want to attach to the new ast nodes (which are cached in dev mode) and later to the completely merged object tree - or if a small string / dto for file and line is negligible. (performance matters also in dev mode ^^)

**Comment by mficzel** [comment]
Would be great to continue here. I think as long as we avoid expanding the ast in production too much it should be fine.

**Comment by mhsdesign** [comment]
ill close this as we have to redo it completely - if we still want it ^^

**Pull request closed without merging**
