### PR TITLE
BUGFIX: Show changes in ContentCollection-Nodes in review-module

### PR DESCRIPTION
**Pull request by mficzel**
This change adds the visualization of changes on ``TYPO3.Neos:ContentCollection`` nodes that also have the type ``TYPO3.Neos:Content`` to the review module. 

Previously those changes were filtered out which prevented the visualization of changes and lead to the page beeing visualized as having changes without showing them in the review module.

### CODE REVIEW

**Comment by aertmann** [comment]
this is not a bug per say, they aren't shown as most of the time those changes are pretty useless to the user and thus clutters a lot when changing creating/something.. however since it's now possible to use content collections as elements themselves, it could be definitely considered a task as the workspace hasn't been adjusted to that change..

now this solution isn't quite desirable IMO, instead I'd suggest to only show content collections when they're not auto-created or they actually have property changes and not just when they're created/deleted/moved which is when they were pretty useless..

also it probably makes sense to take the sorting order of children into account when showing content collections, I'm not entirely sure that's not already the case, but my guess is it's not..

**Comment by mficzel** [comment]
@aertmann i fear the condition would become quite complex and harder to understand. We should try to find a simpler filter logic for the review module. 

I agree that we could safely hide "TYPO3.Neos:ContentCollection" as autocreated child nodes on create but not subtypes. 

The point i found this issue was when an editor mentioned that the number of changes in the Publish-Button was not equal to the number of changes visible in the review module. Even worse if only a Content that had SuperType Collection was changed the review module showed no changes and did'nt allow to publish the changes of the document (the publish button still did).

Maybe we should improve the visualisation of ContentCollection changes in the review module instead of filtering them out.

**Comment by aertmann** [comment]
@mficzel: potentially, I'd suggest to try it out and make a ton of changes with various elements extending/containing content collections and see what works.

Yep know of the issue you mention, and I think the most important is to never be able to open the changes overview and not see anything if it says there are

**Comment by mficzel** [comment]
@aertmann what would be the correct target branch for that? Still 2.1?

**Comment by aertmann** [comment]
@mficzel yep, until 3.0 comes out.. see https://www.neos.io/features/release-roadmap.html

**Comment by mficzel** [comment]
@aertmann i changed the logic slightly to skip collection nodes if no renderable changes are found.

**Comment by mficzel** [comment]
The Logic was changed once again. Now the skipping of collection changes only occurs if the ``TYPO3.Neos:ContentCollection`` is not of type ``TYPO3.Neos:Content``

**Pull request merged**
