### PR TITLE
TASK: Replace in-memory node sorting during export by DB sort

### PR DESCRIPTION
**Pull request by kdambekalns**
This adds a custom replace DQL function to remove the in-memory sorting
of nodes by path during site export that was implemented to fix NEOS-829.

### CODE REVIEW

**Comment by kdambekalns** [comment]
Also @dimaip and @kitsunet might be appropriate reviewers, I think.

**Comment by kdambekalns** [comment]
Does someone have a clue why the test fails? It works on my machine… Doh!?

**Comment by bwaidelich** [comment]
> Does someone have a clue why the test fails?

@kdambekalns That's weird. especially I don't see the difference between
```
       </variant>
-      <node identifier="98892e3b-eee2-49fb-821f-aa41ee53eaa3" nodeName="child">
-       <variant sortingIndex="100" workspace="live" nodeType="TYPO3.Neos.NodeTypes:Page" version="1" removed="" hidden="" hiddenInIndex="">
-        <dimensions>
-         <language>en_US</language>
-        </dimensions>
-        <accessRoles __type="array"/>
-        <creationDateTime __type="object" __classname="DateTime">2016-08-26T17:00:00+02:00</creationDateTime>
-        <lastModificationDateTime __type="object" __classname="DateTime">2016-08-26T17:00:00+02:00</lastModificationDateTime>
-        <properties>
-         <title __type="string">Child of Node</title>
-         <uriPathSegment __type="string">child</uriPathSegment>
-        </properties>
-       </variant>
-      </node>
```
and
```
     </node>
+   </node>
+   <node identifier="98892e3b-eee2-49fb-821f-aa41ee53eaa3" nodeName="child">
+    <variant sortingIndex="100" workspace="live" nodeType="TYPO3.Neos.NodeTypes:Page" version="1" removed="" hidden="" hiddenInIndex="">
+     <dimensions>
+      <language>en_US</language>
+     </dimensions>
+     <accessRoles __type="array"/>
+     <creationDateTime __type="object" __classname="DateTime">2016-08-26T17:00:00+02:00</creationDateTime>
+     <lastModificationDateTime __type="object" __classname="DateTime">2016-08-26T17:00:00+02:00</lastModificationDateTime>
+     <properties>
+      <title __type="string">Child of Node</title>
+      <uriPathSegment __type="string">child</uriPathSegment>
+     </properties>
+    </variant>
    </node>
   </nodes>
  </site>
 </root>
```
!?

I assume it's some whitespacing issue and that _might_ be related to the XML library/settings.. But then again, it doesn't make sense that this is related to the used DB backend

**Comment by kdambekalns** [comment]
Well, once the `<node>` follows a `<variant>` and once a `<node>`. So there is a difference and I think it's indeed showing some error…

**Comment by bwaidelich** [comment]
ah, ofc.. strange

**Comment by kitsunet** [comment]
Apart from the conflicts, what is the state here? Would you follow up on these test errors and rebase @kdambekalns ? :)

**Comment by jonnitto** [comment]
Ping @kdambekalns

**Pull request closed without merging**
