### PR TITLE
WIP: Fusion Tests inside of Fusion

### LINKED ISSUE #3594: Write better Fusion tests (with behat)
It would be great if tests for the fusion language could be written in fusion directly.

### PR DESCRIPTION
**Pull request by mhsdesign**
I was inspired by this comment: https://github.com/neos/neos-development-collection/pull/2729#issuecomment-561039907 
and started this WIP idea...

Currently all functional fusion tests still need to be registered manually in the corresponding php test class and also the expected results are located on the php site. This PR attempts to put this closer to fusion ... in fusion.

The idea is we leverage php units dataprovider and parse the fusion beforehand then look for all paths on the first level who end with 'Test' and yield a configuration (which is generated only from the ast - not at runtime)

run the tests via the usual:
```
./bin/phpunit -c ./Build/BuildEssentials/PhpUnit/FunctionalTests.xml ./Packages/Neos/Neos.Fusion/Tests/Functional/WithinFusionTests/FusionFixturesTest.php
```

### test generation in more detail:
get all first level paths which end with 'Tests' or which are a Neos.Fusion.Testing:TestCase
it can have multiple test and fusion data providers - which will be in mixed combinations evaluated.

return values of @beforeRender and @afterRender are ignored, their purpose is to call methods on the context objects:
- self - the instance of this testcase
- view - the instance of the used view
- result - return value of the provider accessible in @afterRender
```
what_im_testing_here_test {
  @test.1 {
    @beforeRender = ${ view.assign('foo', 123) && self.expectException('Foo\Class') }
  }
  @test.2 {
    @beforeRender = ${ view.assign('foo', 'hi') }
    @afterRender = ${ self.assertSame(actual, 'hi') }
  }

  @fusion.1 = Foo:BarWhichTrowsWhenAnIntGivenElseReturns {
    foo = ${ foo }
  }
}
```

### php unit dataproviders
using dataproviders has the advantage, that each fusion test is treated separately from another fusion tests, and so if one test fails - not everything breaks.

Also filtering with --filter works:
```
./bin/phpunit -c ./Build/BuildEssentials/PhpUnit/FunctionalTests.xml ./Packages/Neos/Neos.Fusion/Tests/Functional/WithinFusionTests/FusionFixturesTest.php --filter "apply"
```

exception messages when one test fails are also fairly readable:
`...FusionTestsFusion\FusionTestsFusionTest::assertFusionRendersAsExpected with data set "dataStructureTest.nestingWithNonExistingChildObject with: scenario[1] provider[1]"`

### how to write the new tests?
i put some working examples in the `Fixtures/Fusion/FusionTestsFusion/` dir.
you can run those from the flow root with:
```
./bin/phpunit -c ./Build/BuildEssentials/PhpUnit/FunctionalTests.xml ./Packages/Neos/Neos.Fusion/Tests/Functional/FusionObjects/FusionTestsFusion
```

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)

... what do you say?
i did create two new folders and so as this is WIP and just a demo ^^

see #3594

### CODE REVIEW

**Comment by mhsdesign** [comment]
Extracted the testcase into own Package `Neos.Fusion:Testing` as you suggested @mficzel

**Comment by mficzel** [comment]
@mhsdesign sorry for sidetracking this with the idea to separate the testing into an extra package. Just noticed how much changes would be needed with almost non existing gain in https://github.com/neos/flow-development-collection/pull/2683. 

I am sorry for causing extra work and agree that the base testcase should be in tests in the neos/fusion package.

**Comment by mhsdesign** [comment]
Sure we can keep it in Neos.Fusion ;)
## how can we proceed?
But before i move this again i would like to know how we can proceed. Maybe we can roll this out with 8.0 - we dont have to rewrite all tests but id like that we then have agreed on a syntax and implementation.

in terms of syntax and implementation id like to abstact as less as possible (eg. make the testCase accessible in eel)

i also 


btw this is the slack thread

**Comment by mhsdesign** [comment]
arent we basically trying to build our own behat? - why not use it directly ^^

**Comment by kitsunet** [comment]
> arent we basically trying to build our own behat? - why not use it directly ^^

Sounds a bit like it, I agree...

**Comment by mficzel** [comment]
Would be fine with that aswell

**Comment by mhsdesign** [comment]
but behat files wont give us fancy syntax highlighting ...

**Comment by mhsdesign** [comment]
Looks better so far than my totally in fusion approach:

```feature
Feature: Fusion
  As a developer i want to write Fusion because Fusion is cool

  Scenario: Simple value
    Given I have this Fusion
      """
      include: resource://Neos.Fusion/Private/Fusion/Root.fusion
      root = Neos.Fusion:Value {
        value = "abc"
      }
      """
    Then I expect to have the following result for path "root"
      """
      abc
      """

  Scenario: Simple array
    Given I have this Fusion
      """
      include: resource://Neos.Fusion/Private/Fusion/Root.fusion
      root = Neos.Fusion:DataStructure {
        foo = "bar"
      }
      """
    Then I expect to have the following json array for path "root"
      """
      {
        "foo": "bar"
      }
      """

```

**Comment by mficzel** [comment]
I agree,  that looks really nice and is really easy to understand.

**Comment by mhsdesign** [comment]
i will close this pr, and make a new WIP one based on behat.

(just too keep the original idea and code seperately)

**Pull request closed without merging**
