### PR TITLE
Add missing prefixes to database table indexes

### PR DESCRIPTION
**Pull request by nezaniel**

### CODE REVIEW

**Comment by mhsdesign** [comment]
i think this might got lost @nezaniel ?

**Comment by bwaidelich** [comment]
An alternative would be to not give an explicit name to these indexes, then PG will create unique ones

**Comment by bwaidelich** [comment]
@nezaniel can't we just omit the names?

**Comment by nezaniel** [comment]
Probably yes, we just can't leave it as it is when we have multiple CRs, can we? @kitsunet

**Comment by bwaidelich** [comment]
Ah right, I had already fixed this with e13e4d65ae786b6180645fb4f7cbf817f9f88250 – I think we can close this one

**Comment by nezaniel** [comment]
Okay :)

**Pull request closed without merging**
