### PR TITLE
BUGFIX: Convert DateTimeImmutable "Now" into DateTime for account deactivation

### LINKED ISSUE #2131: Argument 1 passed to Neos\Flow\Security\Account_Original::setExpirationDate() must be an instance of DateTime or null, instance of Neos\Flow\Utility\Now given
### Description

When using the function deactivateUser from UserService 
(See: https://github.com/neos/neos/blob/master/Classes/Domain/Service/UserService.php#L567 )
I get the following Exception:

Argument 1 passed to Neos\Flow\Security\Account_Original::setExpirationDate() must be an instance of DateTime or null, instance of Neos\Flow\Utility\Now given

### Affected Versions

neos/neos                        4.0.7
neos/neos                        4.0.6
maybe more

### PR DESCRIPTION
**Pull request by dlubitz**
Convert "Now" based on DateTimeImmutable to DateTime, as Account::setExpirationDate expects it.

Fixes #2131

### CODE REVIEW

**Comment by bwaidelich** [comment]
Thanks for this.
I'm just wondering: Wouldn't it be better to change the signature of `Account::setExpirationDate()` so that it supports `DateTimeInterface`s?

**Comment by dlubitz** [comment]
Sure, but I didn't want to change the "contract". IDK if this might be a breaking change than.

**Comment by dlubitz** [comment]
Actually it should be fine, as \DateTime implements \DateTimeInterface

**Comment by dlubitz** [comment]
Hmm, if I think about it a bit longer, it will break because we have to replace also the getter and the return types. If someone relies on \DateTime it could break that.

So what about using this PR for current branches, and a new one with changed contract for master? @bwaidelich

**Comment by dlubitz** [comment]
Nehhhh, 
`DateTime::createFromImmutable` is PHP 7.3 :/
https://www.php.net/manual/de/datetime.createfromimmutable.php

**Comment by dlubitz** [comment]
Fixed with a less smart solution.

**Pull request merged**
