### PR TITLE
BUGFIX: Only show button to create a workspace if user is allowed to do so

### PR DESCRIPTION
**Pull request by ComiR**

### CODE REVIEW

**Comment by aertmann** [comment]
hmm deja vu? didn't we have this change already?

**Comment by kitsunet** [comment]
the other was never reopened for this branch, so...

**Comment by ComiR** [comment]
I should have seen #676...

**Comment by kitsunet** [comment]
oh, so it was rebased, lol... OK yes

**Comment by kitsunet** [comment]
Closing in favor of #676 
Thanks!

**Pull request closed without merging**
