### PR TITLE
BUGFIX: Add workspace hash to NodeDynamicTag_ and AssetDynamicTag_ cache tags

### LINKED ISSUE #4781: BUG: "DynamicTag_" cache tags contain workspace hash for flushing but not for caching
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The "AssetDynamicTag_" cache tag gets created by the `ConvertUrisImplementation` and tags all Fusion cache segments that contain any `asset://` references to an asset. The tag doesn't contain any workspace hash.

On any change to the asset, the content cache flusher registers the asset change and calculates the tags to flush. But it includes a workspace hash of the node where the asset is used.

https://github.com/neos/neos-development-collection/blob/589ca09809523ba48aad10d3f2337103d1beb59b/Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php#L104-L104

https://github.com/neos/neos-development-collection/blob/589ca09809523ba48aad10d3f2337103d1beb59b/Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php#L295-L295

The same issue exists for linked nodes. Also here the created "NodeDynamicTag_" cache tag doesn't contain any workspace hash. But the ContentCacheFlusher, removes tags with AND without workspace hash.

https://github.com/neos/neos-development-collection/blob/589ca09809523ba48aad10d3f2337103d1beb59b/Neos.Neos/Classes/Fusion/ConvertUrisImplementation.php#L100

https://github.com/neos/neos-development-collection/blob/589ca09809523ba48aad10d3f2337103d1beb59b/Neos.Neos/Classes/Fusion/Cache/ContentCacheFlusher.php#L156-L161

Because of this inconsistency, the `AssetDynamicTag` gets never flushed and the `NodeDynamicTag` gets always flushed without the workspace information.

### Expected Behavior

Cache tags for flushing should meet the cache tags created on caching.

### Steps To Reproduce

* Create a Text-NodeType-Property and link an asset.
* Add text and link it to an asset
* Open the page in live context
* Change some meta data of the asset
* Check dev logs for "Content cache"

### Environment

```markdown
- Flow: 7.3
- Neos: 7.3
- PHP: 8.1
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dlubitz**
Fixes #4781

### CODE REVIEW

**Comment by kitsunet** [comment]
Wait I thought we agreed to adjust the flusher to flush without workspace for assets, I'd argue that also makes more sense, for nodes only the workspaces that can possible be affected are important to be flushed, but for assets should the asset change it changed globally, therefore any workspace containaing the asset should be flushed.

**Comment by dlubitz** [comment]
I thought the same, but actually this works very well as we use the "AssetUsage" here. So we know the nodes (and workspaces) where the asset is referenced. We don't flush the cache of assets, we flush the cache of nodes referencing an asset.

**Comment by kitsunet** [comment]
Right I see it now, thanks for the clarification, still a weird hoop to jump through if we could just flush by asset id and be done.

**Comment by dlubitz** [comment]
I'm fine with both... Just thought at the point where I realized, that it works with workspaces, to go the initial intended way.

**Comment by dlubitz** [comment]
Also it's consistent for NodeDynamicTag and AssetDynamicTag.

**Comment by kitsunet** [comment]
No worries, just thinking about why it is as it is, the change makes sense obviously!

I also found why it's not quite that easy, we create dynamic tags (that seem almost useless?) for linked assets in rich text, but there are no tags for assets used as part of the node properties and rendered in some way in content. We basically have a split brain situation here were part of the flushing works via usage reference flushing the node tag itself and part uses the dynamic tag.

**Review by kitsunet — APPROVED** [review]
I think we should take a closer look at this whole model for 9.0 BUT this fix should be good for now.

**Comment by dlubitz** [comment]
It's on my list to create 9.0 issues for that anyways.

**Review by mhsdesign — APPROVED** [review]

**Pull request merged**
