### PR TITLE
[BUGFIX] Reset date picker to current date instead of null

### PR DESCRIPTION
**Pull request by kdambekalns**
Fixes: NEOS-1351

### CODE REVIEW

**Comment by hlubek** [comment]
:+1: by reading

**Comment by aertmann** [comment]
:+1: manual testing & reading

should be pushed to 1.2 instead of 2.0 though..

**Comment by kdambekalns** [comment]
We could do that for 1.2 as well, but let me point out that the reset doesn't work as I'd like to see it. After resetting, the date picker is in the "minutes view" instead of the "startView" mode, and I didn't manage to fix that…

**Comment by aertmann** [comment]
You can do that with `this.$('.neos-editor-datetimepicker').datetimepicker('showMode', 2);`

**Comment by kdambekalns** [comment]
Replaced by https://github.com/neos/neos-development-collection/pull/66

**Pull request closed without merging**
