### PR TITLE
TASK: Replace "TYPO3 Neos" by "Neos"

### PR DESCRIPTION
**Pull request by tbrodard**
The hint about enabling the event logging is probably not at the right place, but I don't know where to put it elsewhere ...

### CODE REVIEW

**Comment by kdambekalns** [comment]
:+1:

**Comment by kitsunet** [comment]
:+1: Might even go into 2.0 and 2.1, WDYT @kdambekalns ?

**Comment by kdambekalns** [comment]
Sure, why not!

**Comment by kitsunet** [comment]
@tbrodard would you retarget the PR to 2.0? Much appreciated :)

**Comment by tbrodard** [comment]
@kitsunet Mmh, OK, but how can I do that ? Via the Github interface ?

**Comment by kitsunet** [comment]
unfortunately not. @tbrodard you need to cherry pick the change into a 2.0 install, push and then open a PR to this repositories 2.0 branch. Then just close this one and point to the new.

**Comment by kitsunet** [comment]
@tbrodard Need help with the retarget?

**Comment by kdambekalns** [comment]
Replaced by PRs to 2.0 branch.

**Pull request closed without merging**
