### PR TITLE
BUGFIX: RemoveNodePrivilege blocks editing

### LINKED ISSUE #896: RemoveNodePrivilege blocks editing
Jira issue originally created by user @kdambekalns:

Due to the way the privilege is implemented, it blocks editing nodes via the inspector, since that will try to call `setRemoved(false)`.

 Jira-URL: https://jira.neos.io/browse/NEOS-1720

### PR DESCRIPTION
**Pull request by kdambekalns**
The RemoveNodePrivilege would block editing of nodes completely, since
the inspector would send all properties of a node, but the setter for
"removed" was blocked by the privilege.

Now the privilege only matches on setRemoved(true) and thus only blocks
what it should block.

Fixes #896

### CODE REVIEW

**Comment by kdambekalns** [comment]
See https://jira.neos.io/browse/NEOS-1720 for a discussion on guarding the `remove()` method…

**Comment by kitsunet** [comment]
So.... should we merge this or find an expression guarding both?

**Comment by kdambekalns** [comment]
Guard both is the way to go, I fear.

**Comment by kdambekalns** [comment]
Maybe @bwaidelich and @foerthner could chime in (again) on this topic…

**Comment by kdambekalns** [comment]
Ok, I will merge this as soon as Travis turns green…

**Pull request merged**
