### PR TITLE
TASK: Make classes readonly where it makes sense

### PR DESCRIPTION
**Pull request by nezaniel**
**Upgrade instructions**

none

**Review instructions**

only final classes (and one or two that were made final) should have been refactored

**Checklist**

- [X] Code follows the PSR-12 coding style
- [X] Tests have been created, run and adjusted as needed
- [X] The PR is created against the 9.0 branch
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Review by bwaidelich — APPROVED** [review]
Nice! +1 by reading

**Review by mhsdesign — APPROVED** [review]
Thanks looks good by reading;)

**Comment by Benjamin-K** [comment]
Shouldn't we add PHP 8.2 as requirement then (if not already set)?

**Comment by nezaniel** [comment]
> Shouldn't we add PHP 8.2 as requirement then (if not already set)?

PHP 8.2 is already required

**Pull request merged**
