### PR TITLE
!!! TASK: Remove ember-js based content module

### PR DESCRIPTION
**Pull request by markusguenther**
Removes old emberjs ContentModule Code and replaces the top navigation bar with plain ES6.
For the new Codebase we use Webpack as toolchain.

### CODE REVIEW

**Comment by markusguenther** [comment]
Note merge yet ... I am just polishing it

**Comment by markusguenther** [comment]
TestNoEmberContentModule

Created a little gif yesterday.

**Comment by kdambekalns** [comment]
Aside from those two things: I love the amount of deletions! :)

**Comment by daniellienert** [comment]
Travis fails as composer hits the memory limit on update.

**Comment by daniellienert** [comment]
Cleared caches. Let's see if it helps.

**Comment by markusguenther** [comment]
The fontawesome thing should be because the private files are not used directly and go thru webpack.

But need to check that when I have a Mac on my side. (Written from phone)

**Comment by kdambekalns** [comment]
> Cleared caches. Let's see if it helps.

No, on master I actually changed .travis.yml to include `COMPOSER_MEMORY_LIMIT=-1 composer …`

**Comment by kdambekalns** [comment]
Ok, re-removed the re-added documentation files and merged master (to fix composer on Travis CI.)

**Pull request merged**
