### PR TITLE
BUGFIX: Improve slow aloha settings selector

### PR DESCRIPTION
**Pull request by dimaip**
Current selector to match property editor of given node type is
extremely slow due to high complexity.

Add additional `data-neos-node-type` attribute to editable property wrap
to simplify the selector.

This brings a huge performance improvement on pages with a lot of
editable properties.

### CODE REVIEW

**Comment by dimaip** [comment]
@kdambekalns why has the test been failing then?

**Comment by robertlemke** [comment]
@dimaip because the unit test only mocks part of the objects needed for the new situation.

Simply add this to the `setUp()` method in the unit test case:

```
        $this->mockNode->expects($this->any())->method('getNodeType')->will($this->returnValue(new NodeType('Acme.Test:Headline', [], [])));
```

Apart from the failing test: :+1:

**Comment by dfeyer** [comment]
:+1: Nice catch

**Comment by dimaip** [comment]
@robertlemke thanks for enlightening me :)
Fixed :+1:

**Comment by dimaip** [comment]
Opened this PR against wrong branch. See #255

**Pull request closed without merging**
