### PR TITLE
TASK: Global unpublished changed publish button state

### PR DESCRIPTION
**Pull request by aertmann**
Adds a different state for the publish button when there are
unpublished changes, but not on the current page.

### CODE REVIEW

**Comment by aertmann** [comment]
image

**Comment by johannessteu** [comment]
👍

**Comment by gerhard-boden** [comment]
:+1: works but I like the current version better. Would that be a reason for a downvote? :smile: Are we going for testing functionality or do we bring in personal preferences?

**Comment by aertmann** [comment]
@gerhard-boden: sure that's a valid reason for a downvote.

it's not really about how it looks but helping users understand there still are unpublished changes, which the current version doesn't get across

**Comment by gerhard-boden** [comment]
I see, but not sure if the new version is more informative than the old one. The green/orange mixture is just hurting my eyes a bit ;). Maybe make use of the new labels and bring up an informative text when hovering the inactive publish button? Not sure.. that's a tricky UX problem!

**Comment by mgoldbeck** [comment]
Personally I like the idea and I would even take an higher alpha value than 0.5 to make it even better visual. Would propose 0.7

**Comment by kdambekalns** [comment]
> helping users understand there still are unpublished changes, which the current version doesn't get across

… but that is what the orange "dropdown" signals!?

**Comment by gerhard-boden** [comment]
But the orange dropdown alone does not really transport that information very well. I think personally thinkt that the greyed out or stripey button does not really help either. Maybe some sort of subtile text field that blends in and out somewhere telling the user that there are "xx unpublished changes" in the workspace?

**Comment by kitsunet** [comment]
What is the state here?

**Comment by dfeyer** [comment]
I don't like the current situation, but the PR does not make the situation more clear ... 👎 for me

**Comment by robertlemke** [comment]
Agree with @dfeyer (I don't like the current situation, but the PR does not make the situation more clear). For me the orange stripes on green impose that something is broken (hazard stripes).

image

**Comment by kdambekalns** [comment]
Closing this for now…

**Pull request closed without merging**
