### PR TITLE
Absolute uri generation

### PR DESCRIPTION
**Pull request by nezaniel**
Previously the LinkingService took care of enforcing absolute URIs if requested or necessary.
Now that Flow routing components can already provide absolute URIs, the LinkingService should no longer always have the final say in this.

The LinkingService now simply only post processes relative URIs.

- [x] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [x] The PR is created against 3.3, which is the first version to be able to make use of this

### CODE REVIEW

**Comment by bwaidelich** [comment]
IMO the `LinkingService` should no longer alter the `UriBuilder` result at all any more and all that logic should be moved to the `FrontendRoutePartHandler` (i.e. _enforced_ from there, not necessarily implemented there directly)

**Comment by nezaniel** [comment]
Good point. Every bit of logic moved out of there in a sensible way is very fine with me

**Comment by nezaniel** [comment]
I'll adjust this accordingly and update the PR, then we can decide whether this can got into a minor release

**Comment by bwaidelich** [comment]
@nezaniel _ping_ any news on this one?

**Comment by bwaidelich** [comment]
@nezaniel *ping*² :)

**Comment by bwaidelich** [comment]
@nezaniel ping³

**Comment by bwaidelich** [comment]
FYI: I just talked to @nezaniel and he is busy and can't log in to github at the moment

**Comment by nezaniel** [comment]
Just a small update: Since I'll try getting the DimensionResolver merged to the core for 4.3 I'll continue and hopefully complete this section here soonish

**Pull request closed without merging**
