### PR TITLE
FEATURE: Inspector group icon

### PR DESCRIPTION
**Pull request by aertmann**
Add icons to inspector groups using a new ``icon`` attribute.

Also includes various improvements related to icons.

NEOS-1406 #close

### CODE REVIEW

**Comment by aertmann** [comment]
https://github.com/neos/neos-googleanalytics/pull/1
https://github.com/neos/neos-seo/pull/8
https://github.com/neos/neosdemotypo3org/pull/9

**Comment by aertmann** [comment]
image
image
image
image
image
image
image

**Comment by johannessteu** [comment]
👍

**Comment by dfeyer** [comment]
Nice one, :+1: by reading, on thing I found annoying with Inspector group, if the fact that use need to click on the right button to close/open, feel more natural to be able to click any where in the group name. But can be done in a separate PR.

**Comment by aertmann** [comment]
trivial rebase

thanks for the reviews! 💯

**Pull request merged**
