### PR TITLE
[TASK] Ignore built JavaScript/CSS to avoid merge conflicts

### PR DESCRIPTION
**Pull request by aertmann**
To avoid merge conflicts, the minified built files are ignored in Git and
instead added using force by the automated jobs in Jenkins.

### CODE REVIEW

**Comment by aertmann** [comment]
:+1:

**Comment by kitsunet** [comment]
But this commit actually removes the files. Shouldn't they still be in?

**Comment by aertmann** [comment]
That's necessary for Git to acknowledge the files are ignored. They will be added automatically by the job afterwards.

**Comment by kitsunet** [comment]
ok, fine for me then :)

**Pull request merged**
