### PR TITLE
FEATURE: Improve site:list command

### PR DESCRIPTION
**Pull request by crydotsnake**
**Upgrade instructions**

_None_

**Review instructions**

Improves our `./flow site:list` command by render the list of all available sites directly in a table.

WindowsTerminal_2VE3pBUkYq

**Checklist**

- [x] Code follows the PSR-2 coding style
- [x] Tests have been ~created~, **run** and ~adjusted~ as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [x] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Review by kitsunet — APPROVED** [review]
I like it a lot, wonder if someone uses the command output for automation and it would break for them, but I'd say it's fine...

**Review by kdambekalns — APPROVED** [review]
by 👀

**Review by Sebobo — APPROVED** [review]
Much better, thx

**Comment by mhsdesign** [comment]
Noice thanks a lot @crydotsnake you can read my mind!!!

**Pull request merged**
