### PR TITLE
TASK: Behat-based Fusion tests (v1)

### PR DESCRIPTION
**Pull request by bwaidelich**
Related: #3594

### CODE REVIEW

**Comment by bwaidelich** [comment]
Forward-ported from #4641

**Review by mficzel — APPROVED** [review]
Fine by 👀

**Comment by mhsdesign** [comment]
Okay the 8.3 part is merged. https://github.com/neos/neos-development-collection/pull/4641

To ease the review here and also prevent ugly merge conflicts during upmerge, id like to upmerge 8.3 first into 9.0 and then update this branch ... okay?

**Comment by bwaidelich** [comment]
Thx! Yes, good idea!

**Review by mhsdesign — APPROVED** [review]
Looks good

**Pull request merged**
