### PR TITLE
TASK: Require all collection packages as self.version

### PR DESCRIPTION
**Pull request by kdambekalns**
Any dependency from one package in the collection to another should always be "to the same version".

This changes makes sure this is the case by using `self.version` as the required version.

See neos/neos-development-collection#4257

**Checklist**

- [ ] ~Code follows the PSR-2 coding style~
- [ ] ~Tests have been created, run and adjusted as needed~
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [x] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [x] Reviewer - The first section explains the change briefly for change-logs
- [ ] ~Reviewer - Breaking Changes are marked wit `!!!` and have upgrade-instructions~

**Upgrade instructions**

**Review instructions**

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Review by kitsunet — APPROVED** [review]
I like <3

Should make a lot of stuff easier.

**Review by fcool — APPROVED** [review]

**Comment by fcool** [comment]
The failing Action in PHP 7.4 at least looks like a "temporal" issue and not like an acutal issue with the change.

**Review by jonnitto — APPROVED** [review]
By reading

**Comment by kitsunet** [comment]
Reran the 7.4 job to confirm it was unrelated, merging

**Pull request merged**
