### PR TITLE
TASK: Finalize standalone contentrepository

### LINKED ISSUE #4227: Standalone ContentRepository.Core !
- [x] Get rid of `ObjectManagerInterface` in `NodeType` and `NodeTypeManager`
- [x] Replace `\Neos\Flow\Utility\Algorithms::generateUUID()` in ID-ValueObjects
- [x] Remove/rewrite Behat test traits!?
- [x] Make unit tests extend `\PHPUnit\Framework\TestCase` instead of `\Neos\Flow\Tests\UnitTestCase`
- [x] Get rid of Doctrine DBAL (v2) dependency (#4989)
- [ ] SQLite support
- [ ] Expose projection DBAL Schema (#4991)
- [ ] Remove `neos/eventstore-doctrineadapter` dependency (no hard requirement)

~- [ ] Improve `NodeTypeManager` API (#4228)~ Postponed to 9.1 or later – this can be done in a bridge layer

### PR DESCRIPTION
**Pull request by mhsdesign**
Resolves: #4227

**Upgrade instructions**

**Review instructions**

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Review by bwaidelich — APPROVED** [review]
You're the man!
+1 by reading

**Review by kitsunet — APPROVED** [review]
What speaks against the root type in there? I mean fine if we don't need it :D

**Comment by bwaidelich** [comment]
> What speaks against the root type in there?
 
The root type ought to be defined by the `CR` core – i.e. it will always exists even if it is not explicitly configured

**Comment by kdambekalns** [comment]
> The root type ought to be defined by the `CR` core

Hence https://github.com/neos/neos-development-collection/pull/4644/commits/b8621148da4624aaa459e70b3404cebe2ddff9bc …

**Review by kdambekalns — APPROVED** [review]
👏

**Comment by bwaidelich** [comment]
Some failing tests still:
Unit
```
1) Neos\ContentRepository\Core\Tests\Unit\NodeType\NodeTypeManagerTest::getNodeTypesReturnsRegisteredNodeTypes
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
     7 => 'Neos.ContentRepository.Testing:Page2'
     8 => 'Neos.ContentRepository.Testing:Page3'
     9 => 'Neos.ContentRepository.Testin...rtypes'
+    10 => 'Neos.ContentRepository:Root'
 )
```

Behat:
```
001 Scenario: Initial setup of the root node (similar to 01/RootNodeCreation/03-...) # Features/RootNodeAggregateDimensionUpdates/UpdateRootNodeAggregateDimensions_WithDimensions.feature:30
      And the command CreateRootNodeAggregateWithNode is executed with payload:      # Features/RootNodeAggregateDimensionUpdates/UpdateRootNodeAggregateDimensions_WithDimensions.feature:24
        Behat\Testwork\Call\Exception\FatalThrowableError: Type error: Neos\ContentRepository\BehavioralTests\TestSuite\Behavior\GherkinPyStringNodeBasedNodeTypeManagerFactory::Neos\ContentRepository\BehavioralTests\TestSuite\Behavior\{closure}(): Return value must be of type array, null returned in /home/runner/work/neos-development-collection/neos-development-collection/neos-development-distribution/Packages/Neos/Neos.ContentRepository.BehavioralTests/Classes/TestSuite/Behavior/GherkinPyStringNodeBasedNodeTypeManagerFactory.php:48
```

**Pull request merged**
