### PR TITLE
TASK: Optimise php imports in Neos 9 code

### PR DESCRIPTION
**Pull request by mhsdesign**
Related: https://github.com/neos/neos-development-collection/issues/4580

Phpstorm supports to optimise imports via `Optimise Imports [ctrl+alt+O]`
This will not only remove outdated imports but also sort them.

In the past when removing a usage i deleted the line manually without sorting to prevent merge conflicts,
but i would like to use the key stroke generally and know that others do as well.

So with care that we _do_ want to upmerge things from 8.3 i ran the import optimisation across the whole repository but only committed newer neos 9 code.

New neos code lies in `Neos.ContentRepository*`, `Neos.ContentGraph*`, `Neos.TimeableNodeVisibility` and partially in selected subdirectories and files of `Neos.Neos` (my strategy was if the file was already touched for a neos 9 refactoring (e.g. we import the contentRepository) its fine to cleanup here).

After this change optimising imports can be carried out safely (at least in new code) as the imports are now tidied.
This will prevent needless mergeconflicts across prs in the future and should improve our workflow. 

**Upgrade instructions**

**Review instructions**

This change should not make upmerging harder than before as the classes in `Neos.ContentRepository*` didnt exist in 8.3 and the few classes modified in `Neos.Neos` have been adjusted in general for Neos 9.

**Checklist**

- [x] Code follows the PSR-2 coding style
- [x] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [x] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [x] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Review by bwaidelich — APPROVED** [review]

**Review by kdambekalns — APPROVED** [review]
👍 by 👀

**Comment by mhsdesign** [comment]
Hmm I just had a change of mind. To be kind to our existing Mammut prs ill delay this cosmetic cleanup as it can be run at any point automatically ;)

**Comment by mhsdesign** [comment]
Thanks for your reviews though ;)

**Comment by mhsdesign** [comment]
With all the elephants merged a change like this can now be more safely carried out ;) (we wont hurt any other big pr)

**Review by dlubitz — APPROVED** [review]
Works for me, but ordering imports by name is useless if we don't have any rule to keep this also in future.

**Comment by mhsdesign** [comment]
Yeah sure without automatic linting we cannot guarantee that this will be kept. But for those of us using phpstorm they can enforce this pattern. And having this as a headstart is quite good i think (the escr code was created over years by multiple people, its only natural that we have more than 160 outdated imports in the files). Also for linting we would have exclude all the packages that were deliberately not cleaned up as they would cause unnecessary conflicts in up-merges like Neos.Fusion or Neos.Media and friends.

Fyi im using the default phpstorm import sort settings (alphabetically):

image

**Comment by bwaidelich** [comment]
Shall we add https://cs.symfony.com/doc/rules/import/ordered_imports.html ?

**Comment by mhsdesign** [comment]
Hmm seeing that we _have_ already php cs (im not using it locally really ...) thats not a bad idea.
And regarding import ordering in Neos.Fusion or Neos.Media and friends, i can very well imagine creating a pr against 8.3 and upmerge these changes ;)

**Comment by bwaidelich** [comment]
> Hmm seeing that we have already php cs (im not using it locally really ...) thats not a bad idea.

Especially because it is enforced by our CI (`composer lint`)

Related: https://github.com/neos/neos-development-collection/issues/4580

**Comment by mhsdesign** [comment]
@bwaidelich i stand completely on the schlauch i dont know how to set this up and it might be that i confused php cs and the fixer 😅 

in the end we want a linter and not a fixer, or at least first a linter and then a fixer on top. But i couldnt find a sniff in php code sniffer that does this. I tried extending your new xml somehow but there seems to sniff?
There is only `src/Standards/PSR12/Sniffs/Files/ImportStatementSniff.php` which doesnt check usages nor sort.

**Comment by bwaidelich** [comment]
[PHP_CodeSniffer](https://github.com/PHPCSStandards/PHP_CodeSniffer/) is pretty confusing.. In our case:
`composer lint:phpcs` runs `phpcs`, that complaints about linting errors (and we run that in our CI).
`composer lint:phpcs:fix` was added for convenience. It runs `phpcbf`, that automatically fixes most of the linter errors.

And then there is [PHP-CS-Fixer](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer) that is a different, unrelated, tool that also provides a linter & fixer. But we don't use that (yet).

Unfortunately, detecting unused import statements is not yet available for PHPCS and  seems to be a very complex task.
For _ordering_ imports there are 3rd party "sniffs", e.g. : https://github.com/slevomat/coding-standard/blob/master/doc/namespaces.md#slevomatcodingstandardnamespacesalphabeticallysorteduses-

**Comment by bwaidelich** [comment]
A little PHP-CS-Fixer experiment: https://github.com/neos/neos-development-collection/pull/4949

**Comment by bwaidelich** [comment]
@mhsdesign I ran my experiment with your PR and it reduces the violating files from 237 to 29. But after applying the fixer, I still get a diff:
[changes.patch](https://github.com/neos/neos-development-collection/files/14627381/changes.patch)

*edit*: ..which is to be expected, those are just the remaining `use` orderings AFAIS. I created a PR with the `composer lint:fix` change applied: #4950

**Comment by mhsdesign** [comment]
Wow thanks @bwaidelich for explaining. it really seems that they choose unwise namings ^^

I would propose to merge this now, and create a separate pr to fix violations in 8.3

Also linting in ci seems more complex and not a one liner so let’s merge this first and keep https://github.com/neos/neos-development-collection/pull/4949 as a follow-up

That way we can continue with other mamut prs right now (e.g. node identity)

**Pull request merged**
