### PR TITLE
FEATURE: Add missing translation to flash messages

### PR DESCRIPTION
**Pull request by NicholaPunkt**
**What I did**
added translation to all flash messages
**How I did it**
added translator and translation units to all flash messages

Fixes: #3334

### CODE REVIEW

**Review by daniellienert — APPROVED** [review]
Hey @NicholaPunkt, 
thanks for your first contribution to this repository!
The changes look good to me.

**Review by kdambekalns — DISMISSED** [review]
**First of all: Thanks for your contribution @NicholaPunkt!**

That looks like it was a tedious task… and it adds quite a lot of code that repeats itself. 😬

Maybe a helper method or an adjustment to `addFlashMessage(…)` could be used instead? Or we do it like for validation errors. The "usual approach" here is using the error codes, see https://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartIII/Internationalization.html#localizing-validation-error-messages

Something similar could be done here, too - the flash messages support a `code`, too. It can only be an integer (otherwise one could have simply passed an XLIFF message if), and unfortunately the same code is duplicated in some cases (which should never happen). But with that fixed (which would be good anyway)…

It would need adjustment to the display of flash messages (that could be done in templates, probably it's just a partial that is reused), but would save a ton of translator injections and `translate(…)` calls…

What do you think?

**Comment by jonnitto** [comment]
Hi @NicholaPunkt 
Today we will have the feature freeze for Neos 6. Will you be able to address the requested changes from @kdambekalns?

**Comment by albe** [comment]
Given the `translator` was already used to translate FlashMessages directly at quite some places (e.g. https://github.com/neos/neos-development-collection/pull/3102/files#diff-4ddd9ae071becedffee71888f1eeba1202d072721742dfb19a4a7ce92950da30L201), this improves the UX for users (once the labes are translated into other languages) and refactoring this to be less repetition is "just" 💅, I'd argue to get this in as is for now.
Then open a new issue to clean this up and fix this in any future bugfix release, instead of blocking this to next minor :)

Do you agree @kdambekalns ?

**Comment by markusguenther** [comment]
Puh seems that we need to overhaul this PR after it is messed up after the 7.0 release.
But would be awesome to have this :)

**Comment by albe** [comment]
If someone could rebase this I would still consider this for 7.1

**Comment by markusguenther** [comment]
@albe Will take care ... but will not make it today.

**Review by markusguenther — APPROVED** [review]
Thank you for this hard work. First class PR 🎉

**Review by albe — APPROVED** [review]

**Comment by albe** [comment]
ping @kdambekalns - any objections still?

**Comment by kdambekalns** [comment]
Hopefully this triggers CI (correctly)…

**Comment by albe** [comment]
Added an issue to do the cleanup work - so I guess this is good to go :) Thanks everyone!

**Comment by albe** [comment]
Note: This causes a regression when the `defaultLanguage` is set to something else than `en`, since the missing translation will make the translator return `null`, which is not accepted as first value to the `addFlashMessage()` method. So we need to add a fallback, either right here or in the Translator itself.

**Pull request merged**
