### PR TITLE
BUGFIX: Fusion based error handling was not included anymore

### LINKED ISSUE #3995: BUG: No Fusion object found in path "error"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It seems like that the fusion object path "error" does not exist anymore which prevents the configuration of custom error pages.

**Configuration:**
```afx
error {
    4xx {
        ...
    }
}
```

### Expected Behavior

To be able to configure custom error pages.

### Steps To Reproduce

[https://www.neos.io/FORCE404ERROR](https://www.neos.io/FORCE404ERROR)

### Environment

```markdown
- Flow: 8.2
- Neos: 8.2
- PHP: 8.1
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Sebobo**
This fixes a regression in #3915 and resolves #3995

### CODE REVIEW

**Review by kdambekalns — APPROVED** [review]
🔎

**Review by markusguenther — APPROVED** [review]
Thanks for the finding and fix 👍

**Comment by Nikdro** [comment]
Am I right, that there is no new tagged version with this bugfix in it?   
We are getting trouble about this on every project, we update currently.   

Can we maybe get a bugfix-release ready for it? 😇

**Comment by mhsdesign** [comment]
Id like the regression introduced by the hotfix get fixed first: https://github.com/neos/neos-development-collection/pull/4054
but after that sure. I also lately noticed this problem and its painfull. Sorry for the wait.

**Comment by mhsdesign** [comment]
voila @Nikdro [Neos 8.2.3](https://github.com/neos/neos-development-collection/releases/tag/8.2.3)

**Pull request merged**
