### PR TITLE
TASK: Refactor AfxService

### PR DESCRIPTION
**Pull request by mhsdesign**
remove wrong php docs and add php types.
use multiple 'nested' generators to create the attributes.
astBooleanToFusion could technically now also render 'false', what is never the case but still.
removed unnecessary checks against truthy or null, when method never returns falsy.
restructure code.

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)

### CODE REVIEW

**Comment by mhsdesign** [comment]
I did this just for fun... a much bigger step forward would be to use an ast out of real objects and build an ast node visitor.

(or even parse afx with the fusion parser by extending it a little?)

**Comment by mhsdesign** [comment]
see https://github.com/neos/neos-development-collection/issues/3896 and https://github.com/neos/neos-development-collection/issues/3555 what could be gained with a new afx parser and ast node visitor pattern (similar to the new fusion parser)

**Review by grebaldi — APPROVED** [review]
LGTM :+1: Nice work!

I'll request another review from @mficzel to take a look at the spread-related parts.

> [...] a much bigger step forward would be to use an ast out of real objects and build an ast node visitor.

I'd be up for that, if you need support :)

**Comment by mhsdesign** [comment]
Thanks for you review ;)

> to take a look at the spread-related parts.

i made them hopefully more readable in https://github.com/neos/neos-development-collection/pull/3596/commits/0d4ab978b51184ebae1f52698af2f8032d365902

> > [...] a much bigger step forward would be to use an ast out of real objects and build an ast node visitor.
> 
> I'd be up for that, if you need support :)

... and also a new Parser while we are on it? ^^ to fix fx. https://github.com/neos/neos-development-collection/issues/3896 and https://github.com/neos/neos-development-collection/issues/3555

**Pull request merged**
