### PR TITLE
WIP !!! TASK: Render redirects for shortcuts via Fusion

### PR DESCRIPTION
**Pull request by mficzel**
Since fusion is capable of rendering http-responses it is perfectly capable of rendering
the redirects for shortcut-documents. This allows to remove the respective logic from the
NodeController and avoids a parallel implementation of the shortcut target resolving.

### CODE REVIEW

**Comment by mficzel** [comment]
@daniellienert i am confused. This is based ob latest master. Is the pr that makes behat green again already in merged?

**Comment by daniellienert** [comment]
@mficzel, your right, master is broken also (https://travis-ci.org/neos/neos-development-collection/branches). Thought @kdambekalns worked on it.

**Comment by kdambekalns** [comment]
Yes, I though I had fixed it. But it seems I forgot to push a change to the Neos development distribution, doh… I'll check that.

**Comment by kdambekalns** [comment]
Yeah, pushed the removal of `Build/Behat` to the development distribution. Then more errors came up, see https://github.com/neos/neos-development-collection/pull/2382

**Comment by mficzel** [comment]
@daniellienert rebased and finally green, thanks @kdambekalns

**Comment by aertmann** [comment]
this has a couple consequences which should be considered before merging..

The `UnresolvableShortcutException` class is no longer thrown/used, that's probably okay but could potentially be breaking. However having the handling done in the linking service is better as it makes it consistent. At the very least the class should be removed.

If a shortcut target node is not found, `NodeNotFoundException` is no longer thrown. Instead `NeosException` is thrown in https://github.com/neos/neos-development-collection/blob/master/Neos.Neos/Classes/Service/LinkingService.php#L281. Again this is probably okay, but we should consider replacing that exception with `NodeNotFoundException`.

**Comment by mficzel** [comment]
@aertmann good catch, i removed the UnresolvedShortcutException but have trouble throwing the NotFoundException in the linkingService. Do you have a clever suggestion?

**Comment by mficzel** [comment]
The decision that is still needed here is wether we consider the changes @aertmann mentioned in https://github.com/neos/neos-development-collection/pull/2373#issuecomment-468253523 a problem or not.

**Comment by bwaidelich** [comment]
I'm loving it! :)
IMO it's just important that an unresolved shortcut leads to a 404 in the frontend – if that's the case, I'd be fine with the potentially breaking changes for the next major!

**Comment by mficzel** [comment]
Checked the behavior of requests to shortcuts without proper target and discovered that no proper 404 is rendered. At the moment i have no clue how to circumvent this and will put this aside until i get a better idea.

**Comment by mhsdesign** [comment]
Should this be closed?

**Pull request closed without merging**
