### PR TITLE
TASK: Make the InsertNode panel keyboard friendly

### PR DESCRIPTION
**Pull request by dfeyer**
This change add support to select a node type with the keyboard left/right 
arrows and confirm the selection with return.

### CODE REVIEW

**Comment by dfeyer** [comment]
DONT MERGE THIS ONE, it depend and include https://github.com/neos/neos-development-collection/pull/709

**Comment by dfeyer** [comment]
Basically this work for insert content node, currently the insert node in the tree is broken due to styles changes. 

@aertmann I need help https://github.com/neos/neos-development-collection/pull/716/commits/150ed413e33c785fb41011805ff4d5d050f5768b#diff-e3ac5b9651c682325495c25607a86743R217 ... no clue why this don't work, the idea is to keep the currently selected element in the visible parts of the modal, any help welcome

**Comment by kitsunet** [comment]
Same question here @dfeyer rebase or wait and (re)do for rewritten UI?

**Comment by daniellienert** [comment]
@dfeyer As the new UI is around the corner, I would like to close this PR. What do you think?

**Comment by dfeyer** [comment]
ok for closing this one

**Pull request closed without merging**
