### PR TITLE
TASK: Display insert position in insert new panel

### PR DESCRIPTION
**Pull request by aertmann**
Display the selected position in the insert new panel header.

NEOS-1121 #close

### CODE REVIEW

**Comment by aertmann** [comment]
image

**Comment by dimaip** [comment]
:+1: by reading, very handy improvement!

**Comment by aertmann** [comment]
moved the opening stuff to https://github.com/neos/neos-development-collection/pull/427/commits/a27414d7087f69feda469bb87d128db937e4fc02 since it depends on it

**Comment by johannessteu** [comment]
Tested all variants. Works like a charm. But when testing this i always kind of expected the name of the current node before the icon like `Create new after Contact` while Contact is the name of the node. But this could be done with a follow up

**Comment by aertmann** [comment]
@johannessteu: had the same though, but can only be done after merging #416

**Comment by aertmann** [comment]
rebased

**Pull request merged**
