### PR TITLE
BUGFIX: Search node properties with "contains" instead of "beginsWith"

### LINKED ISSUE #4188: BUG: Node search in reference editor doesn't return results
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I search for a content node via content reference editor, I don't get any results. 

As it seems the query is internally build for doctrine to search for 'searchTerm%', which excludes all nodes where the property doesn't exactly start with the search term e.g if it contains also HTML.

### Expected Behavior

I'd like to get all matching nodes as result.

### Steps To Reproduce

1. Create a content element which has 'Neos.Neos:Content' as supertype (e.g Neos.Demo:Content.Headline)
2. Set the headline to "My Headline"
3. Create a node of type `Neos.NodeTypes.ContentReferences:ContentReferences`
4. Search for "My" or "Headline"

### Environment

```markdown
- Flow: 8.3
- Neos: 9.0
- PHP: 8.1
```

### Anything else?

See: https://github.com/dlubitz/neos-development-collection/blob/1ebc9af8ee66760b8c9375b570f06e54f0540909/Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentSubgraph.php#L606-L606

### PR DESCRIPTION
**Pull request by dlubitz**
Fixes: https://github.com/neos/neos-development-collection/issues/4188

### CODE REVIEW

**Comment by skurfuerst** [comment]
IMHO a very good catch. @bwaidelich do you remember why you did "starts with" here? I believe you recently touched this code :)

**Comment by bwaidelich** [comment]
yes, good catch!
Can we wait with this one a bit though? I have a PR in the works that adds search functionality to all the query endpoints and I would integrate this fix there including tests if you are OK with that!?

**Comment by skurfuerst** [comment]
makes sense @bwaidelich <3

**Comment by dlubitz** [comment]
Sure, that's fine.

**Comment by bwaidelich** [comment]
Closing in favor of #4233 (as discussed)

**Pull request closed without merging**
