### PR TITLE
TASK: Exchange login wallpaper for version 3.2

### PR DESCRIPTION
**Pull request by daniellienert**
Exchange the login wallpaper vor version 3.2. 
As the image is very good compressible, I chose a width of 2400 px this time.

### CODE REVIEW

**Comment by daniellienert** [comment]
I am pretty sure, that travis isn't in principle against the image ;)

**Comment by aertmann** [comment]
Based on votes in https://discuss.neos.io/t/neos-3-2-login-wallpaper/2517/13 – what a narrow winner 😀

👍 for the larger size

**Comment by aertmann** [comment]
a little shame it goes from green to green though

**Comment by aertmann** [comment]
if sticking with the seasons, something like this would have been more appropriate
image

**Pull request merged**
