### PR TITLE
BUGFIX: Continue with Menu-Generation even if a Node-Dimension is null

### PR DESCRIPTION
**Pull request by sbruggmann**

### CODE REVIEW

**Comment by bwaidelich** [comment]
@sbruggmann Thanks for your contribution!
Even though this is such a small change I'm not sure what exactly it fixes. Could you add a quick description?

**Comment by sbruggmann** [comment]
In a client project with complex country and language dimensions it happened that one $nodeInDimensions were null and the script crashed.

I don't know why it was null, but with the fix the output looks valid. So I didn't dive deeper

**Comment by aertmann** [comment]
Hey thanks for reporting, however I'm not able to reproduce this issue. It also sounds very odd to me that a specific file ending would cause anything like this.

Can you reproduce this behavior on a fresh install with the demo site? It's more likely to be related to your specific site/installation or setup than a core issue.

You mentioned a lot of affected versions, did you confirm the issue exists in all of those versions?

**Comment by jonnitto** [comment]
After having a short talkback with Stefan, I'll close this PR. Thanks to all who participated!

**Pull request closed without merging**
