### PR TITLE
TASK: Removes EventLog and history module

### LINKED ISSUE #4553: 9.0 State of History Module
The history module is currently not implemented/working and its heart mostly commented out:

https://github.com/neos/neos-development-collection/blob/73bf90f9348a1c560b61a8f112f8d0bc80942925/Neos.Neos/Classes/EventLog/Integrations/ContentRepositoryIntegrationService.php

## Option A:

create a simple implementation, which might not even be able to do more than the old history module. (Reusing the fluid templates?)

there was a wip implementation from 2021 which we might get some inspiration from:

https://github.com/neos/contentrepository-development-collection/pull/168

## Option B:

Create a way improved history module with way more possibilities - completely rewritten from scratch - dont say undo ^^

## Option C:

remove it (as there is no working code, only dead code) and add it as feature with 9.x

### PR DESCRIPTION
**Pull request by markusguenther**
Remove the legacy history module and event log due to incompatibility with NeosCMS 9.0's Event Sourced Content Repository. Future enhancements will be based on event-driven features.

**Upgrade instructions**

You can remove the setting for the `eventLog` in your project, but it does not harm if you keep it.

**Review instructions**

Check if the `eventLog` stuff and the history module is gone and nothing is broken.

Resolves: #4553

**Checklist**

- [x] Code follows the PSR-2 coding style
- [x] Tests have been created, run and adjusted as needed
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Review by bwaidelich — APPROVED** [review]
+1 by reading, thanks for taking care!

**Comment by markusguenther** [comment]
Unit tests failed... but need to check if it comes from my change 🙈

**Comment by markusguenther** [comment]
It seems that the failing test from the RedisBackend is not from my changes. I also have it for 9.0 branch locally.

**Comment by ahaeslich** [comment]
> It seems that the failing test from the RedisBackend is not from my changes. I also have it for 9.0 branch locally.

They also suddenly failed here: https://github.com/neos/flow-development-collection/pull/3172#issuecomment-1757127117

**Review by mhsdesign — COMMENTED** [review]
looks great so far ;)

i think we should remove the old doctrine migrations so we dont have the `neos_neos_eventlog_domain_model_event` table anymore no?

related https://github.com/neos/neos-development-collection/pull/4240

**Comment by markusguenther** [comment]
@mhsdesign Table has been removed!

**Comment by mhsdesign** [comment]
Thanks. Im still not sure if it wouldnt be better to clean up those old 10 migrations but i created a follow up:
https://github.com/neos/neos-development-collection/issues/4594

**Review by ahaeslich — APPROVED** [review]

**Pull request merged**
