### PR TITLE
FEATURE: NodeType configuration command controller

### PR DESCRIPTION
**Pull request by mhsdesign**
### `./flow nodetypes:show`

 **Show NodeType Configuration**

 Shows the merged configuration (including supertypes) of a NodeType

 **Examples:**

 ``./flow nodeTypes:show Vendor.Site:Content``

 ``./flow nodeTypes:show Vendor.Site:Content --path="properties.bar"``

 _Options_

 ``--node-type-name`` The name of the NodeType to show
 ``--path`` Optional path of the NodeType-configuration which will be shown

### `./flow nodetypes: list `

 **List NodeTypes**

 Lists all declared NodeTypes grouped by namespace

 **Examples:**

 ``./flow nodeTypes:list --filter Vendor.Site:``

 ``./flow nodeTypes:list --filter Vendor.Site:Document  --include-abstract``

 _Options_

 ``--filter`` Only NodeType-names containing this string will be listed
 ``--include-abstract``  List abstract NodeTypes

**Upgrade instructions**

**Review instructions**

adresses https://github.com/neos/flow-development-collection/pull/1903#issuecomment-580656209
i figured even if the cli could handle dot paths https://github.com/neos/flow-development-collection/pull/2973 (which it wont in the future) one would be able to dump the nodeType config for a single node but what good is it, if you dont get the merged superType config.

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [x] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [x] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Comment by mhsdesign** [comment]
Before i continue with docs and readme ... what do you say about this feature? Id really like this for writing nodeTypes and debugging (sometimes i dont have the ide yaml schema validator installed ^^)

**Comment by bwaidelich** [comment]
Without checking thoroughly, I like the feature. But I would prefer a dedicated CommandController (i.e. `NodeTypes`) since we strive for separating NodeType definitions from the (global) configuration (especially with 9.0 that is)

**Comment by kdambekalns** [comment]
Would love that! ❤️‍🔥

I agree to @bwaidelich aboutthe separate controller.

**Comment by mficzel** [comment]
Would love that and it surely belongs to the core.

**Comment by mhsdesign** [comment]
```sh
./flow nodeTypes:show Vendor.Site:Content

./flow nodeTypes:show Vendor.Site:Content --path="properties.bar"

./flow nodeTypes:list

./flow nodeTypes:list --filter Vendor.Site

./flow nodeTypes:list --filter Vendor.Site:Document  --include-abstract
```

next step would be to add cool informations about finding supertypes and so on

**Review by crydotsnake — APPROVED** [review]

**Review by mficzel — APPROVED** [review]
I really like ... and it works

**Pull request merged**
