### PR TITLE
TASK: PHP 7.4 compatibility

### PR DESCRIPTION
**Pull request by kdambekalns**
See https://github.com/neos/flow-development-collection/issues/1866

### CODE REVIEW

**Comment by kdambekalns** [comment]
Haha, this still needs PHP 7.4 to be enabled for Travis… feel free, I have to run now.

**Comment by kdambekalns** [comment]
FYI: The test failures will be fixed with to https://github.com/Behat/Transliterator/pull/29

**Comment by kdambekalns** [comment]
Haha, right. I only knew `Array and string offset access syntax with curly braces is deprecated` but the GD error is probably a result of switching to Bionic. Seems GD needs to be installed during setup…

**Comment by kdambekalns** [comment]
Ok, still waiting for `behat/transliterator` [PR #29](https://github.com/Behat/Transliterator/pull/29) to be released…

Maybe go this way, too? https://github.com/KnpLabs/DoctrineBehaviors/pull/468/files#diff-c5f7d7b9e0f14fa580860143f56f3b7f

**Comment by kdambekalns** [comment]
Tried `symfony/string` really quick this morning…

```
There were 7 failures:

1) [NeosCR]\Unit\UtilityTest::renderValidNodeNameWorks with data set #2 ('汉语', 'yi-yu')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'yi-yu'
+'han-yu'

/…/Packages/Neos/Neos.ContentRepository/Tests/Unit/UtilityTest.php:54

2) [NeosCR]\Unit\UtilityTest::renderValidNodeNameWorks with data set #5 ('ភាសាខ្មែរ', 'bhaasaakhmaer')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'bhaasaakhmaer'
+'node-270ae7607f9a555aac6ff07f02652788'

/…/Packages/Neos/Neos.ContentRepository/Tests/Unit/UtilityTest.php:54

3) [NeosCR]\Unit\UtilityTest::renderValidNodeNameWorks with data set #6 ('ภาษาไทย', 'phaasaaaithy')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'phaasaaaithy'
+'phas-a-thiy'

/…/Packages/Neos/Neos.ContentRepository/Tests/Unit/UtilityTest.php:54

4) [NeosCR]\Unit\UtilityTest::renderValidNodeNameWorks with data set #7 ('العَرَبِية', 'l-arabiy')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'l-arabiy'
+'al-arabit'

/…/Packages/Neos/Neos.ContentRepository/Tests/Unit/UtilityTest.php:54

5) [NeosCR]\Unit\UtilityTest::renderValidNodeNameWorks with data set #9 ('한국어', 'hangugeo')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'hangugeo'
+'hangug-eo'

/…/Packages/Neos/Neos.ContentRepository/Tests/Unit/UtilityTest.php:54

6) [NeosCR]\Unit\UtilityTest::renderValidNodeNameWorks with data set #11 ('မြန်မာဘာသာ', 'm-n-maabhaasaa')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'m-n-maabhaasaa'
+'node-e035ba647b2805199cfab4478fff8cf1'

/…/Packages/Neos/Neos.ContentRepository/Tests/Unit/UtilityTest.php:54

7) [NeosCR]\Unit\UtilityTest::renderValidNodeNameWorks with data set #12 (' हिन्दी', 'hindii')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'hindii'
+'hindi'

/…/Packages/Neos/Neos.ContentRepository/Tests/Unit/UtilityTest.php:54
```

I can imagine the previous results were wrong, so… how do we check that?

**Comment by kdambekalns** [comment]
See https://github.com/symfony/symfony/issues/35061

**Comment by bwaidelich** [comment]
@kdambekalns at least this one is weird
> --- Expected
+++ Actual
@@ @@
-'m-n-maabhaasaa'
+'node-e035ba647b2805199cfab4478fff8cf1'

In general I don't think we should change the transliteration behavior in minor (or even patch) level releases as it can have a great effect.

For the long run I would prefer to avoid any 3rd party library and use the built-in `\Transliterator` instead with a sane configuration, possibly locale-based (see discussion on https://github.com/neos/flow-development-collection/pull/1861#issuecomment-567860262)

**Comment by kdambekalns** [comment]
> use the built-in `\Transliterator` instead with a sane configuration

Hah, been there, done that. If you can find that "sane configuration", ideally backed by some documentation that humans can understand, go ahead.

In the meantime, let's see what pinning `behat/transliterator` gives us (after all, the package changes verry, very, very, very, very slowly) - and if merged with the pinned version, open an issue to remove said pin as soon as a new release of `behat/transliterator` has been done.

**Comment by kdambekalns** [comment]
>  let's see what pinning `behat/transliterator` gives us

I should have seen that coming. Of course using a dev version is impossible unless whitelisted one way or the other in your root manifest. Which we could do for our base and development distributions, but expecting everyone out there to adjust their's seems a bit too much.

**Comment by jonnitto** [comment]
@kdambekalns Looks like we are ready for 7.4 https://github.com/Behat/Transliterator/releases/tag/v1.3.0

**Comment by kdambekalns** [comment]
🎉

**Pull request merged**
