### PR TITLE
BUGFIX: Remove default value for subtreetags to fix MySQL support

### LINKED ISSUE #5252: Fix MySQL support
Setting up the Content Repository on MySQL (8.x) leads to the following exception:

> Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'subtreetags' can't have a default value

Related: #4337

### PR DESCRIPTION
**Pull request by bwaidelich**
Fixes: #5252

### CODE REVIEW

**Comment by dlubitz** [comment]
I wonder if we need to check the string if empty, as this wouldn't be a valid JSON anymore by default.

https://github.com/neos/neos-development-collection/blob/9e8fd2c6ce1c95fd0820dfd91076efe6fa611378/Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/NodeFactory.php#L80

https://github.com/neos/neos-development-collection/blob/9e8fd2c6ce1c95fd0820dfd91076efe6fa611378/Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/NodeFactory.php#L341

But I guess it's fine, as we ensure this in the projection:
https://github.com/neos/neos-development-collection/blob/a0b6d26edbadec3eba0b0000e74f1f8361ba4d1c/Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Projection/HierarchyRelation.php#L48

**Review by dlubitz — APPROVED** [review]

**Comment by bwaidelich** [comment]
> I wonder if we need to check the string if empty, as this wouldn't be a valid JSON anymore by default.

I wondered the same, but the tests are green so ¯\_(ツ)_/¯

**Comment by mhsdesign** [comment]
should we also add a test via this pr to ensure we dont break mysql again? :D

**Comment by bwaidelich** [comment]
> should we also add a test via this pr to ensure we dont break mysql again?

Right. We already have tests, but we don't run them on MySQL – I had added that as a todo for #4337

**Review by mhsdesign — APPROVED** [review]
looks fine by reading but i didnt test *g

**Pull request merged**
