### PR TITLE
BUGFIX: Change aloha.placeholder labels to new editorOptions

### PR DESCRIPTION
**Pull request by markusguenther**
This changs the language label ids for the placeholders of the base mixins.

### CODE REVIEW

**Comment by kdambekalns** [comment]
From original comment:

> **How to verify it**
> Create a text node or an image node with caption. The placeholders will look like that before the change and the labels will be rendered correctly after the change.
> 
> Bildschirmfoto 2019-11-02 um 19 18 16

**Comment by markusguenther** [comment]
Oh your right ... so will need to go back to 5.0 I guess but will check that :)

**Comment by markusguenther** [comment]
@kdambekalns It was introduced in 5.0 with the following commit.
https://github.com/neos/neos-development-collection/commit/33f415bcb03b6989943a63f6298706dd7cd8cc8c

So base branch is now 5.0.

**Comment by daniellienert** [comment]
I am always in favor to get such things cleaned up. But couldn't that be breaking if someone changed that label in its own code?

**Comment by markusguenther** [comment]
@daniellienert Maybe but then it is broken since the 5.0 release when we changed the yaml configuration. We can also provide the old labels, but as we don`t use it in the core it doesn't make so much sense. Or did I miss something.

**Comment by markusguenther** [comment]
When you use i18n and the id has changed and you don`t have a matching label in the in xliff files  - you will see the new id or if you define a default value the default.

**Pull request merged**
