### PR TITLE
TASK: Only show remove button when image selected in ImageEditor

### PR DESCRIPTION
**Pull request by aertmann**

### CODE REVIEW

**Comment by aertmann** [comment]
Could potentially also be a bug fix and backported, any opinions?

**Comment by gerhard-boden** [comment]
Ha, never noticed that. But seen from an UX perspective, this is a bug! So it should be backported IMHO

**Comment by gerhard-boden** [comment]
I also tested this for 2.2, so I can go ahead and blindly smash that `approve` button when the PR comes along :)

**Comment by gerhard-boden** [comment]
@kdambekalns So no backport for 2.2 or separate PR?

**Comment by kitsunet** [comment]
Mmm, didn't we have a policy of not hiding but only ever disabling buttons? So it should be shown disabled I thought?

**Comment by kdambekalns** [comment]
Feel free to backport, @gerhard-boden ;)

And about that hide vs disable–no idea. We should document our UX guidelines!? But why is it that such a remark comes in after it's merged, and the PR was open for 14 days. :/ _sigh_

**Comment by kitsunet** [comment]
I get too many notifications and just saw it while browsing through recent ones \o/ I guess that's not to be helped. After all I don't mind it being removed instead of disabled, but yes we should clearly document this if we haven't already.

**Comment by kdambekalns** [comment]
I know, I know…

Anyway, the crop button is also not disabled but hidden of cropping is, well, disabled.

Also, while I dislike the hiding of menu items (I learn about available features by looking at menu items), it is somewhat clear that removal of an image will be possible again. So, I think it's fine this way.

**Comment by aertmann** [comment]
Fair point, didn't consider that as I looked at the other two which are hidden if not available.

Not sure if we have such a guideline, but sounds reasonable in most cases.

Just tried it in my browser, but found that I prefer it disappearing in this case as the disabled button adds more confusion in my opinion.

**Pull request merged**
