### PR TITLE
BUGFIX: Reenable the nodeTypes properties.ui configuration validation

### PR DESCRIPTION
**Pull request by mficzel**
The configuration of the single properties was altered to support null or dictionary types. Since the both schemas were written as an array of simple types the validator did not use the additionalProperties section any more and only checked wether the property was null or a dictionary.

This change alteres the notation of both types to add make use of the dictionary subvalidation again.

### CODE REVIEW

**Comment by mficzel** [comment]
This change works best together with https://github.com/neos/flow-development-collection/pull/329

**Comment by mficzel** [comment]
There is a principal problem when using types like [null,__complex_schema__] in schemas. The validator will only create the error that none of the given schemas matched the input and not identify the point at which the subschema validation failed. No clue how to avoid that. Maybe we should allow all types to be null as long as they are not required.

**Comment by skurfuerst** [comment]
Hey Martin,

"Maybe we should allow all types to be null as long as they are not required." -- I'd be in favor of this solution! :+1:

I'd also suggest that we fix this also at least in the 2.1 branch!

All the best,
Sebastian

**Comment by mficzel** [comment]
Hello Sebastian, making that for 2.1 is quite hard because therefore the schema-validator would have to be extended. It would be easier and cleaner to alter [null, __schema__] back to just schema but that would bring up validation errors for all instances that use properties = null. The second solution would bring a new feature to the schema-validator so that would have to go into the master of flow and as far as i understand semver it would at least not be nice to base Neos 2.1.x on Flow 3.1.

I could use some advice here.

**Pull request closed without merging**
