### PR TITLE
BUGFIX: Show installed version of packages in package manager backend module

### PR DESCRIPTION
**Pull request by dlubitz**
Show the actually installed version of each package instead of the defined version in the composer manifest.

NEOS-1826 #close

### CODE REVIEW

**Comment by aertmann** [comment]
in case the package isn't actually installed through composer, it could make sense to show the defined version? as in a fallback

**Comment by aertmann** [comment]
can confirm, only an issue from 2.2+

**Comment by dlubitz** [comment]
@aertmann Added the composer.json version as fallback

**Comment by bwaidelich** [comment]
Thanks for taking care. I'd prefer to have the fallback logic
```
$package->getInstalledVersion() ? $package->getInstalledVersion() : $package->getPackageMetaData()->getVersion()
```

encapsulated in

```
Package::getInstalledVersion()
```

or at least keep it in sync with `./flow package:list`.
Besides, the implicit casting from string to boolean might produce unexpected side-effects

**Comment by dlubitz** [comment]
Ok, but in this case I would create an other ticket for the fallback in FLOW and keep this one simple with  `$package->getInstalledVersion()`.

**Comment by bwaidelich** [comment]
> Ok, but in this case I would create an other ticket for the fallback in FLOW

I agree, thanks!

**Comment by dlubitz** [comment]
Fallback: https://jira.neos.io/browse/FLOW-455

**Comment by aertmann** [comment]
makes sense 👍

**Pull request merged**
