### PR TITLE
BUGFIX: getAssetProxy failed for local assets

### PR DESCRIPTION
**Pull request by Sebobo**
With 836d739fa4f92b3c87c0fcaccd54f2909e188773 a condition was added that prevented getting an AssetProxy for assets in the Neos AssetSource. But they all have one and therefore the query for an imported AssetProxy is not skipped for local assets.

**What I did**

Return AssetProxy for local assets.

**How I did it**

Check if the AssetSource is Neos itself.

**How to verify it**

Added functional test

### CODE REVIEW

**Comment by Sebobo** [comment]
@kitsunet maybe you can help me with the now failing test. I'm not exactly sure how to mock an actual external asset source.

**Comment by Sebobo** [comment]
@daniellienert can you maybe look at the failing test? Not sure how to solve it correctly.

**Comment by daniellienert** [comment]
@Sebobo have you ran the tests locally, is it your test that runs into the memory limit?

**Comment by Sebobo** [comment]
Ah sorry, yes here the tests fail because of the memory limit. 

But locally I have an issue with the mock for the AssetProxyRepo. Before the change the repo was never triggered. I'll ping you and show you my issue later.

**Comment by bwaidelich** [comment]
Any news on this one, it's a very reasonable addition IMO

**Comment by radmiraal** [comment]
@Sebobo hey, just gave it a shot to get the test running but I feel like I lack some context / understanding of the issue ;) Can we maybe chat / call about it / can I do something to help?

**Comment by Sebobo** [comment]
@radmiraal, sure thx. We can take a look at it together :)

**Review by radmiraal — APPROVED** [review]

**Comment by Sebobo** [comment]
Mr. @radmiraal helped me fix the broken test that IMO always incorrect but because of the other bug still was green.
So whenever Travis decides to do its work, this can be finally confirmed and merged.

**Review by bwaidelich — APPROVED** [review]
by reading

**Review by albe — APPROVED** [review]

**Pull request merged**
