### PR TITLE
BUGFIX: Use ``neos-`` prefixed class for publish button count badge

### PR DESCRIPTION
**Pull request by aertmann**

### CODE REVIEW

**Comment by robertlemke** [comment]
:+1:

**Comment by kdambekalns** [comment]
:+1:

**Comment by gerhard-boden** [comment]
:+1:

**Comment by robertlemke** [comment]
So, we have 4 times +1 but it looks like none of us tested it :-/
@aertmann I assumed, that you did at least ...

This is how it was supposed to look like:
image

and this is how it looks like now:
image

**Comment by kitsunet** [comment]
But that basically just means that our badge style doesn't work nicely there... The change itself is right, because otherwise there will probably be no style in a non bootstrap site.

**Comment by robertlemke** [comment]
@kitsunet there was a custom style for the publish menu which hasn't been refactored within this change.

I fixed it in #276

**Pull request merged**
