### PR TITLE
BUGFIX: WorkspacesController uses slugified usernames

### PR DESCRIPTION
**Pull request by kitsunet**
NEOS-1740 #comment This PR is a follow up
NEOS-1742 #close

### CODE REVIEW

**Comment by kitsunet** [comment]
Replacement of #312 for 2.1 with squashed commits and fixed concatenation. If travis agrees I will merge and take care of the rest...

**Comment by kitsunet** [comment]
@djneo92nl no need to reopen for 2.1, this is the PR already.

**Comment by djneo92nl** [comment]
@kitsunet Yes i see, i read the messages #312 then did a squash but you where faster

**Comment by kitsunet** [comment]
it's still your commit :)
So win!

**Comment by dimaip** [comment]
@djneo92nl congrats with your first contribution (it is first, right?) and thanks for the fix!

**Comment by djneo92nl** [comment]
haha i see i did one do a pull for https://github.com/Flowpack/Flowpack.ElasticSearch/pull/30 but that was dropped cause of the merge conflicht

**Comment by djneo92nl** [comment]
But why to the 2.1 branch and not the master ?

**Comment by kitsunet** [comment]
because 2.1 contains the bug? According to our merge guidelines all changes go to the lowest affected branch and will subsequently be upmerged into the higher branches.

**Comment by djneo92nl** [comment]
that sounds logical, thanks :)

**Pull request merged**
