### PR TITLE
BUGFIX: Remove old CR migrations and adjust referencing migrations

### PR DESCRIPTION
**Pull request by gradinarufelix**
Removes doctrine and ContentRepository migrations
and applied core migrations

Related: https://github.com/neos/neos-development-collection/issues/4199

### CODE REVIEW

**Comment by bwaidelich** [comment]
I'm not sure why the tests fail. @gradinarufelix could you maybe rebase that to the latest `9.0`. Maybe that fixes CI

**Comment by gradinarufelix** [comment]
Sure thing, I'll try that!

**Comment by gradinarufelix** [comment]
@bwaidelich hab einen Rebase gemacht. Leider scheitert er wieder an einem Lint Fehler, der in einer fremden Datei liegt.

**Review by dlubitz — APPROVED** [review]

**Comment by dlubitz** [comment]
Looks good to me by reading.

**Comment by bwaidelich** [comment]
@gradinarufelix Thanks for the rebase!

> hab einen Rebase gemacht. Leider scheitert er wieder an einem Lint Fehler, der in einer fremden Datei liegt.

OK, an unrelated linting error and behat tests fail (again).. I'll have a look!

**Comment by gradinarufelix** [comment]
Thanks, @bwaidelich, for fixing the CI 🥳

**Review by bwaidelich — APPROVED** [review]
Thank _you_ for your efforts! :)

**Pull request merged**
