### PR TITLE
BUGFIX: Correctly require a stable version of neos/imagine

### PR DESCRIPTION
**Pull request by kitsunet**
The ``neos/image`` version should be a stable version. Additionally
corrects the ``PHP`` version requirement to 7.0 an higher.

### CODE REVIEW

**Comment by kitsunet** [comment]
Ok, tests will probably still fail, but I will merge this as soon as jenkins is done.

**Comment by kdambekalns** [comment]
Yay! `imagine/imagine` released 0.7.1 with `symfony/phpunit-bridge` now being a dev requirement. I restarted the Travis CI build, for good measure. 🤞

**Comment by kdambekalns** [comment]
Ah. no more branch. Sad 🐼 …

**Comment by kitsunet** [comment]
Nah we need to check in in neos/imagine, not here... We can now try to re-introduce a dependency on imagine/imagine ~0.7.1 over there

**Pull request merged**
