### PR TITLE
BUGFIX: Consistently skip processors if ``@if`` evaluated to false

### PR DESCRIPTION
**Pull request by hlubek**
NEOS-1777 #close Fixes the issue

### CODE REVIEW

**Comment by kitsunet** [comment]
:+1: Tested locally as well. Seems fine.

**Comment by kitsunet** [comment]
Will merge in 24h if no one objects.

**Comment by daniellienert** [comment]
:+1: by reading

**Comment by kdambekalns** [comment]
:+1: by reading

**Comment by kdambekalns** [comment]
But, isn't this on **the wrong branch**? Is only master affected?

**Comment by kitsunet** [comment]
No, but it's a rather big change compared to previous behavior. I think that was the reasoning for just master.

**Comment by hlubek** [comment]
The reason to put this only on master is, that I consider that not a breaking change but a change of unspecified behavior. As a user I would not like to have my rendering differ between bugfix versions, but I think putting this in the next minor release would be okay.

**Pull request merged**
