### PR TITLE
Fix AbstractViewHelper FQCN

### PR DESCRIPTION
**Pull request by BlueM**
Was missing “ViewHelper\” part

### CODE REVIEW

**Comment by kitsunet** [comment]
Very cool, thanks. Ideally this should go into the 2.3 branch from there it would be up merged to all the other branches. If you cannot find the respective part in 2.3 docs it should at least target 3.0 docs. Would be awesome if you can take care to reopen this PR to the other branch, otherwise we can help. :)

**Comment by BlueM** [comment]
I don’t even *see* a 2.3 branch (only 1.* and 2.0), so I think it would be best if you could help out.

**Comment by kitsunet** [comment]
sorry, my fault. got confused here. I mean 1.2 branch (the 2.3 branch would be flow).

**Comment by BlueM** [comment]
“AbstractViewHelper” isn’t even mentioned in the 1.2 docs. I now opened a new PR for the 2.0 branch.

**Pull request closed without merging**
