### PR TITLE
[TASK] Cache backend interface labels client side

### PR DESCRIPTION
**Pull request by aertmann**
Makes the backend interface labels cacheable by storing the version
XLIFF cache and generating a URI using that version. When a label is
changed or the selected language is changed, the URI is automatically
updated.

### CODE REVIEW

**Comment by aertmann** [comment]
:+1:

**Comment by aertmann** [comment]
could also go into 2.0, but don't think it's really worth it

**Comment by dfeyer** [comment]
:+1: funny I think about the exact same feature this morning

**Comment by aertmann** [comment]
changed my mind and decided to push to 2.0 instead.. see #256

**Pull request closed without merging**
