### PR TITLE
BUGFIX: Allow content dimension preset translation

### PR DESCRIPTION
**Pull request by kuborgh-mspindelhirn**
**What I did**
Tranlate content dimension labels.

**How I did it**
Just like it is already done for dimension labels

**How to verify it**
Add content dimension. Enter translation id as label. Add id in your translation. Enjoy!

### CODE REVIEW

**Comment by aertmann** [comment]
Hey thanks for the fix, any particular reason not to do it in the template like most other labels are? https://github.com/neos/neos-development-collection/blob/2.3/TYPO3.Neos/Resources/Public/JavaScript/Content/Components/ContentDimensionSelector.html#L12

**Comment by kuborgh-mspindelhirn** [comment]
I looked at the dimension label for orientation. That one is translated in JS. Can change it if best practice is to translate in template.

**Comment by aertmann** [comment]
that is done there as it's a generated value, not just translated.. better do it in the template like the others

**Comment by kuborgh-mspindelhirn** [comment]
@aertmann Aaand. Done! Hope this is better now and thanks for your quick feedback

**Pull request merged**
