### PR TITLE
TASK Fix phpstan complains about QueryBuilder::execute return value

### PR DESCRIPTION
**Pull request by dlubitz**

### CODE REVIEW

**Comment by mhsdesign** [comment]
but why does it complain so suddenly now?

**Comment by dlubitz** [comment]
Because of a lately change: https://github.com/neos/neos-development-collection/commit/164eeadf18e1996e8a7594f4bfae2076558b1e22

**Comment by bwaidelich** [comment]
> Because of a lately change

My bad?! But it didn't complain back then => https://github.com/neos/neos-development-collection/pull/4771/checks

What complaints did you surpress?
Instead of the many ignore comments we should rather add missing type hints IMO

**Comment by dlubitz** [comment]
```
Error: Cannot call method fetchAllAssociative() on Doctrine\DBAL\ForwardCompatibility\Result|int|string.
Error: Cannot call method fetchAllAssociative() on Doctrine\DBAL\ForwardCompatibility\Result|int|string.
Error: Cannot call method fetchAllAssociative() on Doctrine\DBAL\ForwardCompatibility\Result|int|string.
Error: Cannot call method fetchAllAssociative() on Doctrine\DBAL\ForwardCompatibility\Result|int|string.
Error: Cannot call method fetchAllAssociative() on Doctrine\DBAL\ForwardCompatibility\Result|int|string.
Error: Cannot call method fetchAllAssociative() on Doctrine\DBAL\ForwardCompatibility\Result|int|string.
Error: Cannot call method fetchAllAssociative() on Doctrine\DBAL\ForwardCompatibility\Result|int|string.
Error: Cannot call method fetchAllAssociative() on Doctrine\DBAL\ForwardCompatibility\Result|int|string.
Error: Cannot call method fetchAllAssociative() on Doctrine\DBAL\ForwardCompatibility\Result|int|string.
Error: Cannot call method fetchOne() on Doctrine\DBAL\ForwardCompatibility\Result|int|string.
Error: Cannot call method fetchAllAssociative() on Doctrine\DBAL\ForwardCompatibility\Result|int|string.
 ------ ------------------------------------------------------------------------------ 
  Line   Neos.ContentGraph.DoctrineDbalAdapter/src/Domain/Repository/ContentGraph.php  
 ------ ------------------------------------------------------------------------------ 
  157    Cannot call method fetchAllAssociative() on                                   
         Doctrine\DBAL\ForwardCompatibility\Result|int|string.                         
  180    Cannot call method fetchAllAssociative() on                                   
         Doctrine\DBAL\ForwardCompatibility\Result|int|string.                         
  206    Cannot call method fetchAllAssociative() on                                   
         Doctrine\DBAL\ForwardCompatibility\Result|int|string.                         
  [23](https://github.com/neos/neos-development-collection/actions/runs/7034430586/job/19142467901#step:13:24)6    Cannot call method fetchAllAssociative() on                                   
         Doctrine\DBAL\ForwardCompatibility\Result|int|string.                         
  274    Cannot call method fetchAllAssociative() on                                   
         Doctrine\DBAL\ForwardCompatibility\Result|int|string.                         
  289    Cannot call method fetchAllAssociative() on                                   
         Doctrine\DBAL\ForwardCompatibility\Result|int|string.                         
  308    Cannot call method fetchAllAssociative() on                                   
         Doctrine\DBAL\ForwardCompatibility\Result|int|string.                         
  3[26](https://github.com/neos/neos-development-collection/actions/runs/7034430586/job/19142467901#step:13:27)    Cannot call method fetchAllAssociative() on                                   
         Doctrine\DBAL\ForwardCompatibility\Result|int|string.                         
  [36](https://github.com/neos/neos-development-collection/actions/runs/7034430586/job/19142467901#step:13:37)8    Cannot call method fetchAllAssociative() on                                   
         Doctrine\DBAL\ForwardCompatibility\Result|int|string.                         
  [37](https://github.com/neos/neos-development-collection/actions/runs/7034430586/job/19142467901#step:13:38)9    Cannot call method fetchOne() on                                              
         Doctrine\DBAL\ForwardCompatibility\Result|int|string.                         
  [38](https://github.com/neos/neos-development-collection/actions/runs/7034430586/job/19142467901#step:13:39)4    Cannot call method fetchAllAssociative() on                                   
         Doctrine\DBAL\ForwardCompatibility\Result|int|string.                         
 ------ ------------------------------------------------------------------------------
```

**Comment by dlubitz** [comment]
> Instead of the many ignore comments we should rather add missing type hints IMO

I just know one way, that would need to store the result of "execute" in a variable and a check for the type "Result". But this will become a bit ugly and will not help, as it always will be "Result" in our cases.

**Comment by bwaidelich** [comment]
I'll take care of a suggestion as follow-up, OK?

**Comment by dlubitz** [comment]
Looks good to me! But I can't approve as I opened that PR. 👍

**Review by mhsdesign — APPROVED** [review]
Looks good ;) Thanks!

**Review by bwaidelich — APPROVED** [review]

**Pull request merged**
