### PR TITLE
FEATURE: Implement repair of shadow nodes 

### PR DESCRIPTION
**Pull request by kitsunet**
This will reconstruct missing shadow nodes in case something went
wrong in creating or publishing them.

Important is to select a workspace other than live to repair as
shadow nodes only appear in non base workspaces.

### CODE REVIEW

**Comment by kitsunet** [comment]
Created new PR as rebase was necessary. Ideally #653 is merged before as currently that commit is included in this PR.
@kdambekalns review please :)

**Comment by radmiraal** [comment]
Can this happen with 'normal' Neos usage?

+1 by reading

**Comment by kitsunet** [comment]
@radmiraal at least until https://github.com/neos/neos-development-collection/pull/650 is merged pretty easily

**Comment by kdambekalns** [comment]
Tweaked the help texts, read the code, ran the commands. No missing shadow nodes to fix, but…

**Pull request merged**
