### PR TITLE
!!! TASK: Scope fusion-namespaces to current file and remove default `Neos.Neos`-namespace

### PR DESCRIPTION
**Pull request by mficzel**
Namespaces were previously transported over `include` boundaries and
thus could end up being declared in packages differently depending on how
the Fusion code was included. This could easily lead to confusion.

With this change namespaces are handled like in PHP and are only valid for the
Fusion file they are declared in.

In addition this removes the overwriting of the `default` namespace `Neos.Fusion` 
with `Neos.Neos` inside of Neos wich could lead to Fusion code failing if used 
in another context.

### CODE REVIEW

**Comment by mficzel** [comment]
Attention: Neos.Demo in the current state uses namespaces heavily wrong and will not work without 
https://github.com/neos/Neos.Demo/pull/35

**Comment by aertmann** [comment]
Hey this certainly makes sense, however it will probably break more than 50% of all existing sites, give or take. It was done like that in the first place for convenience, albeit it has downsides. I don't think we can justify this change without an automated migration to be honest.

**Comment by gerhard-boden** [comment]
I am totally in favor of this change, but I would also like this to be as painless as possible. So either a migration like Aske suggested, or a noisy deprecation warning within the logs, that namespaces will be removed in the next major (Neos 5.0 that is). Or preferably even both.

**Comment by mficzel** [comment]
@gerhard-boden @aertmann thanks for the feedback i will work on a migration and therefore added the WIP label in the meantime.

**Comment by mficzel** [comment]
@gerhard-boden @aertmann i added two migrations that expand the use of the fusion-default namespace and of declared namespace aliases to the actual package-keys.

For Neos.Demo this applies the changes i did in https://github.com/neos/Neos.Demo/pull/35

**Comment by kitsunet** [comment]
Wonderful 👍

**Pull request merged**
