### PR TITLE
TASK: Revert wip nullable PropertyType `type: ?string`

### PR DESCRIPTION
**Pull request by mhsdesign**
Contains https://github.com/neos/neos-development-collection/pull/4326

The implementation was WIP only, more like a proposal, and not actually implemented for the Ui (to map the the correct editor)

It was discussed, that we dont want to go down the road being strict by default
- As tt would be pretty breaky, require a noisy migration
- Accepting null as property value (or allowing to unset it), is more like the main use case than needing strict validation (as there are only two ways it can be satisfied: either by having a defaultValue or by using the node creationDialog)

Instead of these nullable types (`?string`) it is **_planned_** to be able to declare a property as required like:

```yaml
type: string
required: true
```

See discussion: https://github.com/neos/neos-development-collection/issues/4304

**Upgrade instructions**

**Review instructions**

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Review by bwaidelich — APPROVED** [review]
Thank you!
I like the change and the suggested solution, but we need @nezaniel blessing for it :)

**Comment by mhsdesign** [comment]
upsi, this now contains https://github.com/neos/neos-development-collection/pull/4326, so half of the diff is already reviewed ^^ it was meant to be merged first, but its hard to tell gh this :P

**Review by bwaidelich — APPROVED** [review]
I did not find the time to test this yet, but +1 by reading. Thanks!

**Comment by mhsdesign** [comment]
Bernhard is fine with it ;)

**Pull request merged**
