### PR TITLE
!!! FEATURE Improve standalone FusionView

### PR DESCRIPTION
**Pull request by mficzel**
- The `fallbackView` and related options are removed as it only caused confusion and made debugging harder
- The `fusionPathPatterns` are now expected to point to a single fusion file instead of parsing all files in the while directory. If the path points to a directory the `Root.fusion` is loaded as starting point. 
- Below the Root.fusion all other fusion files have to be included explicitly!
- The cache `Neos_Fusion_ObjectTree` is added and connected to the FusionView via aspect. The cache is enabled only for production via Setting `Neos.Fusion.enableObjectTreeCache`

Upgrade Instructions: If you use the standalone FusionView make sure that a `Root.fusion` exist in your `fusionPathPatterns` and that all other fusion files are included from there.

### CODE REVIEW

**Comment by mficzel** [comment]
I am aware of the Neos.UI and the History.Module who are using custom `fusionPathPatterns` and will have to be adjusted after this.

**Comment by Sebobo** [comment]
Looks great! 
Solves several confusions I had during rewriting some backend modules lately and makes some code unnecessary.

Would there be a way so we don't need to override `initializeView` in Backendmodules to set the Fusion path?

**Comment by skurfuerst** [comment]
@Sebobo "Would there be a way so we don't need to override initializeView in Backendmodules to set the Fusion path?"

Do you really need to do this? Actually this should be resolved automatically based on the current controller etc.

**Comment by mficzel** [comment]
@Sebobo a fusion path is built in the method "getFusionPathForCurrentRequest"  from the controller-namespace by appending the actionName.

So the `index` action in ` Test\\BeModule\\ExampleController` renders using the fusion path `Test/BeModule/ExampleController/index`.

**Comment by Sebobo** [comment]
Sorry I didn't mean the `FusionPath` but the fusion include path.

**Comment by mficzel** [comment]
@Sebobo this defaults to `resource://@package/Private/Fusion`  and expects a `Root.fusion` there. That imho makes sense. 

Main difference from neos-fusion is the autoInclude of fusion via settings. This imho makes sense for controllers in general.

**Comment by Sebobo** [comment]
Yes, but where do we now want to have Fusion backend code. In `Private/Fusion` together with the frontend code or somewhere else?

**Comment by mficzel** [comment]
@sebobo ack but this is backen module specific. Fusion View has to support frontend aswell and thus i would consider "Private/Fusion/Root.fusion" still the most generic entry point.

You only have to adjust this for packages that habe fe and be fusion code which can avoid  by separating into two packages.

**Comment by Sebobo** [comment]
But this would also be no problem if we allow modifying the inclusion path via `Settings.yaml` as we discussed.

**Comment by skurfuerst** [comment]
Hey @Sebobo,

> But this would also be no problem if we allow modifying the inclusion path via `Settings.yaml` as we discussed.

I don't know what you discussed; but isn't Settings.yaml too global for this kind of thing? Alternatively we could make it configurable using Views.yaml. (Just a comment from the sideline ;) )

All the best :) Sebastian

**Comment by Sebobo** [comment]
Could also work via `Views.yaml`, didn't really think about that one as for me it's so connected to Fluid in my head ;)

What I want us to achieve is that it's possible to add custom Fusion and override existing Fusion code for backend modules. So at the end it should be possible to adjust the rendering of existing modules via extensibility.

Like a media module that can be adjusted to a certain projects needs. People are currently try this with a lot of pain and update issues in Fluid. Or something like a dashboard for SEO stuff where multiple modules can add parts to. I feel we should give the devs at least a similar behavior for Fusion based backend modules like we give them in the frontend rendering.

**Comment by mficzel** [comment]
@Sebobo I kind of like the idea to make the include patterns for fusion configurable via settings. It definetly has to be done for every controller explicitly. I kind of fear a situation where the backend breaks because a package was installed that overwrote some essential prototypes. 

Shall we try to fit this in here or in a follow up pr? I consider this valuable already.

**Comment by Sebobo** [comment]
I'm fine with splitting this and having a follow up 👍 

You can already break the backend via fluid so I don't see a new issue there.
At least via the include patterns you could more easily see where the code comes from. The `Views.yaml` syntax is harder to understand imo.

**Comment by skurfuerst** [comment]
@Sebobo fine with me to use Settings - your argument makes sense to me :+1: :)

**Comment by mficzel** [comment]
@sebobo @skurfuerst 

How about using the equivalent of

```
Neos:
  Neos:
    fusion:
      enableObjectTreeCache: false
      autoInclude:
        Neos.Fusion: true
        Neos.Neos: true
```

and replace the Vendor Name. Offcourse this would pollute the namespace of each package with a fusion key.

**Comment by Sebobo** [comment]
I liked the version you sent me in Slack: 

```
Neos:
    Fusion:
        view:
            enableObjectTreeCache: true
            
            default:
                fusionPathPatterns:
                    main: 'resource://@package/Private/Fusion'
                fusionPath: '@package.@subpackage.@controller.@action'
                
            controller:
                myPackage:
                    controllerNamePattern: 'Vendor\Site\Backend\*'
                    fusionPathPatterns: 
                        main: 'resource://@package/Private/Fusion' 
```

What's missing is the possibility to modify the position.
The `autoInclude` from your example could be added to that too.

**Comment by skurfuerst** [comment]
@Sebobo @mficzel hmm - this means this is scoped *per controller* - is that really the right abstraction? I thought per "Module" or "Functionality" might be better, which might include multiple controllers.

All the best,
Sebastian

**Comment by Sebobo** [comment]
@skurfuerst not really as there is the `controllerNamePattern`.

**Comment by skurfuerst** [comment]
ah I see -- so "myPackage" is just a placeholder which can be anything? makes sense :+1:

**Comment by Sebobo** [comment]
Maybe the key `controller` is not the best one and there is one that is more obvious about its use

**Comment by mficzel** [comment]
@skurfuerst @Sebobo that is why i see this as a feature. Configuration is really hard to change and finding a proper flexible configuration is not easy. I also am not sure about the controller name pattern and would now prefer defining the fusion pathes per package.

**Comment by Sebobo** [comment]
I'm also fine with replacing `controller` with `package` and having no pattern for the controller name.

**Comment by kitsunet** [comment]
I really like per controller, per package might not be granular enough, or respectively you would move "routing" into fusion instead. I like controller (and would almost Fluid style also like to see the possibility of per action).

**Comment by kitsunet** [comment]
And regarding settings, technically we have Views.yaml that _could_ very well be used for this.

**Comment by mficzel** [comment]
@kitsunet @Sebobo @skurfuerst when the example in the flow docs regarding views.yaml works the feature is already there.

https://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartIII/ModelViewController.html?highlight=views.yaml#configuring-views-through-views-yaml

**Comment by Sebobo** [comment]
Ah ok, I'll try it in my packages where I'm already using Fusion for the modules.

**Comment by skurfuerst** [comment]
I'd love to use *Views.yaml* for unplanned extensibility there -- as it's exactly planned for this :+1: :+1:

**Comment by Sebobo** [comment]
So I tested this and it works basically. I could remove my patterns from my controller and just have the `Views.yaml` like this:

```
-
  requestFilter: 'isPackage("Neos.RedirectHandler.Ui") && isController("Module")'
  viewObjectName: 'Neos\Fusion\View\FusionView'
  options:
    fusionPathPatterns:
      - 'resource://Neos.Fusion/Private/Fusion'
      - 'resource://Neos.RedirectHandler.Ui/Private/FusionModule'
```

And in my Neos.Demo I now had the `Views.yaml` like this:

```
-
  requestFilter: 'isPackage("Neos.RedirectHandler.Ui") && isController("Module")'
  viewObjectName: 'Neos\Fusion\View\FusionView'
  options:
    fusionPathPatterns:
      - 'resource://Neos.Fusion/Private/Fusion'
      - 'resource://Neos.RedirectHandler.Ui/Private/FusionModule'
      - 'resource://Neos.Demo/Private/FusionModule'
```

And with this I was able to override my prototypes and change the backend module rendering. That's cool and exactly what I wanted.
What I dislike is that I need to copy the `Views.yaml` 100% from the original package and add my path to it. If two packages want to add something this would cause an issue, if I'm correct?

**Comment by skurfuerst** [comment]
@Sebobo oh, good point. @bwaidelich we do not support any mechanism to *merge* fusionPathPattenrs or so, do we? :)

**Comment by Sebobo** [comment]
@bwaidelich sadly the merging still doesn't work

**Pull request merged**
