### PR TITLE
FEATURE: Element breadcrumb in inspector is hidable

### PR DESCRIPTION
**Pull request by ComiR**
To hide set ``TYPO3.Neos.userInterface.inspector.showBreadcrumb`` to ``FALSE``

### CODE REVIEW

**Comment by aertmann** [comment]
While this change shouldn't be needed, since it basically indicates something should be changed in general, I'd be fine with merging it..

**Comment by kdambekalns** [comment]
I fear this option will stay in forever, instead of a "proper" solution to the confusing "breadcrumb-like" dropdown…

**Comment by kitsunet** [comment]
Lets declare the thing deprecated right away? Default disable / remove on next major release.

**Comment by kitsunet** [comment]
Do we even need a replacement solution?

**Comment by kdambekalns** [comment]
I used it a few times today to select something on the Neos website, so… it can be handy. One can of course use the content structure tree, but if that is collapsed…

**Comment by aertmann** [comment]
@kitsunet let's really not make such a decision in such a pull request, it has been improved for 2.2 and is much less confusing than previously..

I still prefer having it and there is a suggestion how to improve it from Christoph Ono, which is what I'd prefer would happen instead of removing it because it's not perfect

**Comment by ComiR** [comment]
So this one is a good workaround for the controversial breadcrumb-dropdown. Merge right away for 2.2?

**Comment by kdambekalns** [comment]
If I understand it correctly, @aertmann wants to keep the breadcrumb and improve it, but does (no longer) favour this very change. Right?

**Comment by robertlemke** [comment]
It's fine for me if we move the bread crumb menu, but I'm really against introducing a configuration option for that. That's exactly the type of configuration which I'd like to keep away from Neos, because it says "I'm unsure about this" instead of bringing additional value for administrators or end-users.

Please discuss / decide if you want to remove the menu or leave it, but 👎 for adding a setting.

**Comment by ComiR** [comment]
Well, I am for making everything configurable, even if it would make no sense on the first sight. Perhaps in some edge cases it would be useful...

My feedback on the breadcrumb was more of a "make it go away", so I'd like to have it removed ;)

**Comment by aertmann** [comment]
just to be clear, I'd prefer not to remove it but would accept a configuration option to remove it even though I don't like it.. would prefer we implemented the improvement suggested by Christoph instead of the configuration

**Comment by robertlemke** [comment]
> Well, I am for making everything configurable, even if it would make no sense on the first sight. Perhaps in some edge cases it would be useful...

Allright, I think we disagree on this one. From the beginning I tried to argue on every setting we introduce to Flow and Neos, if we can avoid it by detecting something automatically or if it's just telling us that we are doing something wrong conceptually. The point with introducing settings "on spec" or just because you think they *might* be useful is that you are increasing the complexity of the code and usage.

Settings are part of the public and supported API, which means that we need to test all combinations of all settings. You might say, hey, that's just an innocent little setting which won't break anything if it disappears - but nip it in the bud! It's quite a challenge to keep the amount of settings low and well documented.

Sorry for making a fuzz about this poor little patch - but the add-another-settings-part has always been something I passionately defended.

Please try to come to an agreement if you want to remove the breadcrumb menu completely or leave it there. It will help reducing the complexity and will sharpen the UX.

**Pull request closed without merging**
