### PR TITLE
[TASK] Add brief section about ``loadingDepth`` node tree setting

### PR DESCRIPTION
**Pull request by gerhard-boden**

### CODE REVIEW

**Comment by kdambekalns** [comment]
:+1:

**Comment by gerhard-boden** [comment]
Please consider this:
https://github.com/neos/neos-development-collection/pull/171#issuecomment-155377213

**Comment by aertmann** [comment]
:+1:

**Comment by dimaip** [comment]
Indeed do we want that merge commit in there or should we rebase?
Since I started using Github, I only care about PR messages, and not so much about intermediate commit messages, but what's our current rule on this?

**Comment by aertmann** [comment]
@dimaip: merge commits are no problem and usually just come naturally in some workflows.. see more on https://discuss.neos.io/t/creating-a-pull-request/506 https://discuss.neos.io/t/commiters-guide/508

**Comment by skurfuerst** [comment]
:+1:

**Comment by gerhard-boden** [comment]
sorry guys, forgot about the index file and index entry for the configuration section (it's my first documentation contribution)
https://github.com/neos/neos-development-collection/pull/176

**Pull request merged**
