### PR TITLE
BUGFIX: Hide the "Create new workspace" button when not authorized

### PR DESCRIPTION
**Pull request by mkuiphuis**
This small change will hide the button "Create new workspace" when the role does not grant the privilegeTarget ``TYPO3.Neos:Backend.CreateWorkspaces``

### CODE REVIEW

**Comment by robertlemke** [comment]
Good catch. I guess this should be classified as BUGFIX and also be merged into older versions, right?

**Comment by mkuiphuis** [comment]
@robertlemke To answer your question: absolutely fine with me. But I have no idea if I need to do anything special to make that happen (it's my first pull request ever in this Neos package). It also happens to be the devil's PR number, but that aside :-)

**Comment by kitsunet** [comment]
@mkuiphuis it's unfortunately a bit tedious, you need to checkout the branch (I guess 2.2 would be appropriate) cherry-pick your change, push to your fork and start a new PR with 2.2 as base.

**Comment by aertmann** [comment]
hmm changing base doesn't really work out of the box unfortunately :/ however you can change the base and update your branch and keep the existing PR..

also it needs to go into `2.1` as it's present there and that version is still supported

**Comment by kitsunet** [comment]
Create workspace is in 2.1? Wasn't aware

**Comment by aertmann** [comment]
@kitsunet: heh no worries, had to look it up as well, just wanted to be sure

**Comment by johannessteu** [comment]
Ok, the change branch stuff does not work bcause of our upmerge stuff :D

**Pull request closed without merging**
