### PR TITLE
!!! TASK: Move workspace module to separate package

### LINKED ISSUE #4255: Overhauled workspace module UX (Neos 9)
Plan:

- [x] 1. Separate workspace module from Neos.Neos package
- [x] 2. Integrate the workspace overview improvements from https://github.com/Sebobo/Shel.Neos.WorkspaceModule 
  - [x] 2.1. Create a backend module bootstrap for React Apps or at least prepare for one
- [ ] 3. 🚫 Overhaul and improve publishing / discarding workflow -> won't do in this iteration
  - [ ] 3.1. Load changes much faster
  - [ ] 3.2. Improved UX for navigating between changes, sites (#1070), dimensions
  - [ ] 3.3. Improve handling of many changes (see also https://github.com/neos/neos-development-collection/issues/913)
  - [ ] 3.4. Improved diff view (maybe in a >9.0 version)
- [x] 4. Integrate into Neos 9.0
  - [x] 4.1 Make basic functions work
  - [x] 4.2 Adjust workspace domain model
  - [x] 4.3 Use fusion instead of fluid 
  - [x] 4.4 Make ACL work again or disable

-> follow-up https://github.com/neos/neos-development-collection/issues/5411

### PR DESCRIPTION
**Pull request by ahaeslich**
Resolves: #4255

**Upgrade instructions**

**Review instructions**

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Comment by ahaeslich** [comment]
We decided on monday to split the PR for the updated workspace module into multiple PRs. I will keep this one for reference at the moment and will close it later on.

**Comment by ahaeslich** [comment]
New PR for moving the workspace module: https://github.com/neos/neos-development-collection/pull/5118

**Comment by mhsdesign** [comment]
can this be closed as oboslete?

**Comment by ahaeslich** [comment]
> can this be closed as oboslete?

We kept this one as a reference. But I think we can close it now.
@Sebobo or do you still need this?

**Pull request closed without merging**
