### PR TITLE
TASK: Make loadingDepth of structure tree configurable

### PR DESCRIPTION
**Pull request by kdambekalns**
Like the node tree the structure tree has a configurable initial loading
depth now.

NEOS-1361 #comment Adjust structure tree handling

### CODE REVIEW

**Comment by kdambekalns** [comment]
The JIRA issue also mentions the inspector panels, how is that handled?

**Comment by aertmann** [comment]
Hey Karsten

The configuration only seems to work on initial load, when navigating to a new page the setting isn't respected. Same goes for when using the reload button in the toolbar. Is that on purpose? Seems counter intuitive to me.

Checked if there was any problems with synchronization and elements not being present, but seems it's handled gracefully. However when the setting is always respected, it could break when it tries to show the moved or copied node e.g.

Also it's a new feature, not a task so should go into master since there's a risk of regressions.

**Comment by kdambekalns** [comment]
@aertmann Thanks for reviewing! Indeed, the refresh/page change was broken, fixed that in the AbstractTree. Testes the handling of insert/update as well, no issues there.

As for the task vs feature thing: I'd consider it a task on the edge of being a bugfix (depending on the depth of the structure people build), not really a feature. The risk of regressions is low IMHO (you found them right away…) with a few more people testing this.

What do others think?

**Comment by aertmann** [comment]
I found some easily, which says something in itself.. Also stated there could others that are harder to stumble upon.. I don't really see it as low risk.

Also how is it almost a bug fix? the tree works with lots of content? might be a bit slow, but doesn't mean it's broken..

And it introduces a new setting.

I get the feeling you need this for a 2.0 project, no?

**Comment by kdambekalns** [comment]
It was done based on 2.0 and would be easier for the client to use, yes. But I already told them it might come with 2.2 only and they'd need to upgrade, so…

**Comment by kdambekalns** [comment]
Replaced by #451 targeting master

**Pull request closed without merging**
