### PR TITLE
TASK: Introduce rebase failed exception and deprecate `WorkspaceRebaseFailed`

### PR DESCRIPTION
**Pull request by nezaniel**
This deprecates the WorkspaceRebaseFailed event with a likewise named exception.

Applications like the Neos UI need detailed information about what exactly failed. Storing this in an event incapacitates the event store quite fast since the amount of data gets quickly out of hand.

Also, we currently have no application for handling the stored data asynchronously. For endpoints like the Neos UI BackendServiceController we need the feedback directly anyway, so instead of waiting for the event to be serialized and deserialized again, they can deal with an exception a lot better.

All necessary information is stored in said exception and thrown with it, readily available for the initiating user to deal with it

**Upgrade instructions**

nothing yet

**Review instructions**

I'm not 100% sure about the workspace / content stream state handling. The conflict state is probably no longer necessary

Related: https://github.com/neos/neos-development-collection/issues/4545

**Checklist**

- [x] Code follows the PSR-12 coding style
- [x] Tests have been created, run and adjusted as needed
- [x] The PR is created against the 9.0 branch
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Review by kitsunet — APPROVED** [review]
I think one of those "merge rather now than later" kind of changes.

**Review by bwaidelich — COMMENTED** [review]
Looks great and the change makes a lot of sense IMO.

Unfortunately, this still does not seem to allow discarding personal changes in order to solve a conflict:

https://github.com/neos/neos-development-collection/assets/307571/a58045c7-1b4d-4d8e-bb02-175b270f914c

is that expected?

**Comment by nezaniel** [comment]
yes, the whole publishing/discarding will be overhauled in https://github.com/neos/neos-ui/issues/3744

**Review by bwaidelich — APPROVED** [review]

**Comment by mhsdesign** [comment]
Question: what happens with `\Neos\ContentRepository\Core\Projection\Workspace\WorkspaceStatus::OUTDATED_CONFLICT` the doc comment is now at least outdated and we never use it anymore besides writing for legacy event but we never query those?

So can we get rid of this `status` ?

**Comment by nezaniel** [comment]
Yep, it's no longer needed afais

**Pull request merged**
