### PR TITLE
TASK: Remove legacy `unstructured` node type

### PR DESCRIPTION
**Pull request by mhsdesign**
**Upgrade instructions**

`unstructured` Node type was the default nodetype for nodes created in the old cr. It was mostly used for the `sites` node (which is okay and migration would work) and possibly for programmatically created nodes. The latter case will not be able to get migrated. One would first need to cleanup the unstructured node types.

**Review instructions**

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Review by nezaniel — APPROVED** [review]
The tests don't lie and we've eliminated the need for unstrucured anything.
So kill it with fire

**Comment by mhsdesign** [comment]
Hmm yes but in most tests we mock the nodetype manager with our own set. And i found out we still expect it to be there sometimes:

https://github.com/neos/neos-development-collection/blob/b2cd87c513a02f53f6ae4168c03c841dac43b38a/Neos.ContentRepository.LegacyNodeMigration/Tests/Behavior/Features/References.feature#L8

**Comment by nezaniel** [comment]
Idk whether it is required for legacy node migrations, if it is, the legacy node migration package should take care of that

**Comment by mhsdesign** [comment]
```
001 Scenario: Referring to non-existing asset        # Features/Assets.feature:179
      And I expect the following errors to be logged # Features/Assets.feature:188
        Expected logged errors do not match
        Failed asserting that two arrays are identical.
        --- Expected
        +++ Actual
        @@ @@
         Array &0 (
        -    0 => 'The node type "unstructured" is not available. Node: "sites-node-id"'
        -    1 => 'Failed to extract assets of property "string" of node "site-node-id" (type: "Some.Package:Homepage"): Failed to find mock asset with id "non-existing-asset"'
        +    0 => 'Failed to extract assets of property "string" of node "site-node-id" (type: "Some.Package:Homepage"): Failed to find mock asset with id "non-existing-asset"'
         )
```

**Review by kitsunet — APPROVED** [review]
by reading

**Pull request merged**
