### PR TITLE
TASK: Add new login wallpaper for Neos 7.1

### PR DESCRIPTION
**Pull request by bwaidelich**
Voting see https://discuss.neos.io/t/neos-7-1-login-wallpaper/5417

### CODE REVIEW

**Comment by bwaidelich** [comment]
The original image in case someone wants to experiment with different optimization options (I used https://squoosh.app/ MozJPEG @ 67% quality):

Oeschinensee

**Review by albe — APPROVED** [review]

**Comment by albe** [comment]
-43 Bytes diff, so I think that is optimized well enough as it is a (slight) improvement! :)

**Comment by albe** [comment]
-43 Bytes diff, so I think that is optimized well enough as it is a (slight) improvement! :)

**Review by markusguenther — APPROVED** [review]
Awesome picture 🥳

**Pull request merged**
