### PR TITLE
FEATURE: Allow mapping of legacy root paths to RootNodeAggregate  NodeTypeNames

### LINKED ISSUE #4895: Migrating old cr data with additional root nodes and their children
Migrating Neos 8 content to Neos 9 will, as of now, migrate all nodes residing below the sites root node. Nodes residing below other root nodes, like e.g. taxonomies, won't be migrated into the new CR.

https://github.com/neos/neos-development-collection/blob/783e08a1b03f33bbb4052b3611c46596f6e934b9/Neos.ContentRepository.LegacyNodeMigration/Classes/NodeDataToEventsProcessor.php#L126-L142

### PR DESCRIPTION
**Pull request by dlubitz**
This PR allows to add a mapping of root paths in old CR to a NodeTypeName for the RootNodeAggregate in the new CR.

This allows to set a configuration within the cli command `./flow cr:migratelegacydata` to pass an alternative rootNodeType mapping.

Our default rule (`{'/sites': 'Neos.Neos:Sites'}`) needs only to be added manually if you want to override the rootNodeType. For example if you want to add the mapping for Sitegeist.Taxonomy package:
```
./flow cr:migratelegacydata --config {"rootNode": {"/sites": "Neos.Neos:Sites", "/taxonomies": "Sitegeist.Taxonomy:Root"}}
```

Fixes #4895

### CODE REVIEW

**Comment by bwaidelich** [comment]
This is a clever solution, thanks for your work.
I'm a bit unsure about the fact that we pass an array around (OTOH that's not really an issue for these low-level tools, just a bit fragile).
And it might be useful to make this an explicit command line argument somehow (at least which root nodes to include).
We already allow to specify a custom db connection like
```shell
./flow cr:migratelegacydata --config '{"dbal": {"dbname": "neos84"}}'
```
what about allowing the mapping to be specified in a similar way, like:
```shell
./flow cr:migratelegacydata --config '{"rootNodes": {"/sites": "Neos.Neos:Sites", "/taxonomies" => "Sitegeist.Taxonomy:Root"}}'
```

I know, this is not very user-friendly. But it's just about the one-time migration, and folks could wrap that in some composer command if it was used more often

**Comment by dlubitz** [comment]
I was also thinking of an VO but just wanted to draft a possible solution first. 

I would be fine with a command parameter, even if I think this is quite anying to write the json on command line. But I wonder how to set the "default" rootNode ("/sites": "Neos.Neos:Sites")? Shall this get provided always by the cli? Or do we simply override a default, WHEN a "rootNodes" configuration was provided?

**Comment by dlubitz** [comment]
Ahh, ok, I see that we also define defaults for other configuations, in case they are not set.

**Review by bwaidelich — APPROVED** [review]
I love it, thanks for taking care!
+1 by reading (not completely sober)

**Review by mhsdesign — APPROVED** [review]

**Comment by mhsdesign** [comment]
Fyi, the one who merged has the honour to solve the nasty conflicts now with https://github.com/neos/neos-development-collection/pull/5307 :D

**Comment by dlubitz** [comment]
@mhsdesign Done!

**Pull request merged**
