### PR TITLE
TASK: Replace TYPO3 by Neos

### PR DESCRIPTION
**Pull request by robertlemke**
This change contains various further replacements of "TYPO3" by "Neos".

Related to https://github.com/neos/flow-development-collection/issues/823

### CODE REVIEW

**Comment by robertlemke** [comment]
@kitsunet thanks! But functional tests despicably fail. Sigh.

**Comment by aertmann** [comment]
don't get why the test fail, that's pretty odd

**Comment by robertlemke** [comment]
Fixed one test, but two tests still fail.

```1) Neos\Neos\Tests\Functional\Domain\NodeUriTest::hiddenNodeGetsNewUriSegmentOnMoveIfUriAlreadyExists
InvalidArgumentException: Given path "/sites/example/home/about-us/history" is not the beginning of "/sites/example/home/products/history", cannot get a relative path between them.```

The thing is: if I only run this test, it succeeds. If I only run all tests in Neos.Neos, they succeed as well. Only when I run all functional tests in the Neos Dev Collection, they fail. But I can't see what's causing it.

**Comment by kitsunet** [comment]
Ok, first things first, as discovered already the test failure is a problem of test separation. Something is leaking from one test to the other. That it fails with this change is due to the change in `\Neos\Neos\Tests\Functional\AbstractNodeTest::markSkippedIfNodeTypesPackageIsNotInstalled` as that was simply wrong since the namespace changes and therefore the respective tests were skipped. I suspect that the actual problem would have existed since package rename as the order of packages (and therefore) tests has changed, which would reveal unwanted test interactions.

**Comment by kitsunet** [comment]
And another update, I indeed found the culprit... Will push a separate change soon, that should be merged beforehand.

**Comment by kitsunet** [comment]
There we go, see commit message for this latest commit. Should make travis happy...

**Pull request merged**
