### PR TITLE
TASK: Add PHP syntax check to Travis test

### PR DESCRIPTION
**Pull request by aertmann**

### CODE REVIEW

**Comment by aertmann** [comment]
Example https://travis-ci.org/aertmann/neos-development-collection/builds/96663827

**Comment by aertmann** [comment]
:+1:

**Comment by kdambekalns** [comment]
I'd put it before th unit tests…

**Comment by kdambekalns** [comment]
…and what would this catch the compile phase for fucntional tests wouldn't catch? Or is it to speed up the build?

**Comment by kitsunet** [comment]
Yeah, I wonder that as well. Normally the 5.3 functional tests should latest break anyway. But fine to do that. Is there some silent flag so that we don't have all the lines about not finding problems in the log?

**Comment by aertmann** [comment]
hmm thought travis would collapse it, but seems that only happens to things outside the script section, can output to /dev/null instead..

hmm not entirely sure if the compile phase catches all syntax errors since we've had so many of them, but could just be due to not running the tests on 5.3 in the past of course

**Comment by kitsunet** [comment]
yeah, adding the test is cool for me, but `> /dev/null` would be appreciated.

**Comment by aertmann** [comment]
running the functional tests seem to have the same effect, seems unnecessary.. sorry for bringing it up

**Pull request closed without merging**
