### PR TITLE
BUGFIX: Copyrightnotice migration for postgres needs default value

### PR DESCRIPTION
**Pull request by daniellienert**
Resolves: #2333

### CODE REVIEW

**Comment by mstruebing** [comment]
Does that field need to be `NOT NULL` at all?

**Comment by daniellienert** [comment]
@mstruebing - a very good question!
As I am quite unexperienced with postgres, I orientated at already existing fields like "caption" which are added just like I did.

`$this->addSql("ALTER TABLE typo3_media_domain_model_asset ADD caption TEXT NOT NULL");`

I am absolutely fine with dropping the `NOT NULL`

**Comment by kdambekalns** [comment]
Thisis actually only partly related to PostgreSQL, in the sense that `NOT NULL` with MySQL only means you cannot insert `NULL`, but leaving out a field fills it with an empty string for character fields.

Technically it rather depends on the model. And [`Asset.php`](https://github.com/neos/neos-development-collection/blob/644b12bf9fea79d8d26fab44ef9276d0d283fc3f/Neos.Media/Classes/Domain/Model/Asset.php#L106) initializes the field with an empty string, so `NOT NULL` with an empty string default seems in fact correct. And yes, the same should be the case for `caption`, to be honest.

Now, confusingly exactly that "empty string default" is the result of `NOT NULL` on MySQL. Go figure.

**Comment by daniellienert** [comment]
Thx @kdambekalns

**Pull request merged**
