### PR TITLE
[TASK] Change documentation for data sources

### PR DESCRIPTION
**Pull request by daniellienert**
Fix doubled quotes in CustomizingInspector.rst
Change the example in DataSources.rst - the example now makes sens for the use
in an inspector select box. Also adjust the code style.

### CODE REVIEW

**Comment by aertmann** [comment]
Hey, it is actually on purpose that the given example is not compliant with the select box editor since the concept is generic and not in any way specific to the select box editor. That specific format is described where it's actually related, http://neos.readthedocs.org/en/stable/References/PropertyEditorReference.html#property-type-string-array-string-selectboxeditor-dropdown-select-editor

**Comment by aertmann** [comment]
Instead I'd suggest to make that more clear, since it seems many are confused and think that data sources are only meant for select box editors.

**Comment by skurfuerst** [comment]
Actually I'd rather like @daniellienert's documentation; and maybe additionally add a callout-box that it can be used somewhere else. Currently at least, we do not use data-sources anywhere else...

**Comment by aertmann** [comment]
adding such a box is kinda missing the point if you ask me.. also the fact that it's not used anywhere else in the core doesn't mean it's not used in projects for other things..

**Comment by daniellienert** [comment]
@aertmann - I see your point - I reverted the example. I would add a reference to the data structure description instead.

**Comment by skurfuerst** [comment]
OK, I am also fine with this. Merging by reading!

**Comment by aertmann** [comment]
yeah looks good, thanks

**Pull request merged**
