### PR TITLE
9.0 FEATURE: Add flowQuery operations `referenceNodes` and `backReferenceNodes`

### LINKED ISSUE #4462: FEATURE: Add flowQuery operations for Neos 9 to support cr references and backRefences
### Is there an existing issue for this topic?

- [X] I have searched the existing issues

### Description

References have to be exposed to flowQuery for beeing usable by integrators.

### Possible Solution

- Add flowQuery operations `references('name')`, `backReferences('name')` to access the referenceObjects
- Add flowQuery operations `referenceNodes('name')` and `backReferenceNodes('name')`  to access the referenced nodes
- Add a method to access properties on references like `referenceProperty('name')`

### PR DESCRIPTION
**Pull request by mficzel**
Other than the operations `reference` and `backReference` those return the nodes and not the reference edges.

This allows queries like the following example which returns all documents that have similar categories:

```
${q(documentNode).referenceNodes('categories').backReferenceNodes('categories').get()}
```
!!! The new operations replace the `nodes` operation that which is removed. This is non breaking as `nodes` was never part of a release !!!

Resolves: #4462 

**Review instructions**

This is basically the code of the `reference` and `backReference` with an array_map at the end that
return the Nodes from the References and not the References.

**Checklist**

- [x] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Comment by mficzel** [comment]
Tests are as non existent as the tests of the `reference` and `backReference` operation.

**Comment by mhsdesign** [comment]
hmm with the  `nodes` operation gone, it doesnt seem to be possible to fetch with one query the properties of a reference plus the node. This might be a problem, as i think no one is interested in reference properites without the actual reference node.

How can we inexpensively fetch both?

Plain php:

```php
$references = $subgraph->findReferences(FindBackReferencesFilter::create(referenceName: "foo"));
foreach ($references as $reference) {
  $reference->node;
  $reference->properties;
}
```

**Comment by mficzel** [comment]
@mhsdesign i would be fine with a better name `nodes()` imho makes litlle sense.

**Comment by mficzel** [comment]
@mhsdesign i decided to not remove `nodes` with this pr. This discussion can be done elsewhere at another time.

**Comment by mhsdesign** [comment]
I agree that the naming `nodes` is not optimal ^^  Or at least the usage is odd ...

**Comment by mficzel** [comment]
I personally think it may be a better ides to go with  `${q(node).references(...).nodes()}` and `${q(node).references(...).property(...)}` ... leave this as draft for now for discussion. Will close once this is settled.

**Review by skurfuerst — APPROVED** [review]
Thanks for your work :)

**Pull request merged**
