### PR TITLE
BUGFIX: Add missing dependency to Neos.Diff

### PR DESCRIPTION
**Pull request by kdambekalns**

### CODE REVIEW

**Comment by kdambekalns** [comment]
Maybe @kitsunet and @aertmann could check this?

**Comment by aertmann** [comment]
:+1: by reading

**Comment by kitsunet** [comment]
Looks good, :+1:

**Comment by kdambekalns** [comment]
> Looks good…

Ok, I'll verify it :)

**Comment by kdambekalns** [comment]
Yeah, looks good. Whatever.

**Pull request merged**
