### PR TITLE
BUGFIX: Layout of login screen blurred background

### PR DESCRIPTION
**Pull request by aertmann**
After a refactoring of the login screen, the blurred background image was wrongly position and sized.

### CODE REVIEW

**Comment by aertmann** [comment]
Broken (after refactoring):
image
Fixed (before refactoring):
image

**Comment by aertmann** [comment]
@gerhard-boden: maybe you can give this one a look? thanks

**Comment by gerhard-boden** [comment]
Hi @aertmann, 

nice to read you again :smile: 

I've tested your changes: 

this is how the login looks in 2.2 before f9a145c2578c36715594344f42214e9199773a1e:
login-2-2-before

After f9a145c2578c36715594344f42214e9199773a1e:
login-2-2-after

With the changes proposed in this PR:
login-2-2-after-change-aske

So in my opinion the layout is not broken at the moment.
Or maybe I am missing what this change is about.

**Comment by aertmann** [comment]
lol sorry @gerhard-boden my bad, had some custom css that stopped working due to new css selectors.. doh

**Comment by gerhard-boden** [comment]
ah i see, no problem! Hope it's not too much effort to adapt your custom styles

**Pull request closed without merging**
