### PR TITLE
TASK: Add tip that session storage is used for dimensions

### PR DESCRIPTION
**Pull request by gerhard-boden**
Added another tip to documentation about content dimension behaviour.

### CODE REVIEW

**Comment by kdambekalns** [comment]
Actually, it's session storage for content dimensions. Local storage is used as well, but for different things…

**Comment by gerhard-boden** [comment]
Thanks for the advice! Changed the commit message and the text in the commit itself of course.

**Comment by aertmann** [comment]
👍 makes sense, although it would be better to bust the cache when the configuration is changed like it's done for the other configuration..

**Comment by dfeyer** [comment]
> makes sense, although it would be better to bust the cache when the configuration is changed like it's done for the other configuration..

From my POV, i prefer to not have this kind of document if we can make it more easy / automagic for our users. So 👍 for cache busting

**Comment by gerhard-boden** [comment]
Hi guys, thanks for the feedback!

I would also appreciate the cache busting approach (if it can be done in anytime soon). Could somebody point me in a direction how we bust the session storage at the moment? 

The note in the documentation is not a substitute for fixing the actual problem of course, but will help people to see that their dimension settings are actually working until we fix the real issue.

**Comment by aertmann** [comment]
@gerhard-boden: see https://github.com/neos/neos-development-collection/blob/f9a03073244d70dcaed233ca1b81089688ac6c3c/TYPO3.Neos/Resources/Private/Templates/TypoScriptObjects/NeosBackendEndpoints.html#L11-L17

all the first ones which are stored using localStorage or sessionStorage are automatically refreshed if the configuration cache is changed, I would assume the same could just be done for the `neos-service-contentdimensions` script

**Comment by aertmann** [comment]
also feel free to push a fix towards 2.0

**Comment by gerhard-boden** [comment]
Thanks for the hint! Will take a look at this in the coming days and do some testing. So let's not merge this one for now, will close it as soon as the other PR is out.

**Comment by gerhard-boden** [comment]
closed in favour of:
https://github.com/neos/neos-development-collection/pull/613

**Pull request closed without merging**
