### PR TITLE
FEATURE: Introduce --skip and --only to node:repair command

### PR DESCRIPTION
**Pull request by robertlemke**
This change introduces two new options for the ``node:repair`` command
which allows for selective execution of ``node:repair`` checks.

The ``--skip`` option accepts one or more check names (identifiers) which
should be skipped.

If the ``--only`` option is used, only the the checks which are specified
in ``--only`` will be executed.

The identifier for each check can be looked up in the ``node:repair`` help
screen. If multiple check identifiers are specified, they need to be
separated by commas.

### CODE REVIEW

**Comment by robertlemke** [comment]
I manually tested various combinations of --skip and --only with the different check identifiers.

**Comment by aertmann** [comment]
nice addition, remember we considered it previously.. looks good by reading

this thing really is becoming a swiss army knife 😃

**Comment by kitsunet** [comment]
Mmm, now the the two Plugin `invokeSubCommand` signatures are no longer in line with the Interface, which should probably have been adapted as well making this a breaking change. Should have gone only to master with a deprecation and then the interface change in the next major... But well \o/ don't really feel like reverting it.

**Comment by aertmann** [comment]
@kitsunet good catch!

how does it even work when it differs from the interface?

**Comment by kitsunet** [comment]
as long as it overlaps and the additonal agruments are optional that's fine from PHPs point of view.

**Comment by aertmann** [comment]
@robertlemke: will you take care of a interface change PR for master with the `!!! Next major` label?

**Comment by bwaidelich** [comment]
> will you take care of a interface change PR for master with the !!! Next major label?

and *swooooosh* the ticket was there: #2279 :)

**Pull request merged**
