### PR TITLE
[BUGFIX] Set dimension to array() instead of null

### PR DESCRIPTION
**Pull request by michaelgerdemann**
The dimensions have to be an Array instead of null.

Fixes: NEOS-1697

### CODE REVIEW

**Comment by dfeyer** [comment]
:+1: Make sense and good catch we need to be more strict when something need to be an array, we need to avoid returning null, it push a lots of responsability to the other part of the code (is_array, !== null, ...) and it's a big source of bugs

Did you need to push this in a lower branch ?

**Comment by michaelgerdemann** [comment]
No, this utility class exists only in master.

**Comment by lsascha** [comment]
can confirm that this fixes the error i had when i updated a page to the latest dev-master version.

**Comment by kitsunet** [comment]
:+1:

**Pull request merged**
