### PR TITLE
TASK: Adjust requestPattern settings to new syntax

### PR DESCRIPTION
**Pull request by bwaidelich**
Adjusts the ``requestPattern`` configuration to the new
syntax introduced with https://github.com/neos/flow-development-collection/pull/130

Related: FLOW-412

### CODE REVIEW

**Comment by kitsunet** [comment]
Just rerunning the tests now that the flow PR is merged. @bwaidelich how will that behave if people change the controllerObjectName pattern in their projects? Will that nicely merge together?

**Comment by kitsunet** [comment]
Question still stands. Merging for now though.

**Comment by bwaidelich** [comment]
@kitsunet sorry for the late response. If you changed the Neos controllerObjectName in your package (for example) and apply this very change, you'll end up with four entries like:
```yaml
requestPatterns:
  controllerObjectName: 'Your\Changed\Pattern|TYPO3\Neos\[...]'
  'TYPO3.Neos:backendControllers':
    pattern: 'ControllerObjectName'
    // ...
  'TYPO3.Neos:serviceControllers':
    pattern: 'ControllerObjectName'
    // ...
  'TYPO3.Neos:mediaControllers':
    pattern: 'ControllerObjectName'
    // ...
```
If you ran the core migration provided with #130 it would be changed to sth like:
```yaml
requestPatterns:
  'Your.Package:ControllerObjectName':
    pattern: 'ControllerObjectName'
    // ...
  'TYPO3.Neos:backendControllers':
    pattern: 'ControllerObjectName'
    // ...
  'TYPO3.Neos:serviceControllers':
    pattern: 'ControllerObjectName'
    // ...
  'TYPO3.Neos:mediaControllers':
    pattern: 'ControllerObjectName'
    // ...
```

both of which should just work fine because all patterns of the same type will be `OR`ed together..
It might be possible that there are edge cases I didn't consider though, so hopefully people test this in their applications

**Comment by kitsunet** [comment]
Yep that's cool! I was just not sure if the first example would merge :)

**Pull request merged**
