### PR TITLE
FEATURE: Allow route resolving of disabled nodes

### PR DESCRIPTION
**Pull request by dlubitz**
Adds the ability to allow route resolving of disabled nodes.

This is needed for the redirect handling, to create URLs for given nodes, even if they are disabled at the moment.

### CODE REVIEW

**Comment by bwaidelich** [comment]
As written on [Slack](https://neos-project.slack.com/archives/C3MCBK6S2/p1687268350794019?thread_ts=1686673092.414629&cid=C3MCBK6S2):

> I struggle to extend our core API for a feature that I don't even [stand behind](https://discuss.neos.io/t/discuss-redirects-for-hidden-nodes/6331/10)

> My personal short term goal would be to not create redirects for disabled nodes for now

> adding  a new global request parameter that allows routing for disabled nodes could be a pandoras box.
> e.g. we were thinking about hard constraints for URIs (globally avoid duplicates at any time etc) and this change
> would make that more complex – for example if you want to reuse a URI that was used by a disabled node

**Comment by mhsdesign** [comment]
Hmm the suggestion with route Paramus looks a bit odd (due to this odd feature/escape hatch) 

I would rather have some low level internal resolver which doesn’t care about disabled and use this in your place directly? Wouldn’t this work?

**Comment by dlubitz** [comment]
Could you please explain "low level internal resolver"? ATM everything is bound to the `EventSourcedFrontendNodeRoutePartHandler` an not reusable. Only way might be to move this out. But TBH I don't know if this will work, as there might some magic in the other RoutePartHandler as well.

**Comment by bwaidelich** [comment]
> Could you please explain "low level internal resolver"?

I guess, this is about the same topic that we talked about before:
Extracting parts of the resolving logic from the `FrontendNodeRoutePartHandler` such that it can be used in other places (and allows for hooking into the mechanism in order to extend it)

But after thinking about it (once again) I think this is a dangerous path to follow.. IMO there should be only a single way to build and resolve URIs and either we support routing to disabled nodes or not

**Comment by dlubitz** [comment]
Closed in favor of https://github.com/neos/neos-development-collection/pull/4363

**Pull request closed without merging**
