### PR TITLE
BUGFIX: Inline TransientNodeCache

### PR DESCRIPTION
**Pull request by bwaidelich**
Turns the `TransientNodeCache` into a static runtime cache of the
`NodePrivilegeContext` and fixing support for null pointers with that.

Background:

`TransientNodeCache::cache()` had a non-nullable return type which
led to exceptions if no corresponding node was found.
Instead of just fixing the type hint this change suggests to inline the
logic at the same time since it is only used by one class so far.

Related: #2301

### CODE REVIEW

**Comment by kitsunet** [comment]
Actually see https://github.com/neos/neos-development-collection/pull/2302#issuecomment-444091719 and after for why it was changed ;) So I oppose this on the same grounds 😆

**Comment by bwaidelich** [comment]
> So I oppose this on the same grounds

Fair enough, although I don't agree that injecting a runtime cache is any better to be honest. But your call :)

**Comment by kitsunet** [comment]
And that is why I wanted to just fix the bug first before starting a  discussion about improvements... @kdambekalns why did you delete the other one :(

**Comment by kitsunet** [comment]
I don't know which is better, both are not really likeable in my book. I find static harder to deal with, garbage collection will never be able to remove this stuff like that.

**Comment by bwaidelich** [comment]
Closing in favor of #3097

**Pull request closed without merging**
