### PR TITLE
BUGFIX: Failing parsing of inline Fluid viewhelper array arguments

### PR DESCRIPTION
**Pull request by radmiraal**
The parsing of subarrays in the inline viewhelper syntax of Fluid fails
on specific system setups. This change adds additional quoting to prevent
the issue from occuring.

This is a workaround but in most cases leads to more readable / understandable
code.

See: https://github.com/neos/neos-development-collection/issues/2776

**What I did**

**How I did it**

**How to verify it**

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)

### CODE REVIEW

**Comment by radmiraal** [comment]
I now only touched all occurences of an `arguments: {`string or places where we actually confirmed the error occurred... Not sure if there're other array arguments which I missed by grepping the code

**Comment by radmiraal** [comment]
and: still meant as WIP / discussion source imho

**Comment by albe** [comment]
I'd argue about the "more readable" claim ;), but IMO that is irrelevant in the light of not working on some specific systems (OS/PHP versions). So I'm all for fixing this here and now and looking at how to solve the core issue downstream in Fluid (https://github.com/TYPO3/Fluid/issues/449)

**Comment by dlubitz** [comment]
It seems, that 
`arguments: {0: assetProxy.label}', package: 'Neos.Media.Browser')}` != `arguments: '{0: assetProxy.label}', package: 'Neos.Media.Browser')}`

See the tests I added to fluid: 
* Non-Quoted: https://github.com/dlubitz/Fluid/commit/63f3d7fa794ba008796dd38a4b3020db0ed4e75f#diff-1dd205376bc362161e9427170328b8c1R885-R894
* Quoted: https://github.com/dlubitz/Fluid/commit/63f3d7fa794ba008796dd38a4b3020db0ed4e75f#diff-1dd205376bc362161e9427170328b8c1R907-R914

But for some reason it works anyways for the translation view helper in Neos. I guess it's because of the name `arguments` and get merged somehow internally.

**Comment by dlubitz** [comment]
Possible solution PR in Fluid:
https://github.com/TYPO3/Fluid/pull/506

**Pull request closed without merging**
