### PR TITLE
BUGFIX: Missing styling in backend modules

### PR DESCRIPTION
**Pull request by SoulCover**
When using minified resources.

### CODE REVIEW

**Comment by kitsunet** [comment]
Sounds about right! :+1:

**Comment by kitsunet** [comment]
Would merge tomorrow if no one objects.

**Comment by aertmann** [comment]
crap, happened during upmerge.. even tested it, but apparently in a wrong way on 1.2 since it's not a problem until 2.0 :/

**Comment by ryzy** [comment]
Just spotted it in 2.1.4. Then upgraded to 2.1.5. Unfortunately, the issue is still present, styles are only present in `Content` module, in the other modules they are missing.

Reverting to 2.1.3 makes it working again. Cleared all the caches etc after upgrade to 2.1.5 of course, didn't help.

Anyone can confirm that the issue is still there? Or it's just my setup?

**Comment by ryzy** [comment]
Update: sorry, I was too quick in reporting this.
**The issue is fixed in 2.1.5**.

Had too many tabs in the browser and mixed things up - silly me.

**Pull request merged**
