### PR TITLE
FEATURE: Lazy loading images

### PR DESCRIPTION
**Pull request by jonnitto**
This will solve issue #3084

### CODE REVIEW

**Review by Sebobo — APPROVED** [review]
Looks good by reading.

Is there any negative side effect we have to keep in mind?

**Comment by jonnitto** [comment]
@Sebobo Do you have an idea why the test fail?

**Comment by Sebobo** [comment]
@jonnitto yes Flow was broken yesterday.

**Comment by mficzel** [comment]
+1 for adding the attribute but i am not convinced that adding `lazy` as default is a good idea. Totally agree to make this configurable but for images that are immediately visible i would prefer `eager loading. Making all images lazy by default seems a bit too opinionated for Neos. Especially since it can be done by integrators easily by overrding the dafaulrs in the ImageTag prototype.

**Comment by jonnitto** [comment]
The idea behind to make this `lazy` per default: Most of the images are below the fold and many other CMS use this also for marketing: Lazy loading images per default…

**Comment by mficzel** [comment]
Hmm, makes sense marketing wise but i am not sure there is a real marketing difference between "Lazy loading images per default" and "Support for image lazy loading". The second would allow us to choose the default only by technical reasons.

**Comment by Sebobo** [comment]
The docs say on the one hand that it only affects `off-screen` images, but also
```
The load event fires when the eagerly-loaded content has all been loaded; at that time, it's entirely possible (or even likely) that there may be lazily-loaded images that are within the visual viewport that haven't yet loaded.
```
Therefore the loading order of a site could change through this. But as each browser can decide through this attribute how it's best I would say that most sites would simply profit from the change and disabling or changing it would be easy enough.
If we don't enable it by default it would stay disabled for many sites as frontend performance regarding images is often ignored.

**Comment by mficzel** [comment]
I am totally fine if we come to the conclusion that this is a safe default and only wanted to avoid setting this default without reflection.

**Pull request merged**
