### PR TITLE
Fix typo in documentation

### PR DESCRIPTION
**Pull request by hasannawaz**
Fixed a typo in documentation in the User Settings document.

Can we verified using : https://neos.readthedocs.io/en/stable/UserGuide/UserSettings.html

### CODE REVIEW

**Comment by bwaidelich** [comment]
Hi @hasannawaz,
Thanks a lot for your contribution!
According to our [roadmap](https://www.neos.io/download-and-extend/release-process.html) the lowest supported version for regular updates is Neos 2.3 LTS and as this typo already existed for this version, `2.3` should be the target branch for this PR (you should be able to change the base branch by hitting `Edit` above)

**Comment by kitsunet** [comment]
:D Changing base branch down is never a good idea, because it tries to apply all the other chnages to the lower branch... Only way is to redo it for 2.3

**Comment by hasannawaz** [comment]
Ohkay... ill create a PR no worries.

**Comment by bwaidelich** [comment]
Oops, hang on: 2.3 is the lowest supported branch, but the UserSettings docs only exist since `3.1` apparently

**Comment by hasannawaz** [comment]
Should i re-open PR then @bwaidelich ?

**Comment by bwaidelich** [comment]
Nah, swapping the major version created a mess apparently.. Creating a new PR against 3.1 is probably easier

**Comment by hasannawaz** [comment]
Ok 👍

**Pull request closed without merging**
