### PR TITLE
TASK: Workspace review module respects datetime properties

### PR DESCRIPTION
**Pull request by johannessteu**
Workspace review module will show changes for node properties of type DateTime.

NEOS-1771 #close

### CODE REVIEW

**Comment by kdambekalns** [comment]
:+1: by reading

**Comment by kitsunet** [comment]
:+1: by reading

**Comment by dfeyer** [comment]
:+1:

**Comment by kitsunet** [comment]
I will merge this now but I suggest to add the case of changing from no value to value and vice versa, that currently will not be shown which is sad. Needs a bit more logic on the template but I think it can be easily added later.

**Comment by johannessteu** [comment]
I'll add a ticket @kitsunet in Jira and if i find some time i'll take care of that!

**Pull request merged**
