### PR TITLE
FEATURE: Sort direction options in media browser

### PR DESCRIPTION
**Pull request by johannessteu**
More flexible sorting in the media browser. The sorting is now split in sort by and sort direction to sort the asset list independently.

NEOS-1765 #close

### CODE REVIEW

**Comment by johannessteu** [comment]
This is a rework of #385 with some suggested changes.
Right now it looks like this:
![Implementation]
(http://g.recordit.co/dtnV4d1aPh.gif)

**Comment by johannessteu** [comment]
Any ideas for icons in the dropdown? Didn't really find icons that would only match ASC/DESC or filename/last modified

**Comment by aertmann** [comment]
Hey @johannessteu pushed a PR to your branch https://github.com/johannessteu/neos-development-collection/pull/1

Fixed some minor issues, improved the icon stuff and simplified the table header sorting like it's done in OneDrive and Goole Drive, since I find that being a better solution and less cluttered..

**Comment by aertmann** [comment]
good to go from my point of view with that PR merged

**Pull request merged**
