### PR TITLE
BUGFIX: Handle Fusion namespace in Renderer object type property

### PR DESCRIPTION
**Pull request by dfeyer**
Without this change you need to use the fully qualified object type in the type property of the Renderer Fusion object (Renderer, Matcher) even if you have a namespace configured. 

This change add a central service to handle Fusion namespace and update the Renderer implementation to use this service.

### CODE REVIEW

**Comment by dfeyer** [comment]
This one should break the test, but first I want other opinions on the implementation.

**Comment by kdambekalns** [comment]
Now, that's an old change… :) Names look good now. But the test failures need to be addressed!

**Comment by kitsunet** [comment]
I still like this change but I assume it needs some adaptions to the latest namespace changes!?

**Comment by kitsunet** [comment]
Ok, I have re thought about this and I really like the namespace resolver, that makes perfect sense to introduce. But having namespace support in the type property of the Render Fusion object is just weird. You essentially have to give it a string. It's as if PHP would start to expand namespaces in strings if the the string is used in a place where you need to give the name of a class?
So we basically would want to replicate PHPs `::class` behavior

**Pull request closed without merging**
