### PR TITLE
TASK: cleanup (Asset usage) node address

### PR DESCRIPTION
**Pull request by mhsdesign**
subtask of https://github.com/neos/neos-development-collection/issues/4341

The naming of the internal asset usage `NodeAdress` was adjusted - so people more likely import the right one.

**Upgrade instructions**

**Review instructions**

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Comment by dlubitz** [comment]
Hehe, you noticed it yourself ;)

**Review by dlubitz — APPROVED** [review]
I don't think this is necessary, because ... thats what namespaces for. But I'm fine with it if it makes your life easier 😄

**Comment by mhsdesign** [comment]
Yeah i just dont want to answer those questions in slack 😂  this thing is used like 2 time vs the other one will be public api.

**Review by bwaidelich — APPROVED** [review]
What Denny said..

**Pull request merged**
