### PR TITLE
9.0 FEATURE: Allow route resolving of disabled nodes

### PR DESCRIPTION
**Pull request by dlubitz**
This enables the same behavior of route resolving as before Neos 9.

This allows to "resolve" a route of a disabled node and build an URI for it. This doesn't make the node accessible, as long as the route "matching" takes care of it.

Needed for the redirect handling, to create URLs for given nodes, even if they are disabled at the moment.
See discuss post: https://discuss.neos.io/t/discuss-redirects-for-hidden-nodes/6331
Previous draft: https://github.com/neos/neos-development-collection/pull/4334

### CODE REVIEW

**Review by bwaidelich — COMMENTED** [review]
Thanks! <3
Could you add an inline comment similar to the one in Neos < 9 explaining that and why we resolve disabled nodes?

**Comment by dlubitz** [comment]
Additional to the method doc block?

**Review by bwaidelich — APPROVED** [review]
Ah sorry, I looked at this from my mobile phone and missed the doc comment!

**Review by mhsdesign — APPROVED** [review]
Conceptional i approve ;)

Edit: do we have tests that the route matching doesnt work for disabled nodes? This behaviour should be untouched.

Edit2: yes exactly see test

**Review by bwaidelich — APPROVED** [review]

**Comment by bwaidelich** [comment]
Dang, this one had a bigger blast radius than I expected since now `ConvertUris` behaves differently (see #5926).
I still think, that this change makes sense. But maybe now we should respect disabled nodes in the `NodeUriBuilder` instead!?

**Pull request merged**
