### PR TITLE
FEATURE: Add external rel attribute to link in ConvertUrisImplementation

### LINKED ISSUE #3543: Feature: Adding 'external' to Links
For external Links in a menu I would like to automatically add rel="external noopener" to every a-tag to an external website. 

This is to help search engines know that the link is to an external page.

For further information see https://www.w3schools.com/tags/att_a_rel.asp

### PR DESCRIPTION
**Pull request by pKallert**
closes #3543 

**What I did**
I added the posibility of adding 'rel="external"' to external links,  when using the ConvertUrisImplementation 

**How I did it**
Just like the already existing attribute setNoOpener, I added the option setExternal. 

I was wondering about making this more open by allowing a string/array to be set here, since rel-attributes can contain a lot of different attributes. But then again, this could be misused. 

**How to verify it**
When using the ConvertUrisImplementation in fusion, the option setExternal can be used to add rel="external" to a link. 

`
   @class = 'Neos\\Neos\\Fusion\\ConvertUrisImplementation'
    value = ${value}
    node = ${node}
    externalLinkTarget = '_blank'
    resourceLinkTarget = '_blank'
    absolute = false
    forceConversion = false
    setNoOpener = true
    setExternal = true
`

**Checklist**

- [x] Code follows the PSR-2 coding style
- [x] Tests have been created, run and adjusted as needed
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)

### CODE REVIEW

**Review by markusguenther — APPROVED** [review]
Thanks @pKallert, for this improvement

**Review by jonnitto — CHANGES_REQUESTED** [review]
This should also be documented at [NeosFusionReference.rst](https://github.com/neos/neos-development-collection/blob/master/Neos.Neos/Documentation/References/NeosFusionReference.rst#neosneosconverturis)

**Review by jonnitto — COMMENTED** [review]
Tested it and it works. I missed one thing: This new behavior should also be covered by Neos.Neos/Tests/Unit/Fusion/ConvertUrisImplementationTest.php

**Comment by markusguenther** [comment]
I adjusted the UnitTests... also found an issue with the `disablingSetNoOpenerWorks` test. The test never worked, as the `setNoOpener` parameter needs to be an external link and the test did not use the `replaceLinkTargets` and therefore you could setNoOpener to true or false it ends up in a link without the rel attribute.

**Comment by markusguenther** [comment]
@jonnitto maybe we should fix the broken test for setNoOpener for 5.3 as well...

**Comment by markusguenther** [comment]
The test is now fixed in the extra PR: https://github.com/neos/neos-development-collection/pull/3606

**Pull request merged**
