### PR TITLE
BUGFIX: Assign original asset collections to variant

### LINKED ISSUE #3560: ImageVariants have no asset collection assigned
### Description

When an `ImageVariant` is created by means of cropping in the Neos UI inspector, it is not assigned to an `AssetCollection`. This leads to issues if access to assets not being in an asset collection is limited.

### Steps to Reproduce

1. Block access to assets without an assigned asset collection
2. Have an asset in an asset collection
3. Create a crop of that asset

#### Expected behavior

The crop is created and assigned to the node property, becoming visible in the inspector (and the content, once applied.)

#### Actual behavior

The crop is in fact created, but since it is not accessible (due to step 1 above), it's metadata cannot be fetched (an error notice is shown) and the property will in fact be emptied.

### Affected Versions

Neos: 5.3+

### PR DESCRIPTION
**Pull request by kdambekalns**
Fixes #3560

### CODE REVIEW

**Comment by bwaidelich** [comment]
@kdambekalns is this still marked as draft because you are working on a test case? *g

**Comment by kdambekalns** [comment]
> @kdambekalns is this still marked as draft because you are working on a test case? *g

No, because… see linked issue. ;)

**Comment by bwaidelich** [comment]
Ah right.. good question..

**Comment by kdambekalns** [comment]
Conclusion to above mentioned question: makes sense to keep the collections in sync…

**Comment by ru3fu5z** [comment]
Will this be fixed soon? https://github.com/neos/neos-development-collection/issues/3560#issuecomment-1415819112

**Review by fcool — APPROVED** [review]
This looks definetly ripe enough for merging

**Review by mhsdesign — DISMISSED** [review]
The style ci stuff imo doesnt belong into this specific bugfix branch (and might cause trouble, i just have an ungood feeling ^^). I would like 4559130edf2a58771526596273bd974873e33789 to be reverted.

@kdambekalns can you give me a 👍 if you agree? then id go ahead and do so.

**Comment by kdambekalns** [comment]
> The style ci stuff imo doesnt belong into this specific bugfix branch (and might cause trouble, i just have an ungood feeling ^^)

- Might belong elsewhere, but if we always ignore those, they will never be fixed.
- What kind of trouble do you expect?

> @kdambekalns can you give me a 👍 if you agree? then id go ahead and do so.

I disagree, that's a "pure whitespace" change, I see no need to revert that.

**Comment by mhsdesign** [comment]
> What kind of trouble do you expect?

The style ci stuff was done some time ago Apr 29, and might be outdated - also if every bugfix branch does it its just odd ^^.

I also thought our style ci was wrong configured as it only complains now (the code wasnt touched in years)

**Comment by kdambekalns** [comment]
> also if every bugfix branch does it its just odd ^^.

No. You open a PR, the checks fail, you fix them. Nothing odd about that, IMHO.

> I also thought our style ci was wrong configured as it only complains now (the code wasnt touched in years)

That is a "known issue" of some sort. But either way, the complaints are valid.

**Comment by kdambekalns** [comment]
Can't say I am a fan of force-pushing over other people's work without previous agreement. Especially when it's because something is disliked. 🙁

Thanks for housekeeping, still.

**Comment by mhsdesign** [comment]
Sorry not especially nice of me

**Comment by ru3fu5z** [comment]
Any news on this PR? @kdambekalns @mhsdesign

**Comment by kdambekalns** [comment]
Waiting for reviews… sadly.

**Review by kitsunet — APPROVED** [review]
I guess works for me.

**Pull request merged**
