### PR TITLE
TASK: Use node label in inspector breadcrumb

### PR DESCRIPTION
**Pull request by aertmann**
Instead of using the node type name the label of the node is used instead. This helps avoid confusing the breadcrumb in the inspector from a node type selector.

Additionally the label is now updated using the server side rendered label in the inspector breadcrumb, context structure tree and node tree.

NEOS-1141 #comment replaced the node type name with the node label, which should help a little

### CODE REVIEW

**Comment by aertmann** [comment]
http://recordit.co/qZKSKpcGNy
http://g.recordit.co/qZKSKpcGNy.gif
image
image

Since there's quite some clean up in this change, review the commit individually to make it easier.

**Comment by gerhard-boden** [comment]
:+1:Tested and can confirm it works nicely!  (but did not review the code)

**Comment by johannessteu** [comment]
Just like @gerhard-boden , tested locally, works perfect but didn't looked at the code

**Comment by aertmann** [comment]
\o/ thanks for the reviews

**Comment by gerhard-boden** [comment]
small improvement:
Convert line break to space
image

**Comment by aertmann** [comment]
@gerhard-boden: feel free to push a PR for that, needs to be done in https://github.com/neos/neos-development-collection/blob/master/TYPO3.Neos/Configuration/NodeTypes.yaml#L3

**Pull request merged**
