### PR TITLE
BUGFIX: Newly created node not selected

### LINKED ISSUE #4280: BUG: newly created node is not selected
### Description
When creating a new content node on a page, the new node used to get automatically selected and therefore also scrolled into view in previous Neos versions. In Neos 9, when a new node is created, the previously selected node stays selected and therefore the new node is not scrolled into view. 

### Steps to Reproduce

1. Click on the main content collection
2. Click the plus sign to create a new node
3. Choose any content module and create it

#### Expected behavior

After executing the steps described above, the newly created node should be selected/focused

#### Actual behavior

After executing the steps described, the main content collection is still selected/focused

### Affected Versions

Neos: 9.0

UI: 9.0.x-dev

### PR DESCRIPTION
**Pull request by skurfuerst**
Resolves: https://github.com/neos/neos-development-collection/issues/4280
Related: https://github.com/neos/neos-ui/pull/2927
Related: https://github.com/neos/neos-development-collection/pull/3618

### CODE REVIEW

**Comment by skurfuerst** [comment]
best to review this commitwise

**Comment by ahaeslich** [comment]
Interesting case which poped up after your changes: 

Using `Neos.Neos:PrimaryContent` to render the main content collection will throw this error: 

`Neos\Neos\Fusion\Helper\NodeHelper_Original::nearestContentCollection(): Argument #2 ($nodePath) must be of type string, null given`

This is for example used in the [Neos.Demo](https://github.com/neos/Neos.Demo/blob/9.0/NodeTypes/Document/Page/Page.fusion).

**Comment by skurfuerst** [comment]
@ahaeslich hm, where does this happen? for me the demo site seems to run just fine. So what did you try to do? :)

**Comment by ahaeslich** [comment]
> @ahaeslich hm, where does this happen? for me the demo site seems to run just fine. So what did you try to do? :)

Just trying to add a new content element to the page. Sorry, forgot to mention it.

**Comment by ahaeslich** [comment]
To document our discussions about the error:

The error occures if the user adds a content element in a `Neos.Neos:ContentCollection` which uses `Neos.Neos:PrimaryContent` to render the collection. In this case the initial `change` request will throw

image

Example code from Neos.Demo:

- [yaml file](https://github.com/neos/Neos.Demo/blob/1f0909c1d89d739ff6146d8d1d560fecc7668ebc/NodeTypes/Document/Page/Page.yaml) 
- [fusion code](https://github.com/neos/Neos.Demo/blob/1f0909c1d89d739ff6146d8d1d560fecc7668ebc/NodeTypes/Document/Page/Page.fusion)

Looking into `Neos\Neos\Fusion\Helper\NodeHelper::nearestContentCollection` it seems that this behaviour has been there for ages (tested e.g. in Neos 8.3) but didn't really matter until the type declaration was introduced in https://github.com/neos/neos-development-collection/commit/3340c93f1969b7ee8720284cb4e72753403b8e77.

Slack-Discussion: https://neos-project.slack.com/archives/C3MCBK6S2/p1683895922035389

**Comment by bwaidelich** [comment]
The change looks good to me, but I can't really judge because I don't know the UI internals.
Is there anything I can help with, @ahaeslich ?

**Comment by skurfuerst** [comment]
I am confident this could / can be merged as is :) 

All the best!

**Comment by ahaeslich** [comment]
Yes we can merge this. We can deal with `Neos.Neos:PrimaryContent` in another MR.

**Review by ahaeslich — APPROVED** [review]

**Review by bwaidelich — APPROVED** [review]
ok then, thanks!

**Pull request merged**
