### PR TITLE
TASK: Refactor ImageAdjustments to be more flexible

### PR DESCRIPTION
**Pull request by nezaniel**
Refactor ImageAdjustments to use a more flexible, array-based configuration format instead of static properties.

### CODE REVIEW

**Comment by kitsunet** [comment]
Just to prevent accidental merging 👎 because interface is changed. Must go into next major instead.

**Comment by dfeyer** [comment]
Nice one and thanks, it make sense, but as @kitsunet say earlier not before the next major version.

**Comment by nezaniel** [comment]
Thanks for the review, will adapt to not breaking the api.

**Comment by dfeyer** [comment]
@nezaniel I think it's not possible to do this change correctly without being breaking. The next major version is for december, so it's not too fare away. Doing this change without modification in the interface will be useless ... as the adjustements will not respect the base interface.

**Comment by nezaniel** [comment]
That's what I thought too at first, but actually introducing a new ConfigurationBasedAdjustmentInterface seems like a nice solution as it not only not breaks the API but also gives more freedom to developers who don't like / don't want to adapt to the approach. objections?

**Comment by dfeyer** [comment]
Not sure, I think consistency is always the way to go ... so having multiple way to extend a single point sound always a bit bad to me. Why ?

- Maintenance, we need to test way more scenario
- Documentation, more complexity, more documentation
- UX (developer), do i need this way or the other one ? it's always a bad question with no correct answer.

Maybe @aertmann or @kitsunet as some more comments ?

And @nezaniel sorry to block you with all those discussion, but if we don't plan this kind of extension point, we end up in the current situation (try to solve badly planned stuff), and if we can avoid this process multiple time it's will help us a lots.

**Comment by nezaniel** [comment]
@dfeyer Nevermind, I prefer stuff done right, too. And I see your point, a decision has to be made whether there should be just one convenient extension point using the configuration approach or an additional, more abstract extension point should be available too.

However, I'd like to add that an AdjustmentInterface including the configuration related methods might not be very useful as I am convinced the AbstractAdjustment with the methods already implemented is by far the better extension point. The interface then could be scrapped altogether. But that's just my two cents :)

**Comment by dfeyer** [comment]
Let's work on this one for the next major version.

**Comment by mficzel** [comment]
This pr needs a rebase

**Comment by robertlemke** [comment]
Since this patch isn't ready yet, I'll remove the Next major label for now.

**Comment by jonnitto** [comment]
@nezaniel Any progress/status on this?

**Pull request closed without merging**
