### PR TITLE
[BUGFIX] Fixes correct getting of options for StringLengthValidator (JS)

### PR DESCRIPTION
**Pull request by dlubitz**
Fixed the second parameter (radix) of parseInt to get the correct configured max and min. Was falsely changed during translation of JS messages.

Related: 5723c22561591d1ada93ee7cef5b85d30c47b9a2
Fixes: NEOS-1636

### CODE REVIEW

**Comment by aertmann** [comment]
also why not change it back to what it was before? also seems like that commit broke other things actually

**Comment by aertmann** [comment]
@skurfuerst: can you tell why those unrelated changes were merged as part of https://review.typo3.org/#/c/41215/2/Resources/Public/JavaScript/Shared/Validation/StringLengthValidator.js?

**Comment by aertmann** [comment]
@dlubitz: good job finding and fixing it btw.

**Comment by skurfuerst** [comment]
@aertmann that was probably an error...

**Comment by skurfuerst** [comment]
:+1: by reading!

**Pull request merged**
