### PR TITLE
BUGFIX: Return ``null`` if image property comes back empty

### PR DESCRIPTION
**Pull request by gerhard-boden**
Images removed within the backend no longer return an empty string instead of ``null``. This also fixes regression 2a1c89c7a4ee43c934d9e154fc9164cefc736a06 which returns ``null`` even if a default value like empty string or false is set.

### CODE REVIEW

**Comment by gerhard-boden** [comment]
Maybe this can be solved by property mapping as well, but in the interest of time this seems to be the fastest and safest solution we have.

The whole method should be refactored at some point, and maybe we should think about splitting up the class (1894 lines)

**Comment by robertlemke** [comment]
@kitsunet fine with that solution?

**Comment by gerhard-boden** [comment]
Maybe we should add an fixme comment that warns people not to add more conditions to this method, nur to refactor the logic, so this will not become a huge `if` forest

**Comment by robertlemke** [comment]
@gerhard-boden can you retarget this to 3.0 instead of master?

**Comment by gerhard-boden** [comment]
@robertlemke done

**Pull request merged**
