### PR TITLE
FEATURE: Add optional node type inheritance to CreateNodePrivilege

### LINKED ISSUE #3136: CreateNodePrivilege must check parent NodeTypes
If you define a matcher like `createdNodeIsOfType("Some.Package:Mixin")`, the creation of a node using this mixin should match.
Currently, only the final NodeType is checked (ignoring inheritance). Imho here we should do the same inheritance checks as everywhere else.

### PR DESCRIPTION
**Pull request by ComiR**
This is a rebased version of #2166 targeting `master`.

> If you define a matcher like createdNodeIsOfType("Some.Package:Mixin"), the creation of a node using this mixin should match.
> Currently only the final NodeType is checked (ignoring inheritance). Imho here we should do the same inheritance checks as everywhere else.

I [still](https://github.com/neos/neos-development-collection/pull/2166#issuecomment-497291831) suggest looking into the privilege system, since there are some inconsistencies.

Resolves: #3136

### CODE REVIEW

**Comment by jonnitto** [comment]
This will fix #3136

**Comment by kdambekalns** [comment]
Close/re-open to trigger new Travis integration

**Review by kdambekalns — COMMENTED** [review]
- If I read the code correctly, this only respects the first level of sub-nodetypes, it is not recursive. Is that intended or an oversight?
- No documentation has been adjusted and/or added, is that correct?

**Comment by albe** [comment]
Can someone do a rebase of this?

**Comment by mhsdesign** [comment]
The problem is already fixed via https://github.com/neos/neos-development-collection/issues/2960 :)

**Pull request closed without merging**
