### PR TITLE
BUGFIX: add dimensionshash migration to postgres

### PR DESCRIPTION
**Pull request by Jonathan2022Bausch**
Regression https://github.com/neos/neos-development-collection/pull/3279

We need to generate add dimensions hash to node event model in order to be able to save new nodes as we do in MySQL: Neos.Neos/Migrations/Mysql/Version20210125134503.php

**Upgrade instructions**

Run ./flow doctrine:migrate

**Review instructions**

You want to make sure that the dimensions table has valid values. If not you might want to add a custom migration like this one:

```php
<?php
declare(strict_types=1);

namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

class Version20230727164559 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Correct null entries in event log caused by automated import';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('UPDATE neos_neos_eventlog_domain_model_event SET dimension = NULL WHERE dimension = :dimension AND dtype = :dtype;', ['dimension' => 'N;', 'dtype' => 'ttree_contentrepositoryimporter_event']);
    }

    public function down(Schema $schema): void
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('UPDATE neos_neos_eventlog_domain_model_event SET dimension = :dimension WHERE dimension IS NULL AND dtype = :dtype;', ['dimension' => 'N;', 'dtype' => 'ttree_contentrepositoryimporter_event']);
    }
}
```

**Checklist**

- [x] Code follows the PSR-2 coding style
- [x] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Comment by crydotsnake** [comment]
Hello,

Thanks for your contribution!

Is this bugfix related too 8.3? otherwise this should go in the 7.3 branch.

**Comment by Jonathan2022Bausch** [comment]
> Hello,
> 
> Thanks for your contribution!
> 
> Is this bugfix related too 8.3? otherwise this should go in the 7.3 branch.

I am currently developing with 8.3 but I am open to merge this into 7.3

**Comment by crydotsnake** [comment]
Hm. I believe something went wrong during the rebase. Can you fix this? Otherwise, you can create a new branch based on 7.3 and open a new pull request :)

**Comment by markusguenther** [comment]
Adjusted the PR and now it is based on Neos 7.3.
After your PR I also understand your comment in PR (https://github.com/neos/neos-development-collection/pull/3986) better.
I did not enable the history locally.

**Comment by markusguenther** [comment]
I was wrong and @andrehoffmann30 added the hash in Neos 8.3, and we just forgot the Postgres Migration. So will adjust that to 8.3 again.

**Comment by dlubitz** [comment]
Looks good to me! But we need to change it back to 8.3, as this was introduced for MySQL in 8.3 too.

**Review by markusguenther — APPROVED** [review]

**Comment by markusguenther** [comment]
We discussed that PR in our CR Weekly and agreed on merging that change. In Neos 9.0 the EventLog has been removed.

**Comment by markusguenther** [comment]
Thanks for Your contribution @Jonathan2022Bausch 🥇💙

**Comment by markusguenther** [comment]
Your first contribution has been released now 🥳

**Pull request merged**
