### PR TITLE
Feature: Add failing tests for workspace publish

### PR DESCRIPTION
**Pull request by pKallert**
I created a failing test for #4783 

Apparently, the problem here is the command PublishIndividualNodesFromWorkspace. This command is used by the Neos UI to publish simple changes. 

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Comment by mhsdesign** [comment]
Thanks for writing the test looks perfect :D

> Then the last command should have thrown an exception of type "BaseWorkspaceHasBeenModifiedInTheMeantime"

now we just have to fix this, which _should_ be fairly simple by adding a constraint check in the `handlePublishIndividualNodesFromWorkspace` no? Like checking that neither workspace nor baseWorkspace must be outdated.
That might be it.

**Comment by bwaidelich** [comment]
@pKallert wonderful, thank you!

> now we just have to fix this, which should be fairly simple by adding a constraint check in the handlePublishIndividualNodesFromWorkspace no?

A constraint check would probably be the first step. But there's still a risk for race conditions, so IMO we need https://github.com/neos/neos-development-collection/pull/4692 for this – or at least the part that replaces `ExpectedVersion::ANY()` with `ExpectedVersion::fromVersion($contentStreamVersion->unwrap())`

**Comment by nezaniel** [comment]
WorkspaceCommandHandler::handlePublishIndividualNodesFromWorkspace does an implicit rebase by forking a new content stream from the base workspace and then re-applying the commands, so we avoid ConcurrencyException by design. 
To test for actual concurrency handling, we introduced parallel tests (see composer test:parallel).

So I think we can close this, any objections?

**Comment by mhsdesign** [comment]
i first thought we could commit the newly added test but

> Publishing workspace with PublishIndividualNodesFromWorkspace not possible with outdated workspace

is not where we went for with https://github.com/neos/neos-development-collection/pull/5301 we now deliberately rebase event for `PublishWorkspace`.

(also the diff is wrong of this pr, the big test is not new but was copied around and wrongly merged)

**Pull request closed without merging**
