### PR TITLE
TASK: Cleanup of internal VIE usage in JS backend

### PR DESCRIPTION
**Pull request by aertmann**
This change removes a lot of the direct interaction with VIE and replaces it with the node model.
Additionally the VIE namespace is no longer used outside VIE so the configuration is removed.

### CODE REVIEW

**Comment by skurfuerst** [comment]
Hey Aske,

I just read over the change, and I really like what I have seen. So from my side, this is a :+1: by reading, although I think this change needs some more intense testing.

All the best,
Sebastian

**Comment by kdambekalns** [comment]
Hi @aertmann, how does this one relate to #186 - and would you rebase it to fix the conflicts?

**Comment by aertmann** [comment]
@kdambekalns it's not important for the release, so will probably rebase after feature freeze

**Comment by aertmann** [comment]
and it's basically just stuff I found while fixing #186

**Comment by kdambekalns** [comment]
:+1:

**Comment by kitsunet** [comment]
Looks good and seems to work fine. Just played with it a bit. :+1: but conflicts need to be solved before merging.

**Comment by aertmann** [comment]
rebased

**Comment by aertmann** [comment]
:+1: fixed StyleCI issue (unrelated to change)

**Comment by aertmann** [comment]
:+1: rebased

**Comment by aertmann** [comment]
included all of the changes in #416 instead

**Pull request closed without merging**
