### PR TITLE
BUGFIX: Extract "storage clients" into separate packages

### LINKED ISSUE #4684: BUG: `Required class "…\PostgresDbalClientInterface" could not be loaded …`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running Neos 9 from split packages the compile step fails, if there is no "storage adapter" installed:

`Required class "Neos\ContentGraph\PostgreSQLAdapter\Infrastructure\PostgresDbalClientInterface" could not be loaded properly for reflection from "Neos\ContentRepositoryRegistry\Infrastructure\PostgresDbalClient".`

### Expected Behavior

The dependencies make it clear I need (at least) one "storage adapter", and if I use one it is configured correctly "through itself".

### Steps To Reproduce

Require just `neos/neos` in version 9 and try to run `./flow flow:core:compile`

### Environment

```markdown
- Flow: 9.0.x
- Neos: 9.0.x
- PHP: 8.2.x
```

### Anything else?

A first naïve try to fix this was https://github.com/neos/neos-development-collection/pull/4259, which would have made sure the source package for that interface is available.

**But** it should be possible to install one or more of the "clients" as needed, so adding that dependency is a bad idea. Instead users must require the registry **and** one of the adapters.

@bwaidelich mentioned that the Behat tests should be untangled, too (see [Slack discussion](https://neos-project.slack.com/archives/C3MCBK6S2/p1677926252727149?thread_ts=1677924092.973169&cid=C3MCBK6S2))

### PR DESCRIPTION
**Pull request by kdambekalns**
Extract some part from `neos/contentrepositoryregistry` to separate packages, to avoid errors when not using the development collection (and thus not magically "having everything in place".)

Resolves #4684

**Review instructions**

1. When `neos/neos` in v9 is required (**from splits**, not when using the collection!), Composer must complain and tell you to install one of the client packages:
   ```
   - neos/contentrepositoryregistry 9.0.x-dev requires neos/contentrepositoryregistry-storageclient 9.0.x-dev -> could not be found in any version, but the following packages provide it:
     - neos/contentrepositoryregistry-doctrinedbalclient Doctrine DBAL client for the Neos Content Repository Registry
     - neos/contentrepositoryregistry-postgresdbalclient PostgreSQL-optimized Doctrine DBAL client for the Neos Content Repository Registry
     Consider requiring one of these to satisfy the neos/contentrepositoryregistry-storageclient requirement.
   ```
2. As soon as that is done, things (should) work "like before", since the clients itself (should) behave like before.
3. Flow should not complain about the Behat `BeforeScenario` hook, since `CRRegistrySubjectProvider` has been extracted to a separate package. In the development collection or when testing, things should still work.

**Checklist**

- [x] Code follows the PSR-2 coding style
- [x] Tests have been created, run and adjusted as needed
- [ ] ~The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)~
- [x] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [x] Reviewer - The first section explains the change briefly for change-logs
- [ ] ~Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions~

### CODE REVIEW

**Review by bwaidelich — APPROVED** [review]
Wonderful, thanks a lot!
I fail to see all the implications for this but the description sounds more than reasonable and I trust the Kambelkarsten!

**Review by kitsunet — APPROVED** [review]
Installation works for me, BUT I run into a behat issue unrelated to this change. neos/behat should require behat/behat in order to make everything work in split installations.

**Comment by kdambekalns** [comment]
> neos/behat should require behat/behat in order to make everything work in split installations.

Oh, indeed it should do that.

**Comment by kdambekalns** [comment]
I created the needed split repositories and will push a PR to adjust the neos/slicer configuration…

**Review by skurfuerst — COMMENTED** [review]
Awesome work 😊 thanks @kdambekalns

**Pull request merged**
