### PR TITLE
[TASK] Allow SelectBoxEditor sending data to DataSource

### PR DESCRIPTION
**Pull request by kitsunet**
This is a follow up to allow dependent SelectBoxes together with
the change that implements property listeners.

### CODE REVIEW

**Comment by kitsunet** [comment]
Note, this is a bit inconvenient. I would rather like to have #164 merged first and then rebase this one, but I wanted to add this already here. So please do not merge but instead merge #164 first.

**Comment by skurfuerst** [comment]
Hey,

I like the direction this is getting :)

Docs are still missing for the SelectBoxEditor.

All the best,
Sebastian

**Comment by kdambekalns** [comment]
Cherry-picked on top of #164

**Comment by kdambekalns** [comment]
The last three commits fix a number of issues.

**Comment by kdambekalns** [comment]
Regarding documentation see https://github.com/neos/neos-development-collection/pull/197 - based on this some additions are to be made.

**Comment by kdambekalns** [comment]
As soon as https://github.com/neos/neos-development-collection/pull/164 and https://github.com/neos/neos-development-collection/pull/197 are merged this can be rebased once more and should be ready then.

**Comment by robertlemke** [comment]
I (hopefully correctly) based this on current master after having merged #164

**Comment by kdambekalns** [comment]
Yes, rebased correctly. Looks good, :+1:

**Comment by kdambekalns** [comment]
@skurfuerst Fine with the documentation now?

**Comment by robertlemke** [comment]
:+1:

**Pull request merged**
