### PR TITLE
BUGFIX: Add mysql-index for the field `parentpath` in the `nodeData`-table

### PR DESCRIPTION
**Pull request by mficzel**
The find operation is currently very expensive because of an unoptimized LIKE statement.
This index will to optimize the performance for find operations especially in larger cr-instances

The size of the index is a compromise between space and an assumption of the normal length of the nodePath.

### CODE REVIEW

**Comment by aertmann** [comment]
missing a Postgres migration

**Comment by mficzel** [comment]
@aertmann  regarding postgres i cannot prepare that because i have no postgres here.

**Comment by kdambekalns** [comment]
I can take care of the PostgreSQL migration…

**Comment by mficzel** [comment]
@kdambekalns ... i added the annotation and regenerated the migration. The index length had to be inserted manually into the migration since the annotation does not support this.

**Comment by kdambekalns** [comment]
Thanks, will do PostgreSQL tomorrow.

**Comment by kdambekalns** [comment]
_Sigh_, so they added `options` in some later version.

**Comment by albe** [comment]
```
[Doctrine\DBAL\Migrations\MigrationException]                                                                                                                              
  Exception has been thrown in "beforeScenario" hook, defined in Flowpack\Behat\Tests\Behat\FlowContext::resetTestFixtures()                                                 

Migration class "TYPO3\Flow\Persistence\Doctrine\Migrations\Version20170328183557" was not found. Is it placed in "TYPO3\Flow\Persistence\Doctrine\Migrations" namespace? 
```

Uhh?

**Comment by kdambekalns** [comment]
Gah, that's what you deserve for creating a migration on a more current branch…

**Comment by albe** [comment]
Still not quite there :/

`SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "neos_contentrepository_domain_model_nodedata" does not exist`

Guess the table names also need adjustment

**Comment by kdambekalns** [comment]
F**k. Well. By now it would have been faster to bring the local setup down to 2.2 ton create the migration… _sigh_

**Comment by kitsunet** [comment]
Feels right to merge this as the one who first said "No, No, No" 😆

**Pull request merged**
