### PR TITLE
TASK: Apply migrations

### PR DESCRIPTION
**Pull request by kdambekalns**
Apply core migrations to (some) Neos dev collection packages.

### CODE REVIEW

**Review by jonnitto — APPROVED** [review]

**Review by markusguenther — APPROVED** [review]
Thanks for taking care ❤️

**Comment by kdambekalns** [comment]
Note: Not sure about the nodetype constraints changes, TBH… Is tht correct?

**Comment by mficzel** [comment]
The nodeType changes were done by https://github.com/neos/neos-development-collection/pull/3163 will have to look deeper wether the tests should be adjusted or wether the migration does something stupid. The applied changes look like i would expect them to be.

**Comment by mficzel** [comment]
Hmm somehow the migration affected the nodeTyoes Neos.Neos:Content and Neos.Neos:Document aswell wich is clearly not correct.

**Comment by kdambekalns** [comment]
Yep, as the tests say…

```
There were 2 failures:

1) Neos\ContentRepository\Tests\Functional\Domain\NodeConstraintsTest::movingNodeToWhereItsTypeIsDisallowedThrowsException
Failed asserting that exception of type "Neos\ContentRepository\Exception\NodeConstraintException" is thrown.

2) Neos\ContentRepository\Tests\Functional\Domain\NodeConstraintsTest::movingNodeToWhereItsSuperTypeIsDisallowedThrowsException
Failed asserting that exception of type "Neos\ContentRepository\Exception\NodeConstraintException" is thrown.
```

And Behat fails, too, see e.g. https://travis-ci.com/github/neos/neos-development-collection/jobs/439082250

**Comment by kdambekalns** [comment]
Removed the chanages to `Neos.Neos:Content` and `Neos.Neos:Document`, let's see.

**Comment by mficzel** [comment]
I would rather fix the migration. Looking at the code it should not have touched those types.

**Comment by kdambekalns** [comment]
> I would rather fix the migration

Then the migration would not have applied the change I removed, so the result is the same. And usually people do not apply that migration to Neos-maintained packages.

But, sure, by all means go ahead aand fix it! 🛠👷‍♂️👍

**Comment by kdambekalns** [comment]
Seems the adjustments to the testing nodetype setup are also wrong.

**Comment by mficzel** [comment]
Am on it. Probably makes sense to create a separate pr to fix the migration and apply it to the core packages.

**Review by daniellienert — APPROVED** [review]

**Comment by mficzel** [comment]
@kdambekalns found the problem in the migration https://github.com/neos/neos-development-collection/pull/3178. With this in place it will only apply formatting changes to the core nodetypes.

**Review by mficzel — APPROVED** [review]

**Review by mficzel — CHANGES_REQUESTED** [review]
sadly the modifications of the contentCollectionConstraintMigration hit way to many nodeTypes this #3178 fixes this and should be applied beforehand.

**Comment by kdambekalns** [comment]
@mficzel This should be ok, no changes at all. Oh, and… what about https://github.com/neos/Neos.Demo/commit/a5786932999a6367d801a7b4fb4df65115b48719 from earlier today?

**Review by mficzel — APPROVED** [review]

**Comment by mficzel** [comment]
@kdambekalns https://github.com/neos/Neos.Demo/commit/a5786932999a6367d801a7b4fb4df65115b48719 looks fine. That is what this migration was made for.

**Pull request merged**
