### PR TITLE
TASK: Lowercase node type label from history module labels

### PR DESCRIPTION
**Pull request by aertmann**

### CODE REVIEW

**Comment by aertmann** [comment]
image

**Comment by jonnitto** [comment]
What is about languages like German? There you would capitalize the label...

**Comment by aertmann** [comment]
hmm then I guess it's better to leave as is, not that important..

**Comment by aertmann** [comment]
thanks for the input

**Comment by bwaidelich** [comment]
good point, I didn't even think of German 👀

**Pull request closed without merging**
