### PR TITLE
BUGFIX: More precise selection of the DomNode with CSFR token

### PR DESCRIPTION
**Pull request by markusguenther**
To prevent issues with selecting the wrong CSFR Token in the DOM, we now have a more precise selection of the DomNode with the CSFR token.

fixes: #4822

**Review instructions**

Install a version before 1.0.1 of the [Shel.Neos.WorkspaceModule](https://github.com/Sebobo/Shel.Neos.WorkspaceModule)
and go to the user management module to impersonate a user. Then switch to the Workspace module and try to restore the original user. Without this patch, it should fail. With version 1.0.1 it will not fail btw.

**Checklist**

- [x] Code follows the PSR-2 coding style
- [x] Tests have been created, run and adjusted as needed
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Comment by markusguenther** [comment]
@so-grimm Feel free to take a look ;)

**Comment by Sebobo** [comment]
`UserManagement.js` would need the same adjustment right?

**Comment by markusguenther** [comment]
> `UserManagement.js` would need the same adjustment right?

Changed it here as well.

**Review by Sebobo — APPROVED** [review]
LGTM :)

**Review by mhsdesign — APPROVED** [review]

**Pull request merged**
