### PR TITLE
Make adjustments to support PHP8.1's stricter type system

### PR DESCRIPTION
**Pull request by nezaniel**
This adds additional type hints where required in PHP 8.1 ~while maintaining support for 7.4~.
These are only the adjustments required fir the ESCR test suite, more are to follow

### CODE REVIEW

**Comment by mficzel** [comment]
It would be great to add php 8.1 to the test matrix in .github/workflows/build.yml together with this.

**Comment by nezaniel** [comment]
8.1 builds are configured and run through smoothly, which leaves me a bit sceptical since that seems improbable. Is there more to be configured or is everything fine already?

**Review by bwaidelich — APPROVED** [review]
+1 by reading.. let's test this

**Comment by bwaidelich** [comment]
FYI: We removed PHP 7.4 from the matrix since Neos 8+ will require PHP 8.0+

**Pull request merged**
