### PR TITLE
BUGFIX: Show content element after copy paste inline

### PR DESCRIPTION
**Pull request by aertmann**
Fixes copy pasting of content elements where the new element wouldn't be displayed until
reloading the page.

Additionally fixes an issue where cutting an element caused a page reload.

NEOS-1506 #close

### CODE REVIEW

**Comment by kdambekalns** [comment]
:+1: - works fine on 2.1. Thanks!

**Comment by aertmann** [comment]
:+1:

**Comment by dfeyer** [comment]
:+1: Tested on 2.1 and 2.0 well done

**Comment by aertmann** [comment]
thanks

**Pull request merged**
