### PR TITLE
FEATURE: Add fusion-prototype ``TYPO3.TypoScript:RawCollection``

### PR DESCRIPTION
**Pull request by mficzel**
Other than ``TYPO3.TypoScript:Collection`` the ``TYPO3.TypoScript:RawCollection`` returns
an array of the rendered items instead of a concatenated string.

### CODE REVIEW

**Comment by skurfuerst** [comment]
Should we maybe create a separate Fusion object for this? I feel it is somehow weird that by changing a property, a completely different return type is returned.

What do you think?

All the best,
Sebastian

**Comment by mficzel** [comment]
@skurfuerst do you mean prototype ``RawCollection``? that would be possible but i fear we might run into performance issues here. I think the current behavior in the collection to append the subresults to a string is an already an optimization.

**Comment by kitsunet** [comment]
I also prefer a separate type, we could add both capabilities to the AbstractCollection maybe

**Comment by mficzel** [comment]
I adjusted the pr to define a separate prototype ``TYPO3.TypoScript:RawCollection``

**Pull request merged**
