### PR TITLE
BUGFIX: MenuHelper uses content dimensions to get node for privilege check

### PR DESCRIPTION
**Pull request by gjwnc**
Resolves: #4625

The Neos backend MenuHelper received a bugfix to filter sites listed by the menu using NodePrivileges. In case of sites with multiple dimensions the dimensionCombinations are considered too.

**Upgrade instructions**

**Review instructions**

This bugfix tries to fix #4025. If 7.3 and upwards is used on a multi site project with multiple dimensions, it might be that
```
$node = $context->getNode(\Neos\ContentRepository\Domain\Utility\NodePaths::addNodePathSegment(SiteService::SITES_ROOT_PATH, $site->getNodeName()));
```
returns `null`, causing the next line
```
if ($this->privilegeManager->isGranted(NodeTreePrivilege::class, new NodePrivilegeSubject($node))) {
```
to throw an exception. Thus the backend is not accessible anymore.  
The reason is, that for multisite projects with multiple dimensions it might be that `$node` cannot be retrieved by the default context created.

The fix is to use `contentDimensionCombinator` and also to explicitly check if `$node` could be retrieved.  
I'm also using the property `invisibleContentShown` and `inaccessibleContentShown` because it might be that an editor set the Home of a site to `hidden` by mistake. Thus the site might not accessible via the menu anymore to possibly fix an editor mistake.

**Checklist**

- [x] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Comment by gjwnc** [comment]
Since #4025 was reviewed by you guys, @kdambekalns, @kitsunet, @mhsdesign, may you can have a look at this too, please?

**Comment by mhsdesign** [comment]
hmm thanks for this fix. it seems we introduced a regression with https://github.com/neos/neos-development-collection/pull/4025

im not a fan of the `ContentDimensionCombinator` but i couldnt completely figure out a better way in my head.

at other places we seem to ask the `NodeDataRepository` directly - this seems to ignore dimensions (or picks the first one):

```php
$siteNodePath = NodePaths::addNodePathSegment(SiteService::SITES_ROOT_PATH, $site->getNodeName());
$siteNodeData = $this->nodeDataRepository->findOneByPath($siteNodePath, $workspace);

$siteNodeContext = $this->nodeFactory->createContextMatchingNodeData($nodeData);
$siteNode = $this->nodeFactory->createFromNodeData($siteNodeData, $siteNodeContext);
```

**Comment by mhsdesign** [comment]
I even found an issue for this https://github.com/neos/neos-development-collection/issues/4625 and it seems there is even an alternate fix :D https://github.com/neos/neos-development-collection/pull/4649

**Comment by gjwnc** [comment]
I think, #4649 is incomplete. It basically fixes, that the backend will still be usable, but the site won't show up in the return val `$sites`, although you might be allowed to access it, because the node is in another dimension than the default.

**Comment by mhsdesign** [comment]
Do you think https://github.com/neos/neos-development-collection/pull/4269#issuecomment-1757829434 this will work better? less costly?

**Comment by gjwnc** [comment]
Yeah, seems plausible. I'll give it a try in the next days and get back to you.

**Comment by mhsdesign** [comment]
Thanks, we are planning to include this in the last 7.3 bugfix release.

**Comment by gjwnc** [comment]
The usage of `NodeDataRepository::findOneByPath()` does not work either. This also returns `null`. To avoid the `ContentDimensionCombinator` I'll refactor my PR to use `findByPathWithoutReduce`. This seems promising.

**Comment by gjwnc** [comment]
Done. We've been using my patch since quite some time now and the change to `findByPathWithoutReduce` is really much faster than the `ContentDimensionCombinator` in our case, because we have so many languages and fallbacks.

**Comment by markusguenther** [comment]
It seems to work, although it is scary that we have a deprecation since Neos 3.2 in that code base 🙈

**Comment by mhsdesign** [comment]
Hiding a sideNode will currently cause this error

> Argument 1 passed to Neos\ContentRepository\Security\Authorization\Privilege\Node\NodePrivilegeSubject_Original::__construct() must implement interface Neos\ContentRepository\Domain\Model\NodeInterface, null given, called in /Users/marchenryschultz/Code/core/neos-manufacture-lowest/Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_ContentRepository_Security_Authorization_Privilege_Node_NodePrivilegeSubject.php on line 84

but with this bugfix it will still appear as excepted in the menu and one is able to unhide the side again.

**Review by mhsdesign — APPROVED** [review]
Thanks for your adjustments, the code looks much faster already and i could confirm that the reported issue is fixed.

I see that we check each side node in all dimensions of the live workspace against the `NodeTreePrivilege`. Im wondering if we really have to do this or if a check against the first default dimension will do?

On the other hand this seems to be the most correct solution to really loop over all and if even only one is granted grant access to the site.

**Comment by kitsunet** [comment]
> check against the first default dimension will do

It will not as pointed out above, you could have a site not available in the default dimension(s). 

That said, I think the first solution was so much better as it didn't use so many _internals_ of the ContentRepository. In the end I am fine merging this one too, but IMHO the first patch should've been merged. it was implemented according to public API. @mhsdesign

**Comment by mhsdesign** [comment]
Sure :D but it felt to expensive and with the Neos 9 on the horizon i thought that it would be better this way.

**Review by kitsunet — APPROVED** [review]
Because performance.

**Pull request merged**
