### PR TITLE
BUGFIX: Fix autoselection of ancestor nodes in Workspace module

### PR DESCRIPTION
**Pull request by bwaidelich**
Fixes: #5231

### CODE REVIEW

**Comment by bwaidelich** [comment]
~Mh, that's not correct yet~

It's not perfect yet, but better IMO

**Review by kitsunet — APPROVED** [review]
Looks good

**Comment by mhsdesign** [comment]
are we sure that this will not lead to invalid selections being publishable? For example i guess one can never publish just `a1` if their parent `a` is not even published yet?

**Comment by kitsunet** [comment]
> are we sure that this will not lead to invalid selections being publishable? For example i guess one can never publish just `a1` if their parent `a` is not even published yet?

I understand that that's exactly what this fix includes? Ancestors are still auto selected, just not siblings as well.

**Comment by bwaidelich** [comment]
> Ancestors are still auto selected, just not siblings as well.

Correct.
It's still not "perfect" because you can then de-select the ancestor node manually.
At some point we should streamline the rules and the UI.. But in any case the backend should ofc make sure that the request is valid

**Review by Benjamin-K — APPROVED** [review]
I've already stumpled accross this a few times now, but have never really thought about it. PR looks good, although it could still be improved. But at least way better then the currently (broken) code.

**Review by ahaeslich — APPROVED** [review]

**Pull request merged**
