### PR TITLE
TASK: Adds documentation for dynamically hiding editors in Neos UI

### PR DESCRIPTION
**Pull request by dennisirmscher**
Relates Neos UI Issue https://github.com/neos/neos-ui/issues/1682 and PR https://github.com/neos/neos-ui/pull/2118

**What I did**

Added documentation for dynamically hiding editors in Neos UI. See Issue https://github.com/neos/neos-ui/issues/1682 and PR https://github.com/neos/neos-ui/pull/2118 there.

### CODE REVIEW

**Comment by dimaip** [comment]
Also perhaps it's better to target 4.0?

**Comment by dennisirmscher** [comment]
I wasn't sure about this. I thought it to be a new "Feature" (even when it's only a very little one) and the guideline said they should go to master. But of cause I would be happy to change it to 4.0.

**Comment by dimaip** [comment]
But is the new feature in neos-ui, and older releases also include the latest neos-ui.

**Comment by dimaip** [comment]
Right @kitsunet?

**Comment by dennisirmscher** [comment]
Oh well, this is getting quite confusing. I think I will open a new PR for it one of you can merge up. Agree?

**Comment by dimaip** [comment]
Hep, unfortunately it's not easy to change the target branch. The simplest is just to create a new branch locally and cherry-pick the right commits.

**Comment by dennisirmscher** [comment]
I did and created a new PR: https://github.com/neos/neos-development-collection/pull/2182

**Pull request closed without merging**
