### PR TITLE
TASK: Improve & streamline styling of dropdowns

### PR DESCRIPTION
**Pull request by aertmann**

### CODE REVIEW

**Comment by aertmann** [comment]
image
image
image
image
image
image
image
image
image

**Comment by johannessteu** [comment]
👍

**Comment by gerhard-boden** [comment]
Tested in FF, Chrome an IE. :+1: 

What I like most about this is that there are no more misleading arrows in the `selected element` field, when there is nothing to select. 

Btw: How do i get to the state where the Username is marked like in one of your screenshots?

**Comment by aertmann** [comment]
@gerhard-boden: good to know, thought that would be an improvement too although it could potentially be confusing..

also not sure what you mean with your question? how is the username marked?

**Comment by aertmann** [comment]
thanks for the reviews 👍

**Comment by gerhard-boden** [comment]
@aertmann oh man that's what happens when I review stuff at 2am :smile: 
image
image

For reasons unknown i though that bar belonged to the username. But it's just the publish button, of course :smile:

**Pull request merged**
