### PR TITLE
BUGFIX: Check if image is possible to refit on replacement

### LINKED ISSUE #4752: BUG: Replacing an image with an SVG leads to "division by zero"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If yor try to replace an image in the media module, that already contains variants, with an other image, the AssetService tries to refit the new image.

In case the new image is an SVG no height or wight is provided to calculate the aspect ratio nor new dimensions. This leads to a "division by zero" error in the adjustment:

https://github.com/neos/neos-development-collection/blob/6011f885f757bd5e093c731d16322ed500b2f544/Neos.Media/Classes/Domain/Model/Adjustment/CropImageAdjustment.php#L274-L289

### Expected Behavior

No refit if a replacement with a SVG is processed.

### Steps To Reproduce

* add image to media library
* ensure variants are created (resize/crop)
* replace this image with an SVG

### Environment

```markdown
- Flow: 7.3
- Neos: 7.3
- PHP: 8.1
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by dlubitz**
Fixes #4752

Checks if the replacement is an image and has a size.

### CODE REVIEW

**Review by bwaidelich — APPROVED** [review]

**Comment by mhsdesign** [comment]
Im wondering if `refit` should rather be a noop as checking this beforehand looks kinda weird. Hmm and if we dislike this, i think the `refit` should throw a readable exception instead of an DivisionByNullError

**Comment by dlubitz** [comment]
The whole part is questionable, e.g. `method_exists($adjustment, 'refit')` should be checked by an interface. But I did't want to refactor that, I just want to get this case fixed for now.

**Comment by kitsunet** [comment]
> I just want to get this case fixed for now.

Famous last words, but I get it. I think fine for the time being given the state of the thing as of now.

**Review by kitsunet — APPROVED** [review]

**Comment by mhsdesign** [comment]
oki

**Comment by mhsdesign** [comment]
there is actually quite a clever way for our `method_exists($adjustment, 'refit')` to get more transparent:

use `@method void refit(object $image)` in the interface (as its not breaking), have seen doctrine and symphony doing this

**Comment by dlubitz** [comment]
> use @method void refit(object $image) in the interface
But which Interface?

**Pull request merged**
