### PR TITLE
BUGFIX: Use CK5 editor namespace/id for placeholder text #2718

### PR DESCRIPTION
**Pull request by akappler**

### CODE REVIEW

**Comment by davidspiola** [comment]
Just to make sure. Is 5.0 the correct branch?

**Comment by dimaip** [comment]
@davidspiola we can't have it earlier, as there the old UI still existed

**Comment by davidspiola** [comment]
@akappler can you pls check the merge conflict. Once resolved we can merge it

**Comment by akappler** [comment]
sorry, I accidentally deleted the forked repo. I guess it is the easiest to make a new PR and close this one.

**Comment by akappler** [comment]
@davidspiola it's not necessary any more. I guess @markusguenther hasn't seen my PR as he fixed it and it is now already in the 5.0 and master branch. So I'll close this one.

**Comment by markusguenther** [comment]
Yes sorry did not see that but we had quite alot PRs at some point :/
Hope that was ok.

**Comment by davidspiola** [comment]
> @davidspiola it's not necessary any more. I guess @markusguenther hasn't seen my PR as he fixed it and it is now already in the 5.0 and master branch. So I'll close this one.

alright! Thx for your PR anyway

**Pull request closed without merging**
