### PR TITLE
FEATURE: Trigger signal when Thumbnail is persisted

### PR DESCRIPTION
**Pull request by gradinarufelix**
PR for issue #2387 

**What I did**
Added a signal `thumbnailPersisted` and an ORM lifecycle callback that triggers the signal once the thumbnail is persisted.

**How I did it**
Added two methods in Neos\Media\Domain\Model\Thumbnail: one for the signal and one for the lifecycle callback that triggers the signal.

**Checklist**

- [x] Code follows the PSR-2 coding style
- [x] Tests have been created, run and adjusted as needed
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)

### CODE REVIEW

**Comment by gradinarufelix** [comment]
@albe I don't get the point because we don't use `thumbnailCreated` for this  `postPersist` here. But yes, if this is more fine we can move the `emitThumbnailPersisted` to `ThumbnailService`. We can discuss that. Even if I would say that it is tied to the model itself.

**Comment by kdambekalns** [comment]
> But yes, if this is more fine we can move the `emitThumbnailPersisted` to `ThumbnailService`.

The idea is to have those signals in one place, so adding this to any other place seems counter-productive.

**Comment by gradinarufelix** [comment]
> The idea is to have those signals in one place, so adding this to any other place seems counter-productive.

Good, I'll update this later today. Thanks for the hint!

**Comment by gradinarufelix** [comment]
The problem is now: if I put the signal into the service class, I'll need to inject the service class into the model class. Is this a best practise? Because it feels a little bit odd.

**Comment by albe** [comment]
> Then again, what signal are you referring to, @albe?

Ah sorry, that was thoughtless to strip the signal name and just put the doc-block in. I was referring to `emitThumbnailCreated`.

> I'll need to inject the service class into the model class.

Correct. It's a decision of keep all thumbnail signals together inside a class vs. having a "cleaner" model. I'm in favor of injecting and having the signals together, but that is not a strong opinion.

**Comment by gradinarufelix** [comment]
I can understand the sense of having all signals in one place, but @gerhard-boden is also right with this approach. But I'd leave `thumbnailCreated` in the service class as it is called there.

**Comment by gradinarufelix** [comment]
So what should we do now? Leave it like that or transfer the signal to the service class?

**Comment by daniellienert** [comment]
@albe, @kdambekalns would be nice if you could decide on that to get this through. I personally would vote to put it into the service class.

**Comment by albe** [comment]
> Would it be awkward to remove the deprecated tag from the emitThumbnailCreated method again and mark the one in the service as deprecated to have everything in one place again?

Generally not in favor of deprecating something that was supposed to replace another deprecation and revert that. Will just create too much confusion. On the other hand, this deprecation seems to have existed since even before the package rename (dfab7150468db9784fa8f4332b03615cc6da520e) soooo... from what I found, it was a commit by @daniellienert that introduced the change, so he should decide if a reversal is okay. Otherwise I'm still for injecting the service.

**Comment by gradinarufelix** [comment]
Its not about the deprecated signal, this is a completely different one. I want to introduce a new signal `thumbnailPersisted` which is triggered when the thumbnail is persisted in the database. Because `thumbnailCreated` fires way before that point.

So don't worry about the deprecated one. The question is now: should we put the new signal also in the service class or not?

**Comment by daniellienert** [comment]
@gradinarufelix: Please move it to the service class.

**Comment by mficzel** [comment]
@gerhard-boden please review again and merge if you approve.

**Pull request merged**
