### PR TITLE
BUGFIX: Add php version declaration to neos/fusion-afx

### PR DESCRIPTION
**Pull request by kitsunet**

### CODE REVIEW

**Comment by Sebobo** [comment]
Shouldn't we in general make sure the version of this package matches the Neos version like we do with other packages?

**Comment by kitsunet** [comment]
I don't see why we have to as long as the API doesn't change? But would be fine for me too I guess.

**Review by kdambekalns — APPROVED** [review]

**Comment by kitsunet** [comment]
I'd say lets merge this for now and consider how to deal with this in the future...

**Comment by Sebobo** [comment]
I mean when I work on this package I would at least assume that all other packages match and don't test it with Neos 7 separately when I work on 8.x f.e.

**Review by mhsdesign — APPROVED** [review]

**Comment by kitsunet** [comment]
@Sebobo yep, yep, agreed. We could add that as well on top. the question is, do we depend on fusion 8 or just let neos depend on the respective fusion-afx version, many options...

**Comment by markusguenther** [comment]
Thanks for taking care @kitsunet 🥳

**Comment by Chxyz** [comment]
Hi,
Thanks for that!

Just a question, shouldn't there be a commit in the 7.3 branch?
Since it's the 7.3 projects that are impacted by this... :-)

Best regards,
Chrys

**Comment by kitsunet** [comment]
Hey Chrys,

well yes and no. I guess we have to add a fixed version requirement to fusion-afx in earlier branches, the php requirements won't really help though. I talked to karsten about it...

**Pull request merged**
