### PR TITLE
TASK: Image adjustment for image quality

### LINKED ISSUE #768: As a site integrator I want to have control over image quality for individual images
Jira issue originally created by user @hlubek:

In order to provide a better experience for users with different devices
As an integrator of a site
I need to provide different versions of an image, including double-scaled with zero quality

 Jira-URL: https://jira.neos.io/browse/NEOS-100

### PR DESCRIPTION
**Pull request by dfeyer**
I added a adjustment for the image quality that can be used to override the global configuration.
Sometimes you might want to add a preview image with lower quality as a thumbnail, but you couldn't. I added the quality property to Neos:ImageUri to make this possible.

    previewImageUri = Neos.Neos:ImageUri {
        asset = ${q(node).property('image')}
        maximumWidth = 2560
        maximumHeight = 1280
        quality = 25
    }

Resolves #768

### CODE REVIEW

**Comment by dfeyer** [comment]
The upmerge of master was not easy, because of the introduction of async/preset in between, but look like everything work fine.

I remove the default value in QualityTrait, the default comes from the settings value automatically.

**Comment by dfeyer** [comment]
Also would this be a breaking change as it alters the thumbnail configuration and image services ?

**Comment by dfeyer** [comment]
> IMHO the changes are no breaking, since all new arguments are optional and none of that is marked as API.

The question is not really API wise, but as we change the adustement, Neos will have to regenerate all thumbnail ... and duplicate a lots of files. Not sure how to sort this out

**Comment by mficzel** [comment]
The "quality"-key in the fusion documentation should be documented aswell i think.

**Comment by dfeyer** [comment]
> I would consider it non-breaking since \Neos\Media\Domain\Model\ThumbnailConfiguration::toArray passes the values trough array_filter and thus removes null-values anyways. So i think this should not cause and unexpected thumbnail regeneration.

@mficzel You are right, and by the way it's fun to read my own commit message, that explain why we use the array filter here ;) to allow some change in the ThumbnailConfiguration without breaking everything ;)

So for me it's mergeable, and thanks for the documentation update.

**Comment by dfeyer** [comment]
Just upmerged master, to resolve the conflict with the interlace feature.

**Comment by kitsunet** [comment]
Sorry I am late to the party, but I have a few gripes that we should talk about at some point.

a) This quality number is pretty implementation specific for the underlaying image manipulator
b) Only one of these can be taken into account, so a magic "take first found" thing is happening.
c) extending the constructor signatures of thumbnails etc. ad absurdum is not really great.

**Pull request merged**
