### PR TITLE
BUGFIX: Fix wrong hint meaning on XLIFF cache

### PR DESCRIPTION
**Pull request by franzkugelmann**

### CODE REVIEW

**Comment by kdambekalns** [comment]
When does this first appear in the docs? Could very well change to the lowest affected branch…

**Comment by kitsunet** [comment]
Yes, needs to be applied to 2.0

**Comment by kdambekalns** [comment]
Ok, so changing the base of a PR works "great"… :/

**Comment by kdambekalns** [comment]
And back to one commit instead of 2500-something.

**Comment by kitsunet** [comment]
Haha, yes, that's what I tried as well ;)

**Comment by kitsunet** [comment]
it works more or else if going forward...

**Comment by franzkugelmann** [comment]
was it correct for me just to pullrequest onto master? What would be the best approach to save time on your side?

**Comment by kdambekalns** [comment]
Te best would be if you cherry-picked your change onto 2.0 and created a new PR, then close this one. Thanks!

**Pull request closed without merging**
