### PR TITLE
BUGFIX: Exclude "/sites"-node from dimension-migration

### LINKED ISSUE #3109: Node-Migration breaks dimension menu
### Description
The [CR-Documentation](https://docs.neos.io/cms/manual/content-repository/multiple-languages#migrate-existing-content) describes, that you should execute the node migration 20150716212459 after adding a new dimension-configuration. The migration Updates **ALL entries** inside of the nodedata table (and set's the default dimensions values), including the highest parent `/sites`-node.  

@andrehoffmann30 figured out, that this breaks the Dimension-Menu. Afterwards it only shows the default dimension-value. Direct access via known URL and backend is still working. It seems like the DimensionMenu uses the highest node with non-empty dimension configuration, which causes this behavior. In this case it's `/sites`, which is not getting copied into other dimensions when copying pages in the backend.

After removing dimension-configuration from `/sites` and removing the related entry inside of `neos_contentrepository_domain_model_nodedimension`, everything is working fine again. 

### Steps to Reproduce

1. Get a Neos with contents without dimension-configuration and add a DimensionMenu.
2. Add dimensions following https://docs.neos.io/cms/manual/content-repository/multiple-languages and execute the migration (as described there)
3. Copy Contents to other Dimensions using the backend-prompt.
4. Clear Cache and check the DimensionMenu (It should only display the default dimension-value).

#### Expected behavior

Since the `/sites`-node isn't copied while creating content in other dimensions, the migration should not give a dimension-configuration to this node. Same for the `/` node. Both have `unstructured` as NodeType.

#### Actual behavior

It gives the default dimension-value to `/sites`-node.

### PR DESCRIPTION
**Pull request by Nikdro**
Fixes #3109

### CODE REVIEW

**Comment by Nikdro** [comment]
I'm not 100%-sure if filtering by `unstructured` doesn't have any side-effects. But I see no reason, why unstructured nodes should get a dimension-configuration. 

I tested this against a customer project, which already has dimensions configured. Without the fix, it breaks the DimensionMenu and navigation etc. With fix it's working as expected. 

Looking forward to hear your feedback 🙂

**Review by daniellienert — COMMENTED** [review]
Just tested in two projects and can confirm that it solved the described issue. 
Still haven't tested why it works with the language set with the demo package and demo content.

**Review by daniellienert — APPROVED** [review]

**Comment by jonnitto** [comment]
Can anyone tell me why the Travis CI check doesn't run?

**Review by jonnitto — APPROVED** [review]

**Comment by mficzel** [comment]
@jonnitto this is the old Travis.org test. It is replaced by the Travis.com test which is already green

**Comment by jonnitto** [comment]
From my side, this can be merged. I've not enough rights, bc of the old tests…

**Comment by jonnitto** [comment]
@kdambekalns I changed the base branch to 5.3, can we merge this?

**Comment by mficzel** [comment]
@jonnitto the altered base branch should be fine as you changed the target to a newer branch. The other way would cause trouble.

**Pull request merged**
