### PR TITLE
BUGFIX: fix composer create-project command for neos dev collection

### PR DESCRIPTION
**Pull request by crydotsnake**
I noticed that the previous command is no longer working.

### CODE REVIEW

**Comment by mhsdesign** [comment]
..ups yes the `master` is not anymore the correct branch, composer should use `8.2`

but why remove the `--prefer-install=auto` (introduced with https://github.com/neos/neos-development-collection/pull/3367)
... maybe its not needed anymore with: https://github.com/neos/flow-development-distribution/blob/fd825a7829d3cd323b08c07150494a7b1f5b2520/composer.json#L17-L19 in place?


---

honestly i think this `composer create-project` thing is not really helping. When i first set it up - i had problems too (the mentioned #3367 ^^) 

how about we propagate the pattern of just cloning the https://github.com/neos/flow-development-distribution?

```
git clone git@github.com:neos/flow-development-distribution.git
composer install
```

**Comment by crydotsnake** [comment]
> how about we propagate the pattern of just cloning the https://github.com/neos/flow-development-distribution?
> 
> ```
> git clone git@github.com:neos/flow-development-distribution.git
> composer install
> ```

But its about contributing to Flow and/or Neos :). And there, the Development Collection would be more useful. 

>but why remove the --prefer-install=auto (introduced with https://github.com/neos/neos->development-collection/pull/3367)
>... maybe its not needed anymore with: https://github.com/neos/flow-development->distribution/blob/fd825a7829d3cd323b08c07150494a7b1f5b2520/composer.json#L17-L19 in place?

And its the same command as here: https://github.com/neos/flow-development-collection/edit/8.2/Readme.rst. So yes you could be right.

**Comment by mhsdesign** [comment]
> But its about contributing to Flow and/or Neos :). And there, the Development Collection would be more useful.

dont confuse
https://github.com/neos/flow-base-distribution
with 
https://github.com/neos/flow-development-distribution
:D

what i suggested with git clone is the same what composer does with create-project

**Review by kdambekalns — APPROVED** [review]
Well, it's partly "my" change now, so feel free to consider me opinionated. 😎

**Comment by crydotsnake** [comment]
> Well, it's partly "my" change now, so feel free to consider me opinionated. 😎

Looks good! I wasnt sure if it would be `@dev` or `8.2.x-dev` first. Because in the Flow Development Collection it was also  `@dev` in the composer command. 

But my question has been Answered 😉

**Review by ahaeslich — APPROVED** [review]

**Pull request merged**
