### PR TITLE
!!! BUGFIX: Prevent busting the configuration cache version when a user logs in or is updated

### PR DESCRIPTION
**Pull request by Sebobo**
**What I did**

Without this patch the configuration version was flushed and raised after every login or any other change to an account, always forcing the browsers to reload nodetype schemas and other configuration-requests which used the configuration version as cache-buster parameter. So if a user would reload the Neos backend after someone else logged in or logs in and out, the backend loading time would be much slower, as the nodetype schema and xliff data would have to be regenerated and downloaded skipping the possibly already cached version in the browser.

Also each role combination of users now has their own version identifier and therefore can share the resulting nodetype schema, xliff, etc.

Before everyone had the version of the user that last logged in or had any other change to their account as every change would have flushed the configuration version.

**How I did it**

* Removed the `AccountPostEventListener` which only flushed the `Neos_Neos_Configuration_Version`. This could be breaking if anyone relied on it.
* Make sure every role combination has their own configuration version.

**How to verify it**

* Log in with first user and note down configuration version query parameter of nodetype request
* Log in with second user with same roles and compare configuration version, should be the same
* Reload with first user and make sure the version is still the same

### CODE REVIEW

**Comment by Sebobo** [comment]
Hi @robertlemke I created this patch based on your analyses in our shared customers project.
The patch works quite well there so far, I just fear it is breaking if anybody relied on the `AccountPostEventListener` for some kind of reason. 
On the other hand this is really a stupid bug and would also be sad to have to wait for 8.0.

Do you see a sensible less breaky way to do this?
Just disabling the configuration would still be breakish.

**Review by kdambekalns — COMMENTED** [review]
Looks good, and should not be breaking IMHO. Will test tomorrow.

**Comment by kdambekalns** [comment]
I wonder if this is really breaking in a way that justifies keeping this from being applied to 5.3 and up. 🤔

**Comment by kdambekalns** [comment]
I have to admit I don't get why/how the cache is ever flushed… The entries are not tagged with anything and there is no code that flushed that I could find.

So, every combination of roles gets an entry, changing the roles on an account will load the corresponding data. But if anything else is changed that influences the configuration, the cache is not flushed (unless something triggers a flushing of all caches.)

Right? Wrong?

**Comment by Sebobo** [comment]
The cache is flushed in various cases in `Neos.Neos` `Package.php`. F.e. on file changes.

I don't expect a reason to flush this cache during runtime.

**Comment by kdambekalns** [comment]
Oh my… seems I searched only YAML files. 🙈

**Review by kdambekalns — APPROVED** [review]

**Review by mficzel — COMMENTED** [review]
I wonder what would happen if two users with a different set of roles would login in the same second? Would'nt that break the use of time as identifier?

**Comment by Sebobo** [comment]
That would only be a problem if no-one else with their role combination ever logged in before since the last cache flush.
So yes that would be a theoretical problem that would already exist now.

**Comment by mficzel** [comment]
Woud'nt a uuid make more sense in that case. Not a blocker if this has been a theoretical issue before

**Comment by Sebobo** [comment]
We could also hash the role combination 🤔

**Comment by mficzel** [comment]
>  We could also hash the role combination 🤔
If that works i would like this better

**Review by mficzel — APPROVED** [review]
Ahh ... now i get this this is a cache buster for the configuration fetching endpoints. In this case the solution is fine as it is. 

The roles hash could still be added to the version-time to make this more transparent and get rid of the last. But that would be an improvement that we can add later.

**Comment by mficzel** [comment]
Pushed a commit that uses a combined identifier of role hash and last time this was changed. That way the browsers can safely cache the configuration.

What threw me off is the description configuration cache. Actually it is the browser cache that stores the configurations as allowed via cache-control header. The ViewHelper ensures that a unique identifier is added to the urls to ensure that new configurations actually reach the ui.

**Comment by Sebobo** [comment]
ok thx, sorry for the confusion. But this thing is also a bit confusing itself.

**Review by albe — APPROVED** [review]

**Comment by bwaidelich** [comment]
Wow.. good catch.
FYI: I assume that this got a real issue with https://github.com/neos/flow-development-collection/pull/127 because that updates the accounts for every login (usually an account probably doesn't change that often).

What I still fail to understand is: Why does every user (i.e. every role combination) need a separate configuration version?

**Comment by mficzel** [comment]
Close and reopen to trigger ci

**Review by bwaidelich — APPROVED** [review]
(by reading)

**Pull request merged**
