### PR TITLE
TASK: Add workspace/parent index to NodeEvent table

### PR DESCRIPTION
**Pull request by kdambekalns**

### CODE REVIEW

**Comment by kdambekalns** [comment]
This needs migrations to be created!

/cc @Fiach

**Comment by Fiach** [comment]
@kdambekalns  Correct this would involve migrations, how shall we proceed with these :?

**Comment by kdambekalns** [comment]
@Fiach You could this… ;)

**Comment by kdambekalns** [comment]
ping…

**Review by jonnitto — APPROVED** [review]

**Comment by Fiach** [comment]
@kdambekalns  sorry for not answering and supporting this, I have been very busy lately. I will try to test this by the end of next week.

**Comment by kdambekalns** [comment]
ping… anyone else, maybe?

**Review by mficzel — APPROVED** [review]
Fine by reading, did not test performance but it is plausible that this improves some things

**Pull request merged**
