### PR TITLE
TASK: Improve exception error notifications

### PR DESCRIPTION
**Pull request by aertmann**
Generalises and improves the output of exception errors.

Removes unuseful custom AJAX error handling and thus avoids displaying multiple error notifications for a single error.

NEOS-185 #close

### CODE REVIEW

**Comment by aertmann** [comment]
image

**Comment by gerhard-boden** [comment]
:+1: by testing. Thanks for that change! Finally no more giant "end of the world" messages that scare editors if something goes wrong. :smile: 

Plus: If I throw an exception within `Package.php` the message shows up now, and not just "Server communication error: 500 Internal Server Error" without further details
image

**Comment by mgoldbeck** [comment]
:+1:

**Comment by kdambekalns** [comment]
I'd love to have the exception trace reference in there, so one has a chance to relate to it.

**Comment by aertmann** [comment]
@kdambekalns: Yeah makes sense, although I initially didn't since you can open your network monitor/console to get those details. Now adding that was not that easy due to the how terrible the exception output is written, but found a way that works pretty well. Additionally notice that this custom exception handling actually exposes exception information in production context and eliminated that.

Production context:
image
Development context:
image

**Comment by kdambekalns** [comment]
Looks good now, thanks!

One tiny thing: there is no break between `Unknown Status` and `When contacting …` in the Production context JSON example screenshot.

**Comment by aertmann** [comment]
@kdambekalns: thanks, fixed that one.. actually better without it

image

**Comment by johannessteu** [comment]
Tested, verry cool! But if you wann select/copy the reference code, wich is a common case i thing, the toogle is clicked. Should we just trigger the message when clicking on the first line? If you try to copy the code, the code will disappear right now :)

**Comment by aertmann** [comment]
@johannessteu: good point, took care of that

**Comment by johannessteu** [comment]
Great! 👍

**Pull request merged**
