### PR TITLE
FEATURE: Introduce NodeTypePresetPostprocessor

### PR DESCRIPTION
**Pull request by mficzel**
Introduce `NodeTypePresetPostprocessor` and extract `IconNameMappingPostprocessor` and `DefaultPropertyEditorPostprocessor` from `NodeTypeConfigurationEnrichmentAspect`.

This allows to configure nodeType presets via settings and apply them to nodeTypes via. Other than mixins this allows to ensure consistent configurations across differently named properties to ensure a consistent editor experience.

Note: This is mainly a core adaptation of the Sitegeist.Silhoettes package https://github.com/sitegeist/Sitegeist.Silhouettes.

The presets can be applied by definining the `options.preset` for childNodes or properties.

```
Neos:
  Neos:
    nodeTypes:

      presets:

        childNodes:
          vendor:
            defaultConstraints:
              constraints:
                'Neos.Neos:Content': true
                'Neos.NodeTypes.BaseMixins:TitleMixin': true

        properties:
          vendor:
            textBlock:
              type: string
              ui:
                inlineEditable
            type: string
            defaultValue: ''
            ui:
              inlineEditable: true
              inline:
                editorOptions:
                  placeholder: 'Vendor.Site:NodeTypes.Generic:text.placeholder'
                  autoparagraph: true
                  formatting:
                    strong: true
                    em: true
                    u: false
                    underline: false
```

Presets can then be applied to nodetypes via: 

```
'Vendor.Package:NodeTypeName':
  childNodes:
    column1:
      options:
        preset: 'vendor.defaultConstraints'    
    column2:
      options:
        preset: 'vendor.defaultConstraints'    
  properties:
    description:
      options:
        preset: 'vendor.textBlock'
```

Resolves: #3090

This also solves two thirds of #2867  (get rid of NodeTypeConfigurationEnrichmentAspect). The last part cannot be extracted that easily as it converts the magic value `i18n` to a key built from the NodeType it was defined on.

### CODE REVIEW

**Comment by mficzel** [comment]
For the review i would request to also reason about wether the chosen ways to define the position of the new nodeType postprocessors is correct. 

Also the question wether the newly introduced limitation that those postprocessors will only run for nodeTypes derived from `Neos.Neos:Node` is a problem or not.

**Comment by bwaidelich** [comment]
@mficzel I didn't have the time to look into this one closely, but I already sense that it's a great change and added the feature to the 6.0 project board. I assume this overlaps with #2870 ?

**Comment by jonnitto** [comment]
I talked with some people about this, and everyone is happy that this gets finally into the core. :heart: But some of them said that they are not that happy, that the configuration lives in the `Settings.yaml` files. Perhaps we could introduce a new type of config file, something like `Presets.yaml` (or `Presets.*.yaml`) of course.

**Comment by bwaidelich** [comment]
> some of them said that they are not that happy, that the configuration lives in the Settings.yaml

Can you elaborate why?

I kind of dislike the many configuration types as they make things more complex.
Some people don't know that they can just use suffixes like `Settings.NodeTypePresets.yaml` – is that any worse than `Presets.yaml`?

**Comment by mficzel** [comment]
I also think that another configuration type does not make things easier. That is why this uses settings.

**Review by jonnitto — APPROVED** [review]

**Review by bwaidelich — APPROVED** [review]
Thanks for this change, I really welcome it! :)
I can't really test it atm, but I'd say: Lets get it in asap and fix things if they break.

But I'm wondering: Doesn't this change the order in which configuration is merged etc. i.e. is this a potentially breaking change?

**Comment by mficzel** [comment]
@bwaidelich it might intefere with the order when other Postprocessors like the "CreationDialogPostprocessor" are invoked. 

I just tested this again with the `showInCreationDialog` that is added in Document and Content NodeTypes derived from Neos:Node feature and it works as expected and default Editors can be used in the CreationDialiog.

**Comment by bwaidelich** [comment]
Sounds great, thanks for the feedback.
I'd say: Let's merge this one and see how it plays out

**Comment by mficzel** [comment]
close and reopen to trigger travis ci

**Pull request merged**
