### PR TITLE
WIP: FEATURE: Integrate `ContentStream` projection into `ContentGraph`

### PR DESCRIPTION
**Pull request by bwaidelich**
WIP because

- [ ] This will most likely be included with #4979

### CODE REVIEW

**Comment by bwaidelich** [comment]
Obsolete with #4979

**Comment by mhsdesign** [comment]
... sorry i dont follow ... i thought we would not integrate this in christians change as this will not be required and kept slim at first?

**Comment by bwaidelich** [comment]
I think we have to include that into the Graph Adapter change (#4979) because otherwise this has to access foreign projection states which is a no-go IMO.
But maybe we can in fact add this one (and also integrate the `Workspace` projection as a _first_ step.
I'll reopen it for now

**Comment by bwaidelich** [comment]
Will be addressed with #5096

**Pull request closed without merging**
