### PR TITLE
TASK: Raise PHPUnit version to 9

### PR DESCRIPTION
**Pull request by albe**

### CODE REVIEW

**Comment by albe** [comment]
🤞 that builds run through (or at least pass installation)

**Review by kdambekalns — APPROVED** [review]

**Comment by albe** [comment]
> OK, but incomplete, skipped, or risky tests!
Tests: 5805, Assertions: 10751, Skipped: 65, Incomplete: 1.

🎉

**Comment by bwaidelich** [comment]
@albe thanks for taking care

> Just now realized that #3229 should have solved that already, but did not end up in the 7.0 branch

Yep, I realized that yesterday as well: https://neos-project.slack.com/archives/C12EZDXA8/p1607365582260300

But @kdambekalns wrote

> Fixed that by merging back and forth…

**Comment by albe** [comment]
Yeah. All is well with this now (and #3232 will prevent the composer merger from overwriting this again). Tests also green :)

**Comment by kdambekalns** [comment]
> But @kdambekalns wrote
> 
> > Fixed that by merging back and forth…

Ah, then I misunderstood what you meant! The merge of the PR related to PhpUnit was fine, there was nothing to fix… the dependency was broken "afterwards in secrecy" by the branching…

**Pull request merged**
