### PR TITLE
TASK: Correct class loading for Neos Cli setup in master and restore alphabetical order

### PR DESCRIPTION
**Pull request by mficzel**
as is in the 7.3 branch already

### CODE REVIEW

**Comment by kitsunet** [comment]
Now I wonder why was this wrong in the first place?

**Comment by mficzel** [comment]
I copied the code that was added in 7.3 probably by the script. The bug in master was introduced by me manually it seems.

**Comment by mficzel** [comment]
This should resolve the problem in https://github.com/neos/flow-development-collection/pull/2775

**Review by kitsunet — APPROVED** [review]

**Review by kdambekalns — APPROVED** [review]
🤷‍♂️

**Comment by mficzel** [comment]
Merge as the failures are not related to this change

**Pull request merged**
