### PR TITLE
TASK: Event logging tweaks & fixes

### PR DESCRIPTION
**Pull request by kdambekalns**
Some rather small tweaks and fixes to the event logging and the history module.

### CODE REVIEW

**Comment by kdambekalns** [comment]
Maybe @patrickreck and @kitsunet could have a look at some point… :)

**Comment by kitsunet** [comment]
Generally all makes sense, but the test failures seem legit?

**Comment by kitsunet** [comment]
ping @kdambekalns would you look at the test failures?

**Comment by kdambekalns** [comment]
:+1: from my side

**Comment by kitsunet** [comment]
:+1:

**Pull request merged**
