### PR TITLE
BUGFIX: Respect interface language when translating help message

### PR DESCRIPTION
**Pull request by hhoechtl**
NEOS-1750 #close
NEOS-1793 #comment Speeds up server side processing

### CODE REVIEW

**Comment by aertmann** [comment]
Hey Hans

Thanks for the fix. Looking at the code, I noticed some bigger underlying problems unfortunately.

Basically labels should never be translated in the configuration, since it's cached heavily (both client and server side) and only cleared when the underlying configuration actually changes.

A more suiting fix would be adding ``BackendUserTranslationTrait`` to ``SchemaController``, but this will also have the same problem.

So instead no translation should happen server side and instead be done client side, which won't have any problems with caching.

Additionally having a method like ``splitIdentifier`` in such a class is very wrong and should have raised alarms. Although understandable since it's a bit confusing currently due to a half done implementation in Flow/Eel.

/cc @dimaip @kdambekalns

**Comment by dimaip** [comment]
Sorry, missed this PR. Will try to look at this issue next week.

**Comment by kdambekalns** [comment]
Agreed: this translation is done in the completely wrong place, sorry for that. It would need to be converted from Markdown for all available languages and moved to the client. Could this be done during the xliff-to-json conversion?

**Comment by aertmann** [comment]
Related https://jira.neos.io/browse/NEOS-1793

**Comment by kdambekalns** [comment]
@dimaip Some time ago we talked about this topic, did you get around to doing anything related to this?

**Comment by kitsunet** [comment]
I still think we should do the markdown conversion on the client side and treat it as any other label basically.

**Comment by kdambekalns** [comment]
Closing this, since the underlying problem needs to be tackled in a different way. Let's fix this with https://jira.neos.io/browse/NEOS-1793

**Pull request closed without merging**
