### PR TITLE
FEATURE: Custom Route for node preview

### PR DESCRIPTION
**Pull request by bwaidelich**
Introduces a new Route `/neos/preview` that will be used for previewing/editing purposes in the content iFrame and to preview content that is not live or visible (yet).

### Greatly reduced amount of routing cache entries

Previously, URLs for nodes in the backend had the format `<the/node/url/path>@<workspace-name>;<dimensions>`
Thus leading to two routing cache entries (match & resolve) for each user, node & dimension combination.
With this change, there is only *one route* for those cases usinq query parameters to specify the node & context: `/neos/preview?node=<the/node/url/path>@<workspace-name>;<dimensions>`

### Explicit preview action

With a custom action just for the preview scenario, we can remove a lot of special magic (like displaying hidden nodes, shortcut handling, ...) from the regular frontend rendering path

### Faster backend navigation

Previously all links in the Backend triggered a `redirect` route, effectively resulting in two requests.

### Basis for further improvements and simplifications

With a different route (and action) we could greatly simplify the code of the `FrontendRoutePartHandler` and make way for new features like partial matching (#780), multi-format-support (#870) dedicated workspace previews, ...

*Note:* This requires https://github.com/neos/neos-ui/pull/2604 to work as expected

Resolves: #2653

### CODE REVIEW

**Comment by bwaidelich** [comment]
@davidspiola I merged the current master branch into my fork. But for me the backend currently doesn't load with latest master...

If you test this, make sure to flush caches (also browser caches to remove session cookie) and to apply https://github.com/neos/neos-ui/pull/2545

**Comment by bwaidelich** [comment]
@davidspiola (and all) can you please test again now? It was the Neos.UI change that needed rebasing. I got confused so I created a new PR against master: neos/neos-ui#2604

**Comment by davidspiola** [comment]
> @davidspiola (and all) can you please test again now? It was the Neos.UI change that needed rebasing. I got confused so I created a new PR against master: [neos/neos-ui#2604](https://github.com/neos/neos-ui/pull/2604)

will do

**Comment by davidspiola** [comment]
Strange behavior, but might be totaly unrelated to you PR. If I navigate in the page tree I get 404 errors. Links within the website are working correctly. If I test with current master it work as expected.

Screenshot 2019-12-02 at 17 44 21

**Pull request merged**
