### PR TITLE
FEATURE: Support batch tag and asset collection creation

### PR DESCRIPTION
**Pull request by dfeyer**
This feature add the possibility to add multiple tags or asset
collection is a single action. The user needs to separate tags with a
comma.

### CODE REVIEW

**Comment by dfeyer** [comment]
We need to add a small legend bellow the input box, to make this feature visible to our user.

Is comma a good split character ? Did you think user needs comma in tag name ?

**Comment by jonnitto** [comment]
I think a comma is a good and common split character

**Comment by bwaidelich** [comment]
*ping* last call to get this into 4.2

**Comment by bwaidelich** [comment]
I added an issue for this: #2275

**Comment by bwaidelich** [comment]
I suppose we don't have some clever "select2" style component for backend modules that would allow for a more explicit UI and interface (i.e. `createBatchAction(array $tags)`)?

**Comment by kitsunet** [comment]
we would need to create one. Or use (for now some jquery library for tagging, that then exports them as array/separate fields. Something like https://github.com/sniperwolf/taggingJS

And then rework it once we have react there.

**Pull request closed without merging**
