### PR TITLE
TASK: Cleanup some code across packages

### PR DESCRIPTION
**Pull request by johannessteu**
This changes makes use of the use statement and `::class` method to get rid of the namespaces as much as possible

### CODE REVIEW

**Comment by johannessteu** [comment]
This PR will tackle some code cleanup for the whole dev collection to get rid of namespaces to prepare our namespace change so upmerges will be later on easier. Each package will get a single commit in this PR

**Comment by dfeyer** [comment]
@johannessteu What's the status of this PR, I'm working on the Media package, so can conflict ...

Based on my experience we should avoid this kind of cross package PR, to easy to have conflict

**Comment by kitsunet** [comment]
As this was not merged, I assume we should probably close it?

**Comment by aertmann** [comment]
@johannessteu? Would still like these improvements to go in, but maybe target master instead?

**Comment by kitsunet** [comment]
I agree that his should be done, but rebasing this to master probably means redoing it anyway. Will close for now.

**Pull request closed without merging**
