### PR TITLE
!!! BUGFIX: Fix languages fallback order

### PR DESCRIPTION
**Pull request by gerdemann**
The fallback order now corresponds to the order from the dimension "language".

### CODE REVIEW

**Comment by gerdemann** [comment]
@albe I didn't find that in the documentation. If you can tell me the place, I'll adjust it there.

**Comment by albe** [comment]
Ah sorry, didn't take a look beforehand. If there is no section for this yet, I'd probably request adding something :) would be nice to have this within this PR, though objectively a BUGFIX PR is not supposed to contain new docs of course

**Comment by gerdemann** [comment]
@albe I asked Roland for an account for the Neos documentation. I would then add it there.

**Comment by gerdemann** [comment]
> `master` is clearly not the lowest maintained branch… Or is only master affected?

I think it's a breaking change, so it's only allowed in the `master`, right?

**Comment by kdambekalns** [comment]
Oops, right. Sorry for overlooking that…

Here is the description I removed (for the sake of our changelog):

----

**What I did**
The fallback order of the languages was wrong

**How I did it**
Adapt the fallback order of languages in FusionView

**How to verify it**
Define multiple languages in the language dimension and create different translation files.

**Checklist**

- [x] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)

If tests should be necessary, I would try to submit them later if the change is okay.

---

**Comment by kdambekalns** [comment]
Merged master to fix TravisCI builds (composer out-of-memory issue…)

**Comment by albe** [comment]
was missing the label, otherwise Karsten would have surely noticed ;)

**Pull request merged**
