### PR TITLE
TASK: Set default setting to disable the switch to old UI switch

### PR DESCRIPTION
**Pull request by mstruebing**
This introduces a new Setting to control whether the switch to old UI button should be shown or not.

```
Neos:
  Neos:
    Ui:
      frontendConfiguration:
        legacy:
          enableLegacyUiSwitch: <bool>
```

related https://github.com/neos/neos-ui/pull/1809

### CODE REVIEW

**Comment by dimaip** [comment]
> And why would be have that settings in the Ui package namespace?

I think because then it's easier to access it from the UI. Right, Max?

**Comment by mstruebing** [comment]
Yep, it is easier to access indeed. And as this is only needed for a limited time, until the old UI gets removed, I've thought it's not worth the hassle.
Is this a problem that the setting is under the Ui/frontendConfiguration namespace?

I will try change this to an enable flag today but not sure if I can make it (I'm a bit sick)

**Comment by mstruebing** [comment]
If the setting is in the neos-ui-package it means that when you update the UI and you are on neos 3.3 the button would be disabled by the update.

Is this what we want? If so we can proceed like Karsten said :)

**Comment by kdambekalns** [comment]
Another option: add it to the UI package as `true` and then override it in Neos 4.0 itself with `false`.

**Comment by kitsunet** [comment]
I guess that is okay-ish, although introducing settings to old versions is not exactly a great thing...

**Comment by mstruebing** [comment]
I'm closing this and making a new one, because when changing the base more and more commits gets added to this PR. https://github.com/neos/neos-development-collection/pull/2026

**Pull request closed without merging**
