### PR TITLE
BUGFIX: Initialize dimension preset config with empty array

### PR DESCRIPTION
**Pull request by daniellienert**

### CODE REVIEW

**Comment by kitsunet** [comment]
Makes sense, will merge in 24h if on objections.

**Comment by robertlemke** [comment]
Looks good

**Comment by aertmann** [comment]
@kitsunet: this issue is related to the package ordering issue I mentioned.. it's basically just fixing a symptom, so you won't see the problem

see https://discuss.neos.io/t/flow-node-repair-php-error/1090/6?u=aertmann

**Comment by daniellienert** [comment]
@aertmann I already feared that I only patch up a symptom... So we should fix the real issue first.

**Comment by kitsunet** [comment]
I still think this change is not bad IMHO.

**Comment by aertmann** [comment]
but this doesn't even fix it really, it makes sense but it really should be fixed by adding

    TYPO3\TYPO3CR\Domain\Service\ConfigurationContentDimensionPresetSource:
      properties:
        configuration:
          setting: TYPO3.TYPO3CR.contentDimensions

to `TYPO3.TYPO3/Configuration/Objects.yaml`. Keeping the default as `[]` is fine too if that is done.

**Pull request merged**
