### PR TITLE
 FEATURE: Sortable options in selector editors (select, references, asset list)

### PR DESCRIPTION
**Pull request by kitsunet**
Enables drag and drop sorting of selected elements in selector, references and assets list.

All select lists with multiple selections are made sortable.

NEOS-374 #resolve
NEOS-1521 #resolve

### CODE REVIEW

**Comment by dfeyer** [comment]
Oh you rock ;)

Really good change, so remark:

- Maybe add the cursor: ns-resize to help use know when they can drag'n drop
- After selecting a new element the Apply button is not active, if I drag'n drop one item it become active, and I can apply

**Comment by kitsunet** [comment]
@dfeyer fixed the issue, I actually removed the update lines in my change...

**Comment by dfeyer** [comment]
I will test it again today

**Comment by kdambekalns** [comment]
Works fine, just the cursor style hint on it being sortable… should that be in place, @kitsunet?

**Comment by kdambekalns** [comment]
Seems `neos-ui-drag-handle` just isn't styled as expected. Anyone plans to do that?

**Comment by aertmann** [comment]
hey ho, working a little on in improving the user experience when dragging the elements based on some research for other sortable solutions.

Additionally implemented sorting for the select editor.

:+1: from my side and thanks @kitsunet for the initial implementation

**Comment by kitsunet** [comment]
Sweet thanks! Will check that later and try to get it merged with @kdambekalns help.

**Comment by kdambekalns** [comment]
:+1: by reading, tested it with the asset list an content references elements.

**Pull request merged**
