### PR TITLE
BUGFIX: Allow to have no space between value and opening confinement

### PR DESCRIPTION
**Pull request by dimaip**
Fix regression caused by multi-line EEL support.

NEOS-60 #comment fixes a regression introduced by this

### CODE REVIEW

**Comment by aertmann** [comment]
:+1: good catch

**Comment by kdambekalns** [comment]
Looks fine, and I guess we can trust the test.

**Comment by skurfuerst** [comment]
Good catch :)

**Comment by dimaip** [comment]
The kind of catch nobody from the team could catch, as I'm the only one who (used to) write such shitty TS code :dancers:

**Comment by aertmann** [comment]
:D

**Pull request merged**
