### PR TITLE
TASK: Improve asset replacement. 

### PR DESCRIPTION
**Pull request by davidspiola**
Keep asset adjustments if asset size did not change.

**What I did**
I added a condition to compare the size of the old and new asset in order to verify size did not change. In this case the method refit() will not be executed to keep asset adjustments. This is very handy if you upload/replace a image with enriched meta data (eg. IPTC or Exif)

### CODE REVIEW

**Comment by kitsunet** [comment]
Test failure related to: https://github.com/neos/neos-development-collection/pull/1553

**Comment by davidspiola** [comment]
@kitsunet is this pull request still ok? #1153 is already merged. I'm not sure if there is something to do from my end.

**Comment by kdambekalns** [comment]
I restarted the build, now it should pass, if all is well.

**Comment by kdambekalns** [comment]
Oh, well. One of the jobs is hanging in "booting" state, due to https://www.traviscistatus.com/incidents/bnt2wtxpgs39

**Comment by davidspiola** [comment]
I accidentally closed it. Opened a new one #1597. Sorry, still learning a log :-)

**Pull request closed without merging**
