### PR TITLE
TASK: Add support for array keys in AbstractCollectionImplementation

### PR DESCRIPTION
**Pull request by dfeyer**
This change add ```itemKey``` property to support processing array and get
the value of the keys:

    prototype(Vendor.Package:PackageRequirements) < prototype(TYPO3.TypoScript:Collection) {
      itemKey = 'identifier'
      itemName = 'node'
    }

In this example, the variable ```identifier``` contain the array key and
```node``` the array value.

### CODE REVIEW

**Comment by dfeyer** [comment]
:+1: pretty useful when working with raw array in TS

**Comment by kitsunet** [comment]
Looks good :+1:

**Comment by robertlemke** [comment]
:+1:

**Comment by robertlemke** [comment]
Ah, forgot: should this be documented somewhere? An example in the docs would be nice.

**Comment by dfeyer** [comment]
@robertlemke I just update the TYPO3.TypoScript:Collection reference documentation. I think it's enough.

**Pull request merged**
