### PR TITLE
[TASK] Add brief section about ``loadingDepth`` node tree setting

### PR DESCRIPTION
**Pull request by gerhard-boden**
and created new documentation file about configuration

### CODE REVIEW

**Comment by aertmann** [comment]
Maybe it makes sense to add a note about the section being a stub like it's done in http://neos.readthedocs.org/en/latest/CreatingASite/MultiSite.html

**Comment by dimaip** [comment]
Hey @gerhard-boden, thanks for documenting this important setting!

Don't know how much it applies to docs commits, but usually we write commit headers in present imperative tense: https://discuss.neos.io/t/commit-message-style/507

**Comment by gerhard-boden** [comment]
thanks for the feedback guys! Just made the changes

**Comment by aertmann** [comment]
Looks pretty good to me, however we should consider if we'd want to add it to the 2.0 (stable) documentation and not only master. What do you think?

If so you need to close the PR and create a new one from the branch targeting 2.0 instead

**Comment by gerhard-boden** [comment]
that's a thing i wasn't sure. Wrote the lines yesterday evening before going to bed and to be honest i was too lazy to check if that feature came with 2.0, or what branch i should target. will reopen a new pull request for 2.0

**Comment by gerhard-boden** [comment]
Here is the new one: 
https://github.com/neos/neos-development-collection/pull/174

**Comment by kdambekalns** [comment]
Thanks!

**Pull request closed without merging**
