### PR TITLE
TASK: Refactor AssetController in the Media Browser

### PR DESCRIPTION
**Pull request by dfeyer**
This change is first iteration to refactor the AssetController and make it slimer and easier to work with. The current AssetController as a lots of responsability. This first step extract the relatedNodes action to a specific controller. We need to forward the request from the AssetController, because of how we use the routing in backend module

### CODE REVIEW

**Comment by dfeyer** [comment]
If you agree with this change the next candidate will be:
- [ ] Tag management -> TagController
- [ ] Asset Collection management -> AssetCollectionController

Then the AssetController should be more focus on Asset handling ;)

**Comment by dfeyer** [comment]
The proxy method in the AssetController are not elegant, but our current architecture for backend module doesn't allow any other solution ... we are promotting fat controller here :(

**Comment by dfeyer** [comment]
Maybe the policy need a bit more love the extract all the proxy method and move them to the specific policy (ManageTags, ManageAssetCollections, ...)

**Comment by kitsunet** [comment]
I like. Good foundation for a react rewrite and creating APIs for it. Would merge soon-ish.

**Pull request merged**
