### PR TITLE
TASK: Adjust usage of packages to changes in Flow

### PR DESCRIPTION
**Pull request by kitsunet**

### CODE REVIEW

**Comment by kitsunet** [comment]
For: https://github.com/neos/flow-development-collection/pull/1280

**Comment by kitsunet** [comment]
this _should_ build now that the change in Flow is merged.

**Comment by bwaidelich** [comment]
This fixes master and since Travis seems to be very busy atm, I'll just go ahead and merge this one

**Comment by kitsunet** [comment]
<3

**Pull request merged**
