### PR TITLE
BUGFIX: Use a dynamic URL for user impersonation

### LINKED ISSUE #4797: BUG: Login As (user impersonation) not working with subfolders
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When working in a Neos installation in a subfolder, the user impersonation functionality doesn't work and I get an error saying "Could not switch to the selected user." In Neos installations without subfolder, it's working fine.

### Expected Behavior

It should always be possible to switch users, regardless of using subfolders or not.

### Steps To Reproduce

1. use a Neos installation in a subfolder (e.g. www.myproject.com/subfolder/neos)
2. go to User Management
3. click on the crossed arrows at the very end of the table row for any user

### Environment

```markdown
- Flow: 8.0 (?)
- Neos: 8.0
- PHP:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by markusguenther**
As described in the issue, the impersonation does not work when Neos is running in a subfolder. This change adds a data attribute with a dynamic URL to the DOM, and the user impersonation is using this module URL as base.

Fixes: #4797

**Review instructions**

Use the user impersonation in the Backend modules (User Management and other) when Neos is running in a subfolder.
e.g. BASEURL.com/cms/neos

**Checklist**

- [x] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [X] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [x] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [x] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Comment by markusguenther** [comment]
This PR needs also an adjustment in the Neos-UI and will be linked soon.

**Comment by mhsdesign** [comment]
Hmm usually we avoid string concatenating routes in the frontend (see neos ui)
so i would prefer to boot the impersonation with server calculated endpoints instead of this as this is always rather flaky and also hard to track usages of this endpoint that way:

```js
this._basePath + 'user-change'
this._basePath + 'status'
this._basePath + 'restore'
```

but its your feature do as you feel fit :D

**Comment by markusguenther** [comment]
@mhsdesign Yes that would be better but with Fluid you just have the ```<f:uri.action controller="Impersonate" package="Unikka.LoginAs" action="impersonateUserWithResponse" format="json" />``` and this will lead to a not so nice URL. So I thought it would work better with that. I also thought about a new Helper for `_getBasePath` but I think the little duplication is ok here, as we don't use it somewhere else.

**Comment by markusguenther** [comment]
Ok, we don't need the UI adjustment as we already use the dynamic URL here.
https://github.com/markusguenther/neos-ui/blob/b575442d2700b429485c06b90119182d50720124/Resources/Private/Fusion/Backend/Root.fusion

**Comment by ahaeslich** [comment]
Just tested it in a project using this "subfolder" setup:

- Changing the user: ✅ works
- Redirect to Neos backend afterwards: ❌ doesn't work in both places (menu button and user administration)

We need to change the usage of `window.location.pathname = '/neos'` in both JS files:

https://github.com/neos/neos-development-collection/blob/d246fea3daebd96149fbc2f42661c5c454c0e40d/Neos.Neos/Resources/Public/JavaScript/Components/TopBar/UserMenu.js#L94

https://github.com/neos/neos-development-collection/blob/d246fea3daebd96149fbc2f42661c5c454c0e40d/Neos.Neos/Resources/Public/JavaScript/Module/Administration/UserManagement.js#L83

**Comment by ahaeslich** [comment]
@markusguenther I also found `window.location.pathname = '/neos'` in the UI:

https://github.com/neos/neos-ui/blob/38774df6064c977026b1bd518b90aa12ee2e9ef9/packages/neos-ui-sagas/src/UI/Impersonate/index.js#L41

**Comment by markusguenther** [comment]
We now have another PR in the Neos-UI https://github.com/neos/neos-ui/pull/3713

**Review by ahaeslich — APPROVED** [review]
Tested it with success in combination with neos/neos-ui#3713. 

I agree with @mhsdesign about the server calculated endpoints. We for sure can change this when we refactor the user backend module to not use fluid anymore.

**Comment by mhsdesign** [comment]
Thanks :D I dont know fluid well enough but i trust you so consider this as half approval ;)

**Review by mhsdesign — APPROVED** [review]
By reading ;)

**Review by dlubitz — APPROVED** [review]
Looks good by reading!

**Comment by mhsdesign** [comment]
Still not a fan of the uri concatenation on the client, even if the uri would be uglier if generated from the server.
Buuut i never stumbled upon this know and never before and as this is just a bugfix lets do it :D

**Pull request merged**
