### PR TITLE
BUGFIX: Handle non-existing workspaces gracefully

### PR DESCRIPTION
**Pull request by dlubitz**
On replay a projection, the workspaces might not be available anymore. We need to ignore these cases on cache flush.

This was already implemented in a earlier version, but got lost on last rewrite. 
See: https://github.com/neos/neos-development-collection/pull/5221/files#diff-008f3460b749dbf869e63ba0602a1501990fa09cc37cd7fdaca6afa3789017e4L143-L146

### CODE REVIEW

**Review by mhsdesign — APPROVED** [review]
Thanks i also prepared to fix that in https://github.com/neos/neos-development-collection/pull/5261 ^^ see https://github.com/neos/neos-development-collection/pull/5261/commits/5c1f1579f921155ad8c91536d3d7b218c893b97b

**Review by bwaidelich — APPROVED** [review]

**Comment by mhsdesign** [comment]
as this line is a little unnecessary expensive (it runs for all `onBeforeEvent` _and_ `onAfterEvent`, if we handle the event or not) and is generally odd to have and should (tm) be not necessary after beta 15 as we require all beta users to clean old events https://discuss.neos.io/t/neos-9-beta-15-release/6701

which should fix 

> The source workspace missing does not exist

which was only there because of this migration https://github.com/neos/neos-development-collection/blob/4d65f9c1b576f90b516492227df17cdb9c7cf341/Neos.ContentRepositoryRegistry/Classes/Service/EventMigrationService.php#L491


i think we can revert this hack again :D

**Comment by dlubitz** [comment]
Why is this expensive, if it usually shouldn't happen? And why not keeping this as a safeguard?

**Comment by mhsdesign** [comment]
well i see the code in `onAfterEvent` changed a little: https://github.com/neos/neos-development-collection/blob/aa96fc8814f4f2b44bbb29e71bc8b8c381dc3ab6/Neos.Neos/Classes/AssetUsage/CatchUpHook/AssetUsageCatchUpHook.php#L65

now the hook is run for all events, and `getContentGraph` is currently uncached :D

ill refactor this when i deactivate the asset hooks for replay!

**Comment by dlubitz** [comment]
But we need the ContentGraph anyway. Maybe we should pass it to the handling methods.

**Comment by mhsdesign** [comment]
Reverted now via https://github.com/neos/neos-development-collection/pull/5502

**Pull request merged**
