### PR TITLE
TASK: Add fusionObjects `RawMenu`, `RawDimensionsMenu` and `RawBreadcrumbMenu`

### PR DESCRIPTION
**Pull request by mficzel**
Add fusionObjects `Neos.Neos:RawMenu`, `Neos.Neos:RawDimensionsMenu` and `Neos.Neos:RawBreadcrumbMenu`

The fusion objects return arrays of objects with the properties `node`, `state`, `label` and `menuLevel`. The `RawDimensionsMenu` additionally returns the keys `dimension` and `targetDimensions` for each item.

All fusion-configurations that do not belong to rendering from `Neos.Neos:Menu`, `Neos.Neos:DimensionsMenu` and `Neos.Neos:BreadcrumbMenu`
are supported.

### CODE REVIEW

**Comment by mficzel** [comment]
If this gets approval i will add documentation in another commit to this PR. So please leave feedback.

**Comment by mficzel** [comment]
Thinking about this i like the result but dislike the naive implementation wich leads to the FusionObject inheritance hierarchy AbstractArray -> Template -> AbstractMenu -> Menu -> RawMenu. Does anyone has a suggestion how this can be done better.

Maybe AbstractMenu -> RawMenu -> Menu (+Template Trait) could be a solution but would this be backwards compatible?

**Comment by aertmann** [comment]
@mficzel yeah would be a bit odd, would think it's possible to do in a backwards compatible way

**Comment by mficzel** [comment]
I started a discussoion that also contains this topic https://discuss.neos.io/t/rfc-cleanup-fusion-prototype-names/3646

**Comment by mficzel** [comment]
I decided to abandon this in favotr of pure flowQuery solution.

**Pull request closed without merging**
