### PR TITLE
Fix test fails

### PR DESCRIPTION
**Pull request by nezaniel**
This fixes some code parts that made the tests fail

### CODE REVIEW

**Review by ahaeslich — APPROVED** [review]

**Comment by bwaidelich** [comment]
Sorry to sound like a broken record, but could we get rid of the max length restriction?
It's really hard to see the actual diff because most changes are just cosmetical.

(for the record: I'm totally happy with the automatic styling fixes in general, but  adding a new parameter to a method should not automatically affect multiple lines and IMO https://github.com/neos/neos-development-collection/blob/959a23cfa8e3391730d319b2d816c0b61f4b8ba5/Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php#L587-L590 is easier to comprehend than https://github.com/neos/neos-development-collection/blob/8067f9475e3c2bfad44e7a2612fc70bb53ae9a05/Neos.Neos/Classes/FrontendRouting/Projection/DocumentUriPathProjection.php#L587-L597 for example)

**Review by bwaidelich — APPROVED** [review]

**Comment by nezaniel** [comment]
By all means, let's drop the line size hard limit, as that ist not part of PSR-12 anyway.
A soft limit is, though, so that wouldn't keep me personnaly from eliminating horizontal scroll bars wherever I run into them. 
As for your example I strongly disagree, as I prefer having one parameter per line (at least if there is more than one) since I can get an instant overview over what's happening - especially in combination with PhpStorm's parameter name hints or even named arguments since PHP8.
But that's a topic for a broader discussion I guess ^^

**Comment by bwaidelich** [comment]
> But that's a topic for a broader discussion I guess

Yes, you're right. I'll just add one more thought to clarify my intention:

> that wouldn't keep me personnaly from eliminating horizontal scroll bars wherever I run into them

Absolutely! And I'm not against shorter lines at all :D (lets agree to disagree on the example above, it's just a matter of taste and habit probably).
My concern is more: harder to read PRs and unrelated changes. Might sound like a minor issue, but I have to deal with this on a daily basis, where I git blame a line of code and have to dig for the actual reason for the line because it has been touched multiple times :)


On a different note: Thanks a lot for fixing the tests! <3

**Comment by ahaeslich** [comment]
> My concern is more: harder to read PRs and unrelated changes.

I can absolutely relate with that. But as long as it is a separate commit, which was the case here that I liked, it's fine I think.
We actually use this pattern (separate commit) on a daily basis for every case like this.

**Pull request merged**
