### PR TITLE
BUGFIX: Build correct paths to nodes with hidden parents

### PR DESCRIPTION
**Pull request by kdambekalns**
If a node is visible but lies beneath a hidden parent, the URI path
generated for that node had "holes" and did not work. This adjusts the
route part handler to return the complete URI including the URI path
segments of hidden nodes in the chain up to the site node.

Additionally this adjusts the route part handler to return the node,
unless it itself is hidden.  This makes it possible to show visible nodes
beneath hidden parents.

### CODE REVIEW

**Comment by kdambekalns** [comment]
Questions:

- is this a new feature or a bugfix, which would be the best branch?
- is this behaviour desired, or should those nodes rather never be linked?
- do we need this "recursivity" to be configurable, maybe?

**Comment by kitsunet** [comment]
Careful, IMHO it was a designated "feature" that hiding a parent meant that children won't be accessible due to this anymore.

**Comment by kdambekalns** [comment]
Yeah, but then at least

- build no URI to it
- or build a correct URL to it

Both can be achieved with just the first commit of this PR. That was a generated link will start to work as soon as the parent is set to be no longer hidden.

**Comment by kitsunet** [comment]
true that

**Comment by baschny** [comment]
@kitsunet At least our customer currently doesn't want this "feature", as the node is still indexed (i.e. elasticsearch), but with a wrong buggy URL.

So after unhiding the intermediate nodes the URL in the index is still wrong and I cannot reach that node through the search.

The node is accessible anyway if someone knows the correct URL to it, so there is little security benefit of this "feature / bug". :)

**Comment by baschny** [comment]
FYI, Karsten build this fix for our customer, so I will put that in production today and can report back here if I find any unforeseen problems with it.

**Comment by kdambekalns** [comment]
> The node is accessible anyway if someone knows the correct URL to it

Well, only with this change. Without the "second commit" it will not be found, as long as any of the parents are still hidden.

**Comment by kdambekalns** [comment]
Obviously some tests need to be checked and potentially adjusted, but what about the question of the intended/desired behaviour? Any other feedback on that?

As said, the second commit can be dropped to just build correct links but leave them inaccessible…

**Comment by baschny** [comment]
@kdambekalns I would then opt for leaving the second commit out to avoid the security discussions (and the change of behaviour). The correct URL generation is all we (at least for our project) need to get fixed.

**Comment by dfeyer** [comment]
Hiding a parent to hide a branch of the website is currently a feature and need stay like this. 

I'm fine if the URI generation create a valid URI, but the rendering of this URI must be a 404 or at least not some in the 20x range.

**Comment by kdambekalns** [comment]
Ok, I dropped making child nodes of hidden parents accessible and targeted this at 2.3 (since I considered it a bugfix to begin with). See #1654.

**Pull request closed without merging**
