### PR TITLE
[BUGFIX] Set useful defaults for Menu

### PR DESCRIPTION
**Pull request by kitsunet**
Menu should have useful defaults for ``entryLevel`` and
``maximumLevels`` to make it useable in it's default state
without changing too much.
The ``entryLevel`` is therefore set to 1 and maximumLevels to 2.
Maximum shouldn't be too high to avoid loading a lot of nodes
unnecessarily.

### CODE REVIEW

**Comment by aertmann** [comment]
I do agree to the change, however it's a breaking one.. Did you consider that? Probably not a good idea to include in a patch release. It could be done as a ``[!!!][TASK]`` instead.

**Comment by kitsunet** [comment]
Right, the tests say the same. I would say I change to master branch and make it a breaking task as you suggested. 2.0 users will have to live with adding those lines themselves.

**Comment by bwaidelich** [comment]
any news on this one?

**Comment by kitsunet** [comment]
replaced by https://github.com/neos/neos-development-collection/pull/195 for master.

**Pull request closed without merging**
