### PR TITLE
BUGFIX: ImageMagick PDF to Image sometimes results in black background

### PR DESCRIPTION
**Pull request by gerdemann**
**What I did**
I want to convert a PDF with transparencies into a thumbnail

**How I did it**
I use the DocumentThumbnailGenerator.

**How to verify it**
Try to convert this (https://goo.gl/xKMEC2) PDF-File

### CODE REVIEW

**Comment by kitsunet** [comment]
I encountered that as well, but it's entirely a problem of the PDFs and how ImageMagick deals with it in that case, nothing we can fix IMHO. You might want to try ImageMagick bugtracker, although by now I suspect this is a feature not a bug. The PDF in question has in fact no background, most readers default to a white background, but apparently ImageMagick does not and defaults to black apparently. We _can_ try to solve that in our converter but IMHO the PDF is at fault as it doesn't specify the background.

**Comment by bwaidelich** [comment]
I had a similar issue recently with ImageMagick and no approach worked reliably (flatten image, set a background manually, ...).. I ended up using [VIPS](https://jcupitt.github.io/libvips/)

**Comment by gerdemann** [comment]
@kitsunet Okay, you're right, that seems to be a problem primarily with the PDF and/or Imagemagick.
But in our current converter we are already flattening layers. Is there any reason not to flatten for the alpha channels as well?

@bwaidelich Did you use VIPS for the DocumentThumbnailGenerator? Could you perhaps provide me with your code?

**Comment by bwaidelich** [comment]
> Did you use VIPS for the DocumentThumbnailGenerator?

No, sorry, I only used it "manually" in a Flow project and am very happy with the result.
I know that there are imagine adapters in the making (see https://www.liip.ch/en/blog/libvips-adapter-for-php-imagine for example) that might just work "out of the box". But mind that it requires the vips php extension to be installed.

**Comment by jasinai** [comment]
I think we had this problem a year ago. 
With GhostScript 9.06 and 9.10, it was the 'right' thumbnail preview.
With GhostScript >= 9.14, it was the black version. Perhaps this bugfix has something to do with it: http://git.ghostscript.com/?p=ghostpdl.git;a=commitdiff;h=4e44c995bcc7a2aa6c32e23cb73fd532a93f5b1c
I don't know, if this helps at all.

**Comment by bwaidelich** [comment]
Please test this carefully. When I tried to solve this with IM I got some weird side effects when using the various flags (i.e. suddenly different PDFs rendered without background)

**Pull request closed without merging**
