### PR TITLE
BUGFIX: Check for Imagick in DocumentThumbnailGenerator

### LINKED ISSUE #3678: Neos tries to render thumbnails for PDFs - but the default config of ImageMagick on Ubuntu denies reading PDFs
Since it's only checked that Imagick is available, several of our Neos instances started to try to render thumbnails for PDFs - running into an issue, since the default config of ImageMagick on Ubuntu denies reading PDFs (see the `/etc/ImageMagick-6/policy.xml` file).

In a first step we just modified that policy file to allow reading PDFs which works, but this issue also applies to other Document formats like Word files.

We're aware that we can disable rendering thumbnails per document type - but this is kind of cumbersome in >90 Neos installations of a whole fleet of customer setups.

So if one of you sees a generic solution to this, I'm all ears :-)

One approach I'd see would be to not only check if the `imagick` PHP-Module is loaded, but also if it's config allows the current document type to be read. Somehow, PHP **must** be aware of that config from the policy.xml file, as changing it does not change Neos behaviour unless the php-frpm process is restarted.

Or alternatively put the effective generation of thumbnails for Documents into a try/catch block and if getting a thumbnail fails, do

1. ignore this (e.g. do not write out an Exception file)
2. fall-back to showing the icon file instead of the thumbnail from the effective file

_Originally posted by @mrimann in https://github.com/neos/neos-development-collection/issues/3617#issuecomment-1079117378_

### PR DESCRIPTION
**Pull request by kdambekalns**
The `DocumentThumbnailGenerator` will now (again) check for
Imagick being the configured driver in `canRefresh()`. If the
`imagick` PHP extension is available and should  be used even
though Imagick is _not_ the driver for Imagine, a new feature flag
can be turned on:

```yaml
Neos:
  Media:
    thumbnailGenerators:
      Neos\Media\Domain\Model\ThumbnailGenerator\DocumentThumbnailGenerator:
        # if set, the DocumentThumbnailGenerator will be used when possible, even if the
        # used Imagine driver would usually prohibit it's use (because GD doesn't do PDF)
        overrideImagineDriverCheck: true
```

If reading the source fails without an exception, an exception is
raised and passed on from the `refresh()` method. This e.g.
happens when the security policy of ImageMagick denies reading
PDF files.

See #3678

**Review instructions**

To have ImageMagick deny reading of PDF, as is needed to check this, the policy must be changed to include

    <policy domain="coder" rights="none" pattern="PDF" />

- the policy is usually in a place like `/etc/ImageMagick-6/policy.xml`
- for Local Beach it's inside the `php` container in `/opt/flownative/php/build/extensions/imagick/policy.xml`. To be able to edit it, you must use `docker exec -u root -it yourproject_php /bin/bash` to become `root` inside the container.

**Checklist**

- [x] Code follows the PSR-2 coding style
- [x] ~~Tests have been created, run and adjusted as needed~~
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked wit `!!!` and have upgrade-instructions

### CODE REVIEW

**Comment by DrillSergeant** [comment]
Does not work. When calling `$wasRead = $im->readImage($documentFile);` an exception is thrown:

```
Exception #1433109652 in line 49 of /var/www/vhosts/kb-staging.healthyplus.ch/httpdocs/releases/20220523114403/Data/Temporary/Production/Cache/Code/Flow_Object_Classes/Neos_Media_Domain_Strategy_ThumbnailGeneratorStrategy.php: Unable to generate thumbnail for the given document (filename: dummy.pdf, SHA1: 90ffd2359008d82298821d16b21778c5c39aec36)

27 Neos\Media\Domain\Model\ThumbnailGenerator\DocumentThumbnailGenerator_Original::refresh()
26 Neos\Media\Domain\Strategy\ThumbnailGeneratorStrategy_Original::refresh()
25 Neos\Flow\ObjectManagement\DependencyInjection\DependencyProxy::__call()
24 Neos\Media\Domain\Model\Thumbnail_Original::refresh()
23 Neos\Media\Domain\Service\ThumbnailService_Original::refreshThumbnail()
22 Neos\Flow\ObjectManagement\DependencyInjection\DependencyProxy::__call()
21 Neos\Media\Controller\ThumbnailController_Original::thumbnailAction()
20 Neos\Media\Controller\ThumbnailController::thumbnailAction()
19 Neos\Media\Controller\ThumbnailController::Flow_Aop_Proxy_invokeJoinPoint()
18 Neos\Flow\Aop\Advice\AdviceChain::proceed()
17 Neos\Flow\Security\Aspect\PolicyEnforcementAspect_Original::enforcePolicy()
16 Neos\Flow\Aop\Advice\AroundAdvice::invoke()
15 Neos\Flow\Aop\Advice\AdviceChain::proceed()
14 Neos\Media\Controller\ThumbnailController::thumbnailAction()
13 Neos\Flow\Mvc\Controller\ActionController_Original::callActionMethod()
12 Neos\Flow\Mvc\Controller\ActionController_Original::processRequest()
11 Neos\Flow\Mvc\Dispatcher_Original::initiateDispatchLoop()
10 Neos\Flow\Mvc\Dispatcher_Original::dispatch()
9 Neos\Flow\ObjectManagement\DependencyInjection\DependencyProxy::__call()
8 Neos\Flow\Mvc\DispatchComponent_Original::handle()
7 Neos\Flow\Http\Component\ComponentChain_Original::handle()
6 Neos\Flow\Http\Component\ComponentChain_Original::handle()
5 Neos\Flow\Http\Middleware\ComponentChainMiddleware_Original::process()
4 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::process()
3 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle()
2 Neos\Flow\Http\RequestHandler::handleRequest()
1 Neos\Flow\Core\Bootstrap::run()

Previous exception: Exception #499 in line 72 of /var/www/vhosts/kb-staging.healthyplus.ch/httpdocs/releases/20220523114403/Data/Temporary/Production/Cache/Code/Flow_Object_Classes/Neos_Media_Domain_Model_ThumbnailGenerator_DocumentThumbnailGenerator.php: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/408

28 Imagick::readimage()
27 Neos\Media\Domain\Model\ThumbnailGenerator\DocumentThumbnailGenerator_Original::refresh()
26 Neos\Media\Domain\Strategy\ThumbnailGeneratorStrategy_Original::refresh()
25 Neos\Flow\ObjectManagement\DependencyInjection\DependencyProxy::__call()
24 Neos\Media\Domain\Model\Thumbnail_Original::refresh()
23 Neos\Media\Domain\Service\ThumbnailService_Original::refreshThumbnail()
22 Neos\Flow\ObjectManagement\DependencyInjection\DependencyProxy::__call()
21 Neos\Media\Controller\ThumbnailController_Original::thumbnailAction()
20 Neos\Media\Controller\ThumbnailController::thumbnailAction()
19 Neos\Media\Controller\ThumbnailController::Flow_Aop_Proxy_invokeJoinPoint()
18 Neos\Flow\Aop\Advice\AdviceChain::proceed()
17 Neos\Flow\Security\Aspect\PolicyEnforcementAspect_Original::enforcePolicy()
16 Neos\Flow\Aop\Advice\AroundAdvice::invoke()
15 Neos\Flow\Aop\Advice\AdviceChain::proceed()
14 Neos\Media\Controller\ThumbnailController::thumbnailAction()
13 Neos\Flow\Mvc\Controller\ActionController_Original::callActionMethod()
12 Neos\Flow\Mvc\Controller\ActionController_Original::processRequest()
11 Neos\Flow\Mvc\Dispatcher_Original::initiateDispatchLoop()
10 Neos\Flow\Mvc\Dispatcher_Original::dispatch()
9 Neos\Flow\ObjectManagement\DependencyInjection\DependencyProxy::__call()
8 Neos\Flow\Mvc\DispatchComponent_Original::handle()
7 Neos\Flow\Http\Component\ComponentChain_Original::handle()
6 Neos\Flow\Http\Component\ComponentChain_Original::handle()
5 Neos\Flow\Http\Middleware\ComponentChainMiddleware_Original::process()
4 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::process()
3 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle()
2 Neos\Flow\Http\RequestHandler::handleRequest()
1 Neos\Flow\Core\Bootstrap::run()


HTTP REQUEST:
target: /media/thumbnail/3a18b7c2-1440-4854-8ee9-9d964e0849cf
Cookie: Neos_Session=RC7ydQYGxsGJy3Lkh1owfHkD6ykKExwd
Accept-Language: de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7
Accept-Encoding: gzip, deflate, br
Referer: https://kb-staging.healthyplus.ch/neos/management/media?moduleArguments%5B%40package%5D=neos.media.browser&moduleArguments%5B%40controller%5D=asset&moduleArguments%5B%40action%5D=index&moduleArguments%5B%40format%5D=html&moduleArguments%5B%40subpackage%5D=&moduleArguments%5B__referrer%5D%5B%40package%5D=Neos.Media.Browser&moduleArguments%5B__referrer%5D%5B%40subpackage%5D=&moduleArguments%5B__referrer%5D%5B%40controller%5D=Asset&moduleArguments%5B__referrer%5D%5B%40action%5D=index&moduleArguments%5B__referrer%5D%5Barguments%5D=YTowOnt94115b134149d980851f5c9191096346ae0dd1a27&moduleArguments%5B__trustedProperties%5D=a%3A0%3A%7B%7Dcf98ad47af67d5de5c504e530cfbd416e6a51732&moduleArguments%5BsearchTerm%5D=dummy&moduleArguments%5B__referrer%5D%5B%40package%5D=Neos.Media.Browser&moduleArguments%5B__referrer%5D%5B%40subpackage%5D=&moduleArguments%5B__referrer%5D%5B%40controller%5D=Asset&moduleArguments%5B__referrer%5D%5B%40action%5D=index&moduleArguments%5B__referrer%5D%5Barguments%5D=YToxOntzOjEwOiJzZWFyY2hUZXJtIjtzOjU6ImR1bW15Ijt94135ee32a01ff7f68a021bbfbb65413daffa6687&__referrer%5B%40package%5D=Neos.Neos&__referrer%5B%40subpackage%5D=&__referrer%5B%40controller%5D=Backend%5CModule&__referrer%5B%40action%5D=index&__referrer%5Barguments%5D=YToxOntzOjY6Im1vZHVsZSI7YTozOntzOjY6Im1vZHVsZSI7czoxNjoibWFuYWdlbWVudC9tZWRpYSI7czoxMDoiY29udHJvbGxlciI7czo0NjoiXE5lb3NcTWVkaWFcQnJvd3NlclxDb250cm9sbGVyXEFzc2V0Q29udHJvbGxlciI7czo2OiJhY3Rpb24iO3M6NToiaW5kZXgiO31951f95b502ddaeab22482cf35ce86c667b484a601&moduleArguments%5B__trustedProperties%5D=a%3A0%3A%7B%7Dcf98ad47af67d5de5c504e530cfbd416e6a51732&moduleArguments%5BsearchTerm%5D=
Sec-Fetch-Dest: image
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
Accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8
Sec-Ch-Ua-Platform: "Windows"
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua: " Not A;Brand";v="99", "Chromium";v="101", "Google Chrome";v="101"
Host: kb-staging.healthyplus.ch
Content-Length: 
Content-Type: 

HTTP RESPONSE:
200

PHP PROCESS:
Inode: 2628744
PID: 1612730
UID: 1003
GID: 1003
User: kb-staging

    [array] => 
        previousException:
        [string] => Exception #499 in line 72 of /var/www/vhosts/kb-staging.healthyplus.ch/httpdocs/releases/20220523114403/Data/Temporary/Production/Cache/Code/Flow_Object_Classes/Neos_Media_Domain_Model_ThumbnailGenerator_DocumentThumbnailGenerator.php: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/408

```

I assume this exception should be catched and thumbnail generation aborted in that moment.

**Comment by kdambekalns** [comment]
Ok, this works for me (I actually checked, yay!)

**Comment by DrillSergeant** [comment]
@kdambekalns Now we have a different behaviour: No Exceptions is thrown while trying to generate a thumbnail (good), but now we get another exception in the ThumbnailController:
```
22-06-28 09:35:14 3711642    CRITICAL                       Exception #1450178437 in line 49 of /var/www/vhosts/kb-staging.healthyplus.ch/httpdocs/releases/20220602062850/Data/Temporary/Production/Cache/Code/Flow_Object_Classes/Neos_Media_Controller_ThumbnailController.php: Could not generate URI for static thumbnail "092bf306-fdd3-4fd0-9901-4d0b3614a5ef". - See also: 202206280935146b3328.txt
```
This exception is repeated every time I reload the media module in my browser and once for every pdf-file that has no thumbnail at this moment.

I would expect the media module to show a pdf-icon instead of a thumbnail and that no exceptions are thrown in such a case.

**Comment by kdambekalns** [comment]
Ok, the `ThumbnailGeneratorStrategy` works by iterating over the available strategies, asking for `canRefresh()` and return after the first "yes" to that question. If the actual rendering failed, you get no thumbnail and later run into your new error.

If the strategy would try to continue after a failure, it would eventually come by the `IconThumbnailGenerator` and fetch the (expected) PDF icon.

Now, just ignoring an error there seems like a bad idea, but logging it might cause unexpected amounts of log and stacktrace data to be written:

`22-06-29 16:16:34 3688       DEBUG     Neos.Media           Neos\Media\Domain\Model\ThumbnailGenerator\DocumentThumbnailGenerator.refresh() failed. Exception #1433109652 in line 67 of /…/Neos_Media_Domain_Strategy_ThumbnailGeneratorStrategy.php: Unable to generate thumbnail for the given document (filename: test.pdf, SHA1: 29936096c8f9c7fd0b145003d04632a2c38d8069) - See also: 20220629161633a67cec.txt`

[20220629161633a67cec.txt](https://github.com/neos/neos-development-collection/files/9012286/20220629161633a67cec.txt)

I implemented this, so please give it a try. Any opinions?

**Comment by kdambekalns** [comment]
The latest commit

1. Brings back the check for `$this->imagineService instanceof \Imagine\Imagick\Imagine` that https://github.com/neos/neos-development-collection/pull/3617 removed.
2. Adds a feature flag to be able to use the `DocumentThumbnailGenerator` even when not using `\Imagine\Imagick\Imagine`, solving the need expressed in https://github.com/neos/neos-development-collection/pull/3617 without changing existing behaviour.

**Review by kitsunet — APPROVED** [review]

**Comment by kitsunet** [comment]
@Sebobo would super appreciate if you gave this alos a a look after you already approved the other PR in the "series" 😆

**Review by Sebobo — APPROVED** [review]
Looks good

**Pull request merged**
