### PR TITLE
BUGFIX: make sure NotoSans font is loaded correctly

### LINKED ISSUE #4005: BUG: Incorrect Noto Sans font paths in Neos.Neos package
### Description

At least the Noto Sans font paths in the Neos.css and the Includes-built.css of the Neos.Neos package are incorrect, as they are
```
../Fonts/NotoSans/NotoSans-Regular.ttf
```
instead of
```
../Fonts/NotoSans-Regular.ttf
```
The organization of the fonts has probably been flattened recently without adjusting the paths. The other CSS files in the same package have correct paths, e.g. Lite.css, Login.css, etc.

### Steps to Reproduce

1. Include the Neos.css stylesheet in the backend template of an arbitrary document type.
2. Apply `style='font-family: "Noto Sans", sans-serif;'` to an arbitrary text element of that template. 
3. Verify that the text is not rendered in Noto Sans and that the browser console displays an appropriate error for the missing font.

#### Expected behavior

The text should be rendered in Noto Sans.

#### Actual behavior

The text is rendered in the fallback font.

### Affected Versions

Neos: 9.0, 8.2, 7.3, 5.3

### PR DESCRIPTION
**Pull request by crydotsnake**
**Upgrade instructions**

**Review instructions**

Resolves: #4005 

Make sure the NotoSans font is loaded from the correct path.

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [x] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [x] Reviewer - The first section explains the change briefly for change-logs
- [x] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Comment by Sebobo** [comment]
@crydotsnake did you check when and why this broke? I'm surprised that nobody noticed until now.

**Review by Sebobo — APPROVED** [review]
Looks fine by reading. We should have a follow up issue to replace the ttf fonts with woff2 like we did in the Neos.Ui.

**Comment by ahaeslich** [comment]
@Sebobo & @crydotsnake

> @crydotsnake did you check when and why this broke? I'm surprised that nobody noticed until now.

That kind of question makes me curious. Apparently the paths are broken since 02. September 2019 😲 and the updated folder structure was introduced with Neos 5.0.

And as for the not noticing: When are those includes really used? In most cases the NotoSans files are loaded because Lite.css is included or they are loaded form the Neos.Ui package.

**Review by ahaeslich — COMMENTED** [review]
To change these files in the public folder don't seem right. They appear to be deprecated files which should not be used anymore.

Why? 

- All other files in this folder are generated via webpack. And in the webpack config the `Neos.scss` file is transformed to `Main.css`. 
- These two files are missing the additional sourcemap files which are generated via webpack.
- I could only find one place in the development collection which includes one of these files. And this is the current (old) media module.

So my question is: should we fix the paths or delete these files?

**Comment by Sebobo** [comment]
I thought the same, but the creator of https://github.com/neos/neos-development-collection/issues/4005 must have encountered an issue with them?
I would prefer getting rid of them and fixing whatever place still used them.

**Comment by alexander-nitsche** [comment]
My use case was this [PR](https://github.com/breadlesscode/neos-nodetypes-folder/pull/20) for the Breadlesscode.NodeTypes.Folder package: It should use the Font Awesome icons of the Neos.Neos package and at the same time be compatible down to Neos 4 LTS. In Neos 4 and 5 there was no Lite.css, Minimal.css etc. but only the Neos.css. So I decided to use this and became aware of the incorrect file paths. 

I would recommend fixing these paths once now with this PR, and in a follow up issue the Neos.css could still be completely replaced.

**Comment by Sebobo** [comment]
Ah thx, now I remember that we needed the styles as fallback for the modules that don't use the new style files. But we could also find a better solution for that and remap the filename or something.

**Comment by Sebobo** [comment]
@ahaeslich so should we merge this then like it is and follow-up in another issue/pr?

**Comment by ahaeslich** [comment]
@Sebobo 👍

**Review by ahaeslich — APPROVED** [review]

**Comment by alexander-nitsche** [comment]
> The PR is created against the lowest maintained branch

As the bug also occurs down to Neos 5.3: Will it be backported?

**Comment by Sebobo** [comment]
@alexander-nitsche no, 5.3 is out of the bug fixing timeframe.

**Pull request merged**
