### PR TITLE
[BUGFIX] Fix PHP 5.3 compatibility issues

### PR DESCRIPTION
**Pull request by kdambekalns**
The 1.2 branch should be compatible to PHP 5.3, but since we did not have automated
testing in place on that version of PHP, some incompatibilties have crept in.

This fixes those issues and enables the unit and functional tests to be run on PHP 5.3
on Travis CI.

### CODE REVIEW

**Comment by kitsunet** [comment]
YAY, thanks!

**Comment by kdambekalns** [comment]
_phew_

**Comment by aertmann** [comment]
very good, thanks so much for taking care :+1:

@kdambekalns might be easier if you merge and take care of the up merge to 2.0?

**Comment by kdambekalns** [comment]
Yes, will merge and upmerge. Thanks.

**Pull request merged**
