### PR TITLE
BUGFIX: Select box editor unselect styling

### PR DESCRIPTION
**Pull request by aertmann**
Regression from the new dropdown styling.

### CODE REVIEW

**Comment by aertmann** [comment]
Broken:
image
Fixed:
image

**Comment by gerhard-boden** [comment]
Never could reproduce the issue with the double magnifier (event used excactly the same field for testing), but the line was too short when closing the select box. 

Tested in Firefox, Chrome and IE 11 on Windows 10. Looks good now, thanks! :+1:

**Comment by aertmann** [comment]
thanks for reviewing 😄 

@gerhard-boden: as mentioned in the comment it's due to a media query so you probably don't match it

**Comment by gerhard-boden** [comment]
@aertmann ah, thanks for the info! Do not see the comment :(. But I'm glad it's not a Win/Mac issue because i want to live in a world where the browsers show the same output on both systems. :wink:

**Pull request merged**
