### PR TITLE
TASK: Aloha update and fix

### PR DESCRIPTION
**Pull request by aertmann**
Updates Aloha Editor to closest maintained version (1.1.5 to 1.2.42)

No new features used (only bugfixes)

Additionally fixes a bug with the toolbar buttons overflowing

### CODE REVIEW

**Comment by aertmann** [comment]
Tried 1.4, but that caused problems with the link plugin so just went for 1.2 since it's still maintained and all we really want is the latest bugfixes

**Comment by aertmann** [comment]
:+1:

**Comment by skurfuerst** [comment]
:+1: - good job!

**Comment by kdambekalns** [comment]
:+1:

**Pull request merged**
