### PR TITLE
FEATURE: ``isParentNodeOf`` node privilege operation

### PR DESCRIPTION
**Pull request by skurfuerst**

### CODE REVIEW

**Comment by skurfuerst** [comment]
migrated from https://review.typo3.org/#/c/41975/

**Comment by bwaidelich** [comment]
Nice one. The commit/PR message could use some tweaking and the PR needs to be rebased. Besides a test would be nice of course ;)

**Comment by dfeyer** [comment]
@bwaidelich @skurfuerst Can you update this PR ? Can we target it to 3.3 ?

**Comment by johannessteu** [comment]
Duplicate to #477 ?

**Comment by kitsunet** [comment]
Can we get some status update here please?

**Comment by bwaidelich** [comment]
Closing in favor of #477  (I'll take care of that one asap!)

**Pull request closed without merging**
