### PR TITLE
BUGFIX: Only move children with the same dimensionHash in setPath()

### LINKED ISSUE #1696: Cut & paste across pages with dimensions loses ContentCollection child nodes
### Description

When cutting and pasting nodes with content collection children in a site with dimensions, content collections get lost during publishing.

### Steps to Reproduce

1. Set up the demo site (`composer create-project neos/neos-base-distribution=2.3.16 testsetup`, migrate DB, import site, create user)
2. Create two pages in _en_US_, named _Test 1_ and _Test 2_
3. On _Test 1_ create a two-column element
4. In the first column of that element, create another two-column-element
5. Switch language to _de_, choose "Create & Copy" when asked
6. Publish all changes
7. Switch back to _en_US_
8. Cut the nested two-column element
9. Paste it into the _Test 2_ page
10. Publish all changes

#### Expected behavior

One of:

- the children of the moved two-column element move along (only!) in _en_US_
- the paste is not allowed

since the target does not exist in _de_.

#### Actual behavior

The ContentCollection children of the moved element are left at their original location. This leads to missing children in the new location and orphaned (old) nodes.

This can be seen (partly) by looking at the _Test 1_ page in _de_ using the structure tree - the nested two-column element lost it's children (_column0_ and _column1_), even though the _de_ variant of the content wasn't touched at all.

test_1_-_neos_demo_site

The multi-column rendering of TYPO3.Neos.NodeTypes does not produce any immediate errors now, since the children to be rendered are collected using

	columns = TYPO3.TypoScript:Collection {
		collection = ${q(node).children('[instanceof TYPO3.Neos:ContentCollection]')}
		itemRenderer = TYPO3.Neos.NodeTypes:MultiColumnItem
	}

so that simply nothing is rendered.

If one uses Fusion code like this, rendering breaks with an exception:

 	column0 = TYPO3.Neos:ContentCollection {
		nodePath = 'column0'
	}

This is because the explicitly requested node is not found.

### Affected Versions

Neos: seen in 2.3.13, 2.3.14 and 2.3.16

### PR DESCRIPTION
**Pull request by kdambekalns**
This changes the code in setPath() to no longer move all children
across all dimension value combinations. Instead only children with
the same dimensionsHash as the currently moved node will be moved
along.

This avoids errors like the one described in #1696.

Fixes #1696

### CODE REVIEW

**Comment by kdambekalns** [comment]
Thanks to @nlx-lars for finding the issue and providing a first description of how to reproduce it.

**Comment by nezaniel** [comment]
Shouldn't all variants of that node be moved as well? (Variants as in everything connected further down the fallback graph)

**Comment by kdambekalns** [comment]
Well… I know that we want to keep documents of the same dimensions values at the same place[1], but in this case content is cut and pasted to a page that exists in one language, but not the other. So, in other words, there is "no place to paste german".

It seems that keeping documents together still works, since the Behat tests aiming at that still pass. But of course they might be incomplete…

[1] Actually breaking a "promise" of the dimensions feature, where we wanted to make entirely different structures for different dimensions possible, still allowing to keep "translations" connected. But, well. That's another story…

**Comment by kdambekalns** [comment]
Ping… I really would love some help with that. There is a bug, but it seems we also have a conceptual issue here!?

**Comment by nezaniel** [comment]
I think this needs at least some conceptual clarification / decision being made. I have a pretty clear understanding about how I'd expect specializations of content to behave in such a case, but I'm not sure whether all of us agree ^^

**Comment by kdambekalns** [comment]
Hi everyone, a client just had what seems to be the issue addressed by this. How can we continue here?

**Comment by DrillSergeant** [comment]
Hi guys. I just slacked with @kdambekalns about this. We really have an serious issue with our client here. He did some nodetree-movements (drag&drop) and afterwards, the content in another dimension was broken. Took me hours to repair the other dimension.
But even worse: my client wants to restructure his node-tree from time to time. Right now they stopped the restructuring process because of the bug but it's hard to explain that node-movements are not allowed in Neos.
I hope we can find a solution soon here. I am willing to help as good as I can.

**Comment by DrillSergeant** [comment]
This is getting urgent on our side, after we informed our customers (it's several projects) they reacted even worse than expected. I hope we can provide a solution here soon. I am availabe on slack (https://neos-project.slack.com/team/U08TGAKB6) for any ideas/discussions and would help as much as I can.

In our most projects there is a dimension-fallback defined, which means the content on a page is a mixture of the shine-through fallback-dimension and some single content-nodes that are modified in the other dimension. So I think moving only one dimension would break the site, too.

**Comment by kitsunet** [comment]
This sounds sensible, even IF we wanted to move all variants at some point this doesn't happen at the moment because if you look closely we move children in all dimensions but not the variants of the node itself. So I would like to merge this and as I said a while ago, for the rewritten CR we should write down these usecases and expected behaviors...

**Comment by kdambekalns** [comment]
The issue seems indeed to be caused (or at least made worse) by having dimensions. Add some more trouble for having fallbacks(?).

@nezaniel Would you share you clear conceptual understanding? Maybe we _do_ agree, after all…

**Comment by DrillSergeant** [comment]
Thanks for merging. I could test soon. Our project runs Neos 3.2 right now. Is there a chance to test it there? I could also update the project to 3.3 before, if needed.

**Comment by kdambekalns** [comment]
@DrillSergeant Right now the fix is only merged into 2.3. I am doing upmerges currently, running tests "as we speak". So, as soon as those are pushed (I'll announce that in #neos-nore-dev in Slack), you can test on 3.2.x-dev, if you like.

**Comment by kdambekalns** [comment]
FYI: The upmerges have all been pushed, so all branches have the fix by now. Test as much as you like (and can).

**Comment by DrillSergeant** [comment]
Thanks to all involved people for your quick responses. I cannot wait to test it, bad luck I am stuck in meetings untill tomorrow afternoon. But I will give feedback asap.

**Comment by DrillSergeant** [comment]
First test: works nicely. Will rollout to staging and involve some more people to test.

**Pull request merged**
