### PR TITLE
BUGFIX: Deletion of assets from media overview works again

### LINKED ISSUE #3349: BUG: Error occurs when trying to delete an asset in the media UI
### Description

An error occurs when trying to delete an asset in the media UI in Neos.
We tested it with a fresh installation of Neos, so no other package should have an impact.

**Error message:**  
```
Exception in line 477 of /var/www/html/Data/Temporary/Development/SubContextDocker/Cache/Code/Flow_Object_Classes/Neos_Flow_Mvc_Controller_ActionController.php: Argument 1 passed to Neos\Media\Browser\Controller\AssetController::deleteAction() must be an instance of Neos\Media\Domain\Model\Asset, null given, called in /var/www/html/Data/Temporary/Development/SubContextDocker/Cache/Code/Flow_Object_Classes/Neos_Flow_Mvc_Controller_ActionController.php on line 477

43 Neos\Media\Browser\Controller\AssetController::deleteAction(NULL)
42 Neos\Flow\Mvc\Controller\ActionController_Original::callActionMethod()
41 Neos\Flow\Mvc\Controller\ActionController_Original::processRequest(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Mvc\ActionResponse)
40 Neos\Flow\Mvc\Dispatcher_Original::initiateDispatchLoop(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Mvc\ActionResponse)
39 Neos\Flow\Mvc\Dispatcher_Original::dispatch(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Mvc\ActionResponse)
38 Neos\Neos\Controller\Backend\ModuleController_Original::indexAction(array|3|)
37 Neos\Neos\Controller\Backend\ModuleController::indexAction(array|3|)
36 Neos\Neos\Controller\Backend\ModuleController::Flow_Aop_Proxy_invokeJoinPoint(Neos\Flow\Aop\JoinPoint)
35 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
34 Neos\Flow\Security\Aspect\PolicyEnforcementAspect_Original::enforcePolicy(Neos\Flow\Aop\JoinPoint)
33 Neos\Flow\Aop\Advice\AroundAdvice::invoke(Neos\Flow\Aop\JoinPoint)
32 Neos\Flow\Aop\Advice\AdviceChain::proceed(Neos\Flow\Aop\JoinPoint)
31 Neos\Neos\Controller\Backend\ModuleController::indexAction(array|3|)
30 Neos\Flow\Mvc\Controller\ActionController_Original::callActionMethod()
29 Neos\Flow\Mvc\Controller\ActionController_Original::processRequest(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Mvc\ActionResponse)
28 Neos\Flow\Mvc\Dispatcher_Original::initiateDispatchLoop(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Mvc\ActionResponse)
27 Neos\Flow\Mvc\Dispatcher_Original::dispatch(Neos\Flow\Mvc\ActionRequest, Neos\Flow\Mvc\ActionResponse)
26 Neos\Flow\Mvc\DispatchMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
25 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
24 Neos\Flow\Http\Middleware\SecurityEntryPointMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
23 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
22 Neos\Flow\Http\Middleware\RequestBodyParsingMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
21 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
20 Neos\Flow\Mvc\FlashMessage\FlashMessageMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
19 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
18 Neos\Flow\Http\Middleware\PoweredByMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
17 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
16 Neos\RedirectHandler\RedirectMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
15 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
14 Neos\Flow\Mvc\Routing\RoutingMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
13 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
12 Neos\Neos\Routing\RequestUriHostMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
11 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
10 Neos\FluidAdaptor\Core\Widget\AjaxWidgetMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
9 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
8 Neos\Flow\Http\Middleware\SessionMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
7 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
6 Neos\Flow\Http\Middleware\TrustedProxiesMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
5 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
4 Neos\Flow\Http\Middleware\StandardsComplianceMiddleware_Original::process(GuzzleHttp\Psr7\ServerRequest, Neos\Flow\Http\Middleware\MiddlewaresChain)
3 Neos\Flow\Http\Middleware\MiddlewaresChain_Original::handle(GuzzleHttp\Psr7\ServerRequest)
2 Neos\Flow\Http\RequestHandler::handleRequest()
1 Neos\Flow\Core\Bootstrap::run()
```

### Steps to Reproduce

1. Go to the media module in the Neos backend
2. Click `Delete` in the dropdown on an asset
3. Error occurs

#### Expected behavior

The asset should be deleted without an error.

#### Actual behavior

The asset is not deleted and it comes to an error.

### Affected Versions

Neos: `7.1.0`

Flow: `7.1.0`

### PR DESCRIPTION
**Pull request by kdambekalns**
Fixes #3349

### CODE REVIEW

**Comment by kdambekalns** [comment]
**Note:** This is untested and just a best guess from reading the code… 😎

**Comment by mhsdesign** [comment]
## its a partial fix.

seems like a good guess ;)

It fixes for me the second case of two problems: [2 asset deletion errors](https://github.com/neos/neos-development-collection/issues/3349#issuecomment-856534701)
- I tested it (shortly) with PHP 7.4 and Neos/Flow 7.1

----------

But the first case ([2 asset deletion errors](https://github.com/neos/neos-development-collection/issues/3349#issuecomment-856534701)), the deletion error from within the 'Content module', is not fixed with this code.
The 'deletion message' `Do you really want to delete asset "{0}"?` is unchanged and so is the console output and the php error.

**Comment by markusguenther** [comment]
> **Note:** This is untested and just a best guess from reading the code… 😎

Arg that is a thing we did not find in the review then.
The name tools was not nice and  therefore it has been renamed to helpers :/

**Comment by markusguenther** [comment]
https://user-images.githubusercontent.com/1014126/123410717-e8672900-d5af-11eb-8eda-8e524ebaece9.mp4

Adjusted the code bit for the content-module. Sorry for the inconveniences.

**Comment by kdambekalns** [comment]
Test failures are unrelated…

**Review by kdambekalns — COMMENTED** [review]
Gets a solid 👍 from me. Thanks @markusguenther!

**Comment by markusguenther** [comment]
I broke it, so I need to fix it ;)

**Pull request merged**
