### PR TITLE
!!!TASK: Replace occurrences of 'typoScript' with 'fusion'

### PR DESCRIPTION
**Pull request by cvette**
* Deprecates methods with 'TypoScript' in name
* Replaces 'typoScript' with 'fusion' in variable names, doc blocks

### CODE REVIEW

**Comment by albe** [comment]
Wait, we can't just sneak in deprecations in a release version, right? So this would need to be targeted at master, meaning it will land only in 3.2

**Comment by kitsunet** [comment]
IMHO doesn't make a difference as removal will only happen in 4.0 anyway. But our rule is to mark changes which deprecate something as breaking so people see early..

**Comment by daniellienert** [comment]
I would prefer to extract the breaking part to a separate PR against master and target the non breaking / internal / docblock stuff against 3.0. Would be a pity to see those occurrences of TypoScript for two more versions.

**Comment by kitsunet** [comment]
Mmm, a second after merging I thought we might have wanted to postpone this to master to at least not do it in a bugfix version, but \o/

**Comment by kitsunet** [comment]
Meehh, it actually has test failures after merging now :/ So debating if I either fix them or revert and we move this to master...

**Comment by albe** [comment]
What kind is the breaking test? If it's only related to the name changes I'd say fix test

**Comment by kdambekalns** [comment]
FYI: I'll take care of that, checking the failures so we can asses a solution.

**Comment by kdambekalns** [comment]
Seemed to be only two tests, see https://travis-ci.org/kdambekalns/neos-development-collection/builds/234025428 - if that passes, I'll push that to origin/3.0 directly. Unless someone objects…

**Comment by kdambekalns** [comment]
Pushed, results will be at https://travis-ci.org/neos/neos-development-collection/builds/234058158

**Comment by kitsunet** [comment]
<3

**Pull request merged**
