### PR TITLE
FEATURE: Add `ContentRepository::subgraphForNode`

### PR DESCRIPTION
**Pull request by mhsdesign**
Seeing code like this

```php
$subgraph = $this->contentRepositoryRegistry->subgraphForNode($node);
$nodeTypeManager = $this->contentRepositoryRegistry->get($node->contentRepositoryId)->getNodeTypeManager();
```

this seems just double because the contentRepository is fetched twice and not passed
```php
$subgraph = $this->contentRepositoryRegistry->subgraphForNode($node);
$contentRepository = $this->contentRepositoryRegistry->get($node->contentRepositoryId);
$contentRepository-> ...
```

makes me rethink if were not going to far with `contentRepositoryRegistry->subgraphForNode`, id like to fetch the cr more often in code directly and then get the subgraph:

```php
$contentRepository = $this->contentRepositoryRegistry->get($node->contentRepositoryId);
$subgraph = $contentRepository->subgraphForNode($node);
$nodeTypeManager = $contentRepository->getNodeTypeManager();
```

**Upgrade instructions**

**Review instructions**

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Comment by nezaniel** [comment]
I guess the reason for this not existing is that the node might not even belong to the given content repository

**Comment by mhsdesign** [comment]
touché we could add a content repository id check

**Comment by mhsdesign** [comment]
```
public function subgraphForNode(Node $node): ContentSubgraphInterface
{
    return $this->subgraphForIdentity(ContentSubgraphIdentity::fromNode($node));
}

public function subgraphForIdentity(ContentSubgraphIdentity $identity): ContentSubgraphInterface
{
    if (!$this->id->equals($identity->contentRepositoryId)) {
        throw new ForeignContentRepositoryUsed(
            sprintf('ContentRepository "%s" cannot get subgraph for Node of ContentRepository "%s".', $this->id->value, $node->contentRepositoryId->value),
            1715531407
        );
    }
    return $this->getContentGraph($identity->workspaceName)->getSubgraph(
        $identity->dimensionSpacePoint,
        $identity->visibilityConstraints
    );
}

public function subgraphFor(WorkspaceName $workspaceName, DimensionSpacePoint $dimensionSpacePoint, VisibilityConstraints $visibilityConstraints): ContentSubgraphInterface
{
    return $this->getContentGraph($workspaceName)->getSubgraph(
        $dimensionSpacePoint,
        $visibilityConstraints
    );
}
```

as of now we concluded that shortcuts like these are not worth it yet

**Comment by mhsdesign** [comment]
Discussion moved to https://github.com/neos/neos-development-collection/issues/5065

**Pull request closed without merging**
