### PR TITLE
TASK: Improve styling of checkboxes

### PR DESCRIPTION
**Pull request by aertmann**
- Changes the check icon
- Always show a check icon
- Improves hover / focus states

### CODE REVIEW

**Comment by aertmann** [comment]
image

**Comment by johannessteu** [comment]
If i hover a checkbox i get the blue border. If i click then the green background is only visible if i leave the field with the mouse, but should also be visible on label hover

**Comment by aertmann** [comment]
@johannessteu I disagree, hence I implemented it that way.. before you had no visual feedback if it had been modified

**Comment by aertmann** [comment]
okay something was wrong, sorry should be correct now

image

**Comment by johannessteu** [comment]
Yup, great! 👍

**Comment by gerhard-boden** [comment]
Windows 10, Firefox, Chrome, IE11 Subtle change, but makes sense once you see it in action :+1:

**Comment by aertmann** [comment]
thanks for testing 😃

**Comment by robertlemke** [comment]
Hey there. I like the new style apart from always showing a check mark, even if the box is unchecked. What's the idea behind that? I was about to report it as a bug ;-)

**Comment by dfeyer** [comment]
Same from me. Pretty annoying UX wise to see three state for a checked box

**Comment by aertmann** [comment]
it was suggested by Cristoph Ono, see https://jira.neos.io/browse/NEOS-1173

the goal is to make it easier to see it's actually a checkbox/radio button and not just some box

personally prefer it to befeore thus don't agree with you on this one, but maybe it should be more subtle.. just used the existing "textSubtle" color we already have

**Comment by kitsunet** [comment]
I do like this change as well, it needs a little getting used to and yes maybe the contrast could be just a tiny bit less but all in all it shows nicely "this is a checkbox".

**Pull request merged**
