### PR TITLE
!!! TASK: Move `ContentRepositoryId` to `SharedModel` namespace

### PR DESCRIPTION
**Pull request by mhsdesign**
Originally the content repository didnt know its id but with the change https://github.com/neos/neos-development-collection/pull/4310 we added it.
Thats why i presume the `ContentRepositoryId` lived in the factory namespace.
But since we now like to expose it in the ContentRepository and in the to be conceptualised NodeIdentity the idea about its location changed. The dto does no longer belong to the `Factory` namespace.

> `ContentRepositoryId` should not be in that namespace o.O

_Originally posted in https://github.com/neos/neos-development-collection/pull/4868#discussion_r1489431550_
            

**Upgrade instructions**

Instead of referencing `Neos\ContentRepository\Core\Factory\ContentRepositoryId` you should reference `Neos\ContentRepository\Core\SharedModel\ContentRepository`

(That can as well be a simple string replace)

**Review instructions**

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Comment by mhsdesign** [comment]
Ui adjustments https://github.com/neos/neos-ui/pull/3717

**Review by bwaidelich — APPROVED** [review]
Makes sense, thanks for taking care!

**Review by dlubitz — APPROVED** [review]
OMG ... this means we also have to adopt all external packages. 🙈

**Comment by mhsdesign** [comment]
jup, but we already have to because of the workspaces and subtree tags 😅 

and its not that widely used, for example pure fusion packages wont be affected.

Anke and me discussed that after this week we should probably check on a few packages ^^

**Pull request merged**
