### PR TITLE
[BUGFIX] Make PluginView label translatable

### PR DESCRIPTION
**Pull request by aertmann**
Fixes: NEOS-1540

### CODE REVIEW

**Comment by dfeyer** [comment]
:+1:

**Comment by patrickreck** [comment]
:+1:

**Comment by daniellienert** [comment]
:+1:

**Comment by aertmann** [comment]
Rebased

:+1:

**Comment by aertmann** [comment]
Please review https://github.com/neos/neosdemotypo3org/pull/1

**Pull request merged**
