### PR TITLE
9.0: TASK: Simplify command handler resolution

### PR DESCRIPTION
**Pull request by bwaidelich**
Replaces the explicit `if/elseif` blocks by simple checks
for a corresponding `handle*` method

### CODE REVIEW

**Comment by skurfuerst** [comment]
@bwaidelich I personally find the explicit if/else more explicit, so that would be my slight preference; but I'm also totally fine merging this change :) whatever you prefer!

**Comment by bwaidelich** [comment]
@skurfuerst I turned all the `handle*` methods *private* now (some weren't yet) and added some `@noinspection PhpUnusedPrivateMethodInspection` annotations to satisfy the IDE.
But I get your point and, yes, it won't be statically type-checked like this.

Maybe there's a third option to get rid of the large amount of repetition like:
image

And IMO we should go for a single approach (not use `if/else` in one handler, and `match` in others).

What about this:

```php
public function canHandle(CommandInterface $command): bool
{
    return method_exists($this, 'handle' . (new \ReflectionClass($command))->getShortName());
}

public function handle(CommandInterface $command, ContentRepository $contentRepository): EventsToPublish
{
        return match ($command::class) {
            SetNodeProperties::class => $this->handleSetNodeProperties($command, $contentRepository),
            // ...
        }
}
```

**Comment by bwaidelich** [comment]
@skurfuerst I like that final version now, what do you think?

**Comment by skurfuerst** [comment]
really nice :) let's get this in!

**Pull request merged**
