### PR TITLE
TASK: Clean up and fix .gitgnore files a bit

### PR DESCRIPTION
**Pull request by kdambekalns**

### CODE REVIEW

**Comment by kdambekalns** [comment]
IMHO this is simply a bit easier to understand. Also, the paths starting with `/` in the "lower levels" did not match anything.

**Comment by kdambekalns** [comment]
@robertlemke

**Comment by aertmann** [comment]
this would change how we do things, so far we've pushed the css files but not the built ones to make it easier to review without having to run the scripts after pulling..

not sure about it tbh., but can accept the change if people are in favor of having to run the scripts when reviewing changes with css modifications

**Comment by kdambekalns** [comment]
@aertmann Not behaviour change with this… files already tracked are never influenced by `.gitignore`, so we could even remove the exclusion of the built css and js as well. It's just a cleanup I did after trying to understand potential reasons for the built JS missing today…

And I don't get the thing about "running the scripts" - nothing is changed in that regard with this, no?

If I'm on the wrong track, correct me, of course!

**Comment by aertmann** [comment]
ah sorry my bad, got confused.. you just moved things into one file.. yeah should be fine

**Pull request merged**
