### PR TITLE
TASK: Remove deprecated VIE schema

### PR DESCRIPTION
**Pull request by Sebobo**
This schema was required for the Aloha editor which is not supported by Neos anymore.
Backend modules were still loading this schema, so this might help making them a slightly more responsive on initial load.

### CODE REVIEW

**Comment by Sebobo** [comment]
@mficzel do you want this cleanup task (with a bit of performance benefit) still in 8.0? Then I can also change the target branch.

**Comment by mficzel** [comment]
@Sebobo ... 8.0 is fine

**Review by kdambekalns — APPROVED** [review]
👏 – yay for 8.0 as target!

**Review by mficzel — APPROVED** [review]
Fine by reading

**Pull request merged**
