### PR TITLE
[BUGFIX] Node tree state out of sync with other components

### PR DESCRIPTION
**Pull request by aertmann**
When using the hide button and editing the title in the node trees, the state of other components like the publish menu wasn't updated accordingly. Additionally the node trees weren't updated when nodes were altered outside the trees. Several fixes are included in this change:

- Publish menu updated when modifying nodes in the tree (hidden/title)
- Context structure tree nodes updated when changed on the page
- Hidden button in trees updated correctly for active node
- Incorrect entity updated when modifying nodes in the tree

Resolves: NEOS-1474
Resolves: NEOS-1129

### CODE REVIEW

**Comment by aertmann** [comment]
:+1:

**Comment by aertmann** [comment]
look at the individual commits for easy reviewing

**Comment by dimaip** [comment]
In general: verified.
Found a tiny small quirk: when hiding a node with inline handles, the red cross appears next to the node in context tree, but the hidden button in context tree doesn't become blue. Not sure if it needs fixing though, as it's visible enough with the red cross.

**Comment by aertmann** [comment]
@dimaip: thanks, good catch master of review :) happens because it's only updated when the node selection changes, will fix and push update

**Comment by dimaip** [comment]
:+1: by reading, but can't verify at the moment

**Comment by kitsunet** [comment]
:+1: by reading

**Comment by aertmann** [comment]
thanks a lot guys :)

**Comment by dimaip** [comment]
thanks for your attention to details, awesome job! Now waiting for upmerge :)

**Comment by aertmann** [comment]
upmerge done

**Pull request merged**
