### PR TITLE
BUGFIX: Respect disabled superTypes when filtering by Node Type

### PR DESCRIPTION
**Pull request by bwaidelich**
This fixes `NodeType::isOfType()` to return `false` when the given
type is explicitly disabled by the corresponding NodeType or one of
it's super types.

Example:

    'Acme:Animal':
      superTypes:
        'Acme:HasBonesMixin': true

    'Acme:Jellyfish':
      superTypes:
        'Acme:Animal': true
        'Acme:HasBonesMixin': false

With this `NodeTypeManager::getNodeType('Acme.Jellyfish')->isOfType('Acme:HasBonesMixin')`
should return `false` but it didn't.
Respectively a FlowQuery like the following should not return any "Jellyfish"-node (or
nodes with a sub-type): `q(node).find('[instanceof Acme:HasBonesMixin]')` but it did.

Fixes: #1983

### CODE REVIEW

**Comment by daniellienert** [comment]
@bwaidelich, @kitsunet, @kdambekalns, @gerhard-boden, @beheist Great to have that fixed! I just had to restructure a lot in a project to work around that bug. But as this changes the behavior of supertype inheritance, this is really breaking and I really wonder why all of you think that this can go in as a normal bugfix.

**Comment by daniellienert** [comment]
@bwaidelich: Its not my work arounds that break - my workaround was to avoid setting supertypes to false whenever possible. But If someone uses that buggy construct, the "superType = false" settings suddenly takes effect. And that can be breaking in many ways. Thats why I wouldn't cover this great change in a normal bugfix, but give it some attention in the next minor release.

**Comment by kitsunet** [comment]
It made sense to me. IMHO fixing obviously wrong behavior constitutes not necessarily a breaking change. But I am open to revert this. Does some have a real world breaking scenario?

**Comment by kdambekalns** [comment]
It still makes sense to me. It is broken the old way, so if I tried to use it, I'd see it's not working and use some other way. If someone uses this as broken as it is, I am stumped.

But, whatever…

**Comment by daniellienert** [comment]
He guys, it wasn't meant as a real veto. If none of you sees the risk, that this might break things / causes strange behavior after a bugfix release - i'm fine with merging it.

**Comment by bwaidelich** [comment]
Sorry for the confusion, but I thought about this once again and came to the conclusion that it really doesn't make sense to change the behavior in a patchlevel release. Even if it's unlikely to break nobody will actually benefit. And _if_ it breaks it won't be in the form of an exception but by returning unexpected nodes which can be really nasty..
As you wrote that your are fine with reverting it, I'll go ahead re-open #2145 and push the fix (with  `!!!`) to the 4.0 branch.
Obviously you'll be free to veto :)

**Comment by kdambekalns** [comment]
Let's get over with it :)

**Pull request merged**
