### PR TITLE
BUGFIX: fixing searching in dimension select

### PR DESCRIPTION
**Pull request by samuelhauser**
this PR replaces #1662 (now is in correct branch)

### CODE REVIEW

**Comment by daniellienert** [comment]
Triggered style ci again.

**Comment by dfeyer** [comment]
@samuelhauser Can you rebase ?

**Comment by samuelhauser** [comment]
@dfeyer unfortunately I don't have the branch any more. Is there a way to reopen it or to checkout this pr and do the changes there?

**Comment by jonnitto** [comment]
Any progress on this?

**Pull request closed without merging**
