### PR TITLE
BUGFIX: Neos.NodeTypes prototypes are now ContentComponents

### LINKED ISSUE #4705: TASK: Check and fix Neos:NodeTypes packages
- Check Neos.NodeTypes packages:
  - after removal of fusion prototypes (#4537)
  - refactoring of Neos.Neos:Page (#4654)
  - refactoring of menu prototypes (#4623, #4671)
  - remove fluid rendering

Packages:

- [x] Neos.NodeTypes
  - [x] Adjust to refactored Neos.Neos:Page (#4704)
  - [x] Neos.NodeTypes:Headline (#4706)
  - [x] Neos.NodeTypes:Text (#4706)
  - [x] Neos.NodeTypes:Image
  - [x] Neos.NodeTypes:TextWithImage
- [x] Neos.NodeTypes.AssetList (#4706)
- [x] Neos.NodeTypes.ColumnLayouts (#4706)
- [x] Neos.NodeTypes.ContentReferences (#4706)
- [x] Neos.NodeTypes.Form
- [x] Neos.NodeTypes.Html (#4670)
- [x] Neos.NodeTypes.Navigation

### PR DESCRIPTION
**Pull request by ahaeslich**
After the removal of deprecated fusion prototypes (#4537) the fluid based rendering of prototypes contained in Neos.NodeTypes packages will throw the error `Warning: Array to string conversion` because of attribute handling in fluid templates.

**Upgrade instructions**

**Review instructions**

Best reviewed commit by commit.

**Checklist**

- [x] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Comment by kitsunet** [comment]
Nice! One could ask the academic question if having the "best practice" structure of fusion without actually having the naming for it (Neos.NodeTypes.Content:Something) is a good idea, but I don't think it's a huge problem. We _could_ put a variant with .Content. in the name besides the old ones and then at some point deprecate the old ones _shrug_

**Comment by ahaeslich** [comment]
> Nice! One could ask the academic question if having the "best practice" structure of fusion without actually having the naming for it (Neos.NodeTypes.Content:Something) is a good idea, but I don't think it's a huge problem. We _could_ put a variant with .Content. in the name besides the old ones and then at some point deprecate the old ones _shrug_

Yes, I struggled with myself how much I should cleanup. I was confused that in some packages all fusion prototypes reside in `Root.fusion`. In other packages not so much.

Then again I think @mficzel has some plans in mind to refactor those prototypes anyway ...

**Review by mficzel — APPROVED** [review]
fine by 👀

**Comment by mficzel** [comment]
For now those are best "Default" contents we have and it makes sense to keep them running. Once we have nested properties we should define new default nodetypes with proper semantic and deliver those without renderer easy theming.

**Comment by Sebobo** [comment]
Do we really want this nodetype name based class block with docs in each prototype?

Never liked that we show a technical implementation detail in the frontend this way.

**Comment by ahaeslich** [comment]
> Do we really want this nodetype name based class block with docs in each prototype?

🤷‍♀️ we can delete them if we don't want to add them as standard. Or is this something we can decide, when we refactor those packages for real? We should at least make the prototypes work in the next beta release.

**Comment by Sebobo** [comment]
Just a question when we want to make a breaking change.
IMO they could have a simple classname without all the magic.

**Comment by mhsdesign** [comment]
Hmmm. Thanks for providing a 100% 1to1 implementation. I wouldnt have gone to through the trouble of adding this 

>   attributes.class.@process.nodeType = ${Array.push(value, String.toLowerCase(String.pregReplace(node.nodeTypeName.value, '/[[:^alnum:]]/', '-')))}

everywhere. But as you did this already we might as well keep it :D (im not going to use these components anyway and awaiting for martins master plan to happen which will obliterate them out of existence.)

**Review by mhsdesign — APPROVED** [review]
thanks for removing the fluid rendering. I didnt check up on the actual implementation, but my thesis is that it cannot be worse than a fatal error of array to string conversion ;)

**Comment by ahaeslich** [comment]
Removing the magic css class wouldn't be that much trouble. Than I would also remove it in the HTML component which was the first one to be adjusted (see: #4670). 

And as we are removing fluid in almost all these protoypes it's breaky anyways for all of those who are expecting it. I did never use these protoypes ... therefore I don't have a strong affection for these classes anyway.

@mficzel any objections on removing them? If not I would adjust this PR to get it merged ASAP 😉

**Comment by kitsunet** [comment]
then it _might_ need to become a breaking change, people have used these classes to style components 🙈

I would rather merge as is

**Review by kitsunet — APPROVED** [review]

**Pull request merged**
