### PR TITLE
FEATURE: New FlowQuery filter operation ``!instanceof``

### PR DESCRIPTION
**Pull request by gerhard-boden**
This is the rebased version of this PR:
https://github.com/neos/neos-development-collection/pull/23

The essentials for flow have already been merged into master a while ago:
https://github.com/neos/flow-development-collection/commit/6cabed2e2f7ca2d72cd0f89f391fc21288596f87
But they have to be in the current flow release aswell. I guess this is also the reason why most of the tests fail.

NEOS-1321 #close

### CODE REVIEW

**Comment by kdambekalns** [comment]
Are you sure this can work with Flow 3.x? The change in Flow went into master, after 3.0 was branched off. So this change can only work on Neos master right now, because 2.0 depends on Flow 3.0…

**Comment by kdambekalns** [comment]
@gerhard-boden

**Comment by gerhard-boden** [comment]
@kdambekalns i see, so i'll create another PR targeting `neos:master`? Or what's the plan?

**Comment by kitsunet** [comment]
@gerhard-boden that would be nice and if you do that now there is a chance to get it merged still for 2.1

**Comment by gerhard-boden** [comment]
Home in 20 minutes, doing it right away

Christian Müller <notifications@github.com> schrieb am Di., 15. Dez. 2015,
19:45:

**Comment by kdambekalns** [comment]
Awesome, thanks!

**Comment by gerhard-boden** [comment]
another try: https://github.com/neos/neos-development-collection/pull/270 :)

**Pull request closed without merging**
