### PR TITLE
BUGFIX: Avoid fatal error when asset not available

### PR DESCRIPTION
**Pull request by kdambekalns**
This fixes what is basically a merge error. It lead to a method call
on an unset variable.

### CODE REVIEW

**Comment by kdambekalns** [comment]
Introduced with https://github.com/neos/neos-development-collection/pull/1745

**Comment by gerhard-boden** [comment]
@kdambekalns can you point be to the method call on the unset variable in this change? (sorry if it's really obvious)

**Comment by kdambekalns** [comment]
Sure: it would be `$asset->getFileExtension()`

**Comment by gerhard-boden** [comment]
Ah thanks, ofc, was moved inside the if statement with this 👍

**Comment by gerhard-boden** [comment]
and since we assume the `NeosAssetProxy` will always have a `asset` property set, right?

**Pull request merged**
