### PR TITLE
BUGFIX: #5234 Display site-name on neos login view

### LINKED ISSUE #5234: BUG: Backend Login screen no longer shows site-name
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There are two places in Neos.Neos:View.Login that reference `props.site.name.value`. Site::getName() returns a string however so there is no value-object to unwrap.

The login screen `/neos` no longer shows the name of the site but simply "Login to"

### Expected Behavior

The login screen should show the correct text "Login to {sitename}"

### Steps To Reproduce

_No response_

### Environment

```markdown
- Flow: 9.0.0-beta13
- Neos: 9.0.0-beta13
- PHP: 8.3
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by crydotsnake**
**Upgrade instructions**

_None_

**Review instructions**

Resolves: #5234 

Displays the `site-name` title in the Neos Login screen.

**Checklist**

- [x] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Comment by crydotsnake** [comment]
@mhsdesign I saw you changed the `Neos.Neos:View.Login` prototype the last time in june. Did you maybe forgot to change those lines?

The commit was: https://github.com/neos/neos-development-collection/pull/5168/commits/3518a343101a713cf5c804a3e6bf8ee7e0c0e6c5

**Review by kdambekalns — APPROVED** [review]
👍 by 👀

**Review by dlubitz — APPROVED** [review]
Looks good to me and works.

**Comment by mhsdesign** [comment]
thanks good catch thats on me :D

**Pull request merged**
