### PR TITLE
BUGFIX: Node property search with PostgreSQL 9.5

### PR DESCRIPTION
**Pull request by hlubek**
Adds an explicit string conversion which is needed for PostgreSQL > 9.4
to convert a JSON type to string. This is needed when matching a string
pattern in the NodeSearchService against the node properties.

NEOS-1873 #resolve

### CODE REVIEW

**Comment by hlubek** [comment]
Make sure to test this on PostgreSQL < 9.5, PostgreSQL 9.5 and MySQL

**Comment by hlubek** [comment]
The TravisCI build fails because of the backport to the 2.0 branch

**Comment by kdambekalns** [comment]
Please see https://github.com/hlubek/neos-development-collection/pull/1

**Comment by kdambekalns** [comment]
The only thing that makes me cringe is `TYPO3CR_TOSTRING`. Could we name it `NEOSCR_TOSTRING`? ;)

**Comment by hlubek** [comment]
@kdambekalns Sure, will do that in a few minutes

**Comment by kdambekalns** [comment]
❤️

**Comment by hlubek** [comment]
<strike>minutes</strike> hours...

**Pull request merged**
