### PR TITLE
FEATURE: Split useful NodeTypes into separate packages

### PR DESCRIPTION
**Pull request by rolandschuetz**
**What I did**
Move the more often used node type ContentReferences out of the NodeTypes package to allow separate usage without the more nasty parts of Neos.NodeTypes.

**How I did it**
I create a new package Neos.NodeTypes.ContentReferences. The Neos.NodeTypes package inherits Neos.NodeTypes:ContentReferences from Neos.NodeTypesContentReferences.:ContentReferences to provide backwards compability.

The Menu was renamed into Neos.NodeTypes.Navigation because Mac interprets ".Menu" folders as packages and I wanted to prevent any confusion.

The compromise is that we now have two NodeTypes with the same functionality (one of them abstract when the NodeTypes package is included). There should be a breaking change in Neos 4 to get rid of the old namespace.

**How to verify it**
Start a new neos-development-distribution with this [modified composer.json](https://gist.github.com/rolandschuetz/2bc4be4d71986c923cd35cd8aedc14dd).
Create a new node type ContentReferences, everything works like before.

**Checklist**
- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [master](https://www.neos.io/features/release-roadmap.html)
- [ ] Crowdin has been adjusted, if needed(?)
- [ ] Branching and release scripts have been updated to take care of (dependencies to) the new packages

### CODE REVIEW

**Comment by rolandschuetz** [comment]
@kdambekalns Vermutlich muss hier CrowdIn angepasst werden. Kann ich das machen?

**Comment by dimaip** [comment]
ja ja

**Comment by kdambekalns** [comment]
I'll check… Need to get up to speed with the Crowdin itegration anyway again.

**Comment by kdambekalns** [comment]
Also see #1559 and #1561

**Comment by rolandschuetz** [comment]
@kdambekalns
Damn. #1559 seems to party implement this as well, but misses moving all non-english translations.

At the code sprint after some discussion we felt that the less usefull nodetypes like Headline should not be separated out. Diacussion included Christian Müller, Dmitri and Markus. So #1561 should not be merged. Also it didn't move the translations.

In general it seems unclean that the package Neos.NodeTypes.Headline write to the namespace Neos.NodeTypes. 
This pull request implements the new namespace and maps it back for compability to not break projects relying on the package.

**Comment by rolandschuetz** [comment]
It would be good to merge this pull request soon. Since there are MANY file changes future merge conflicts are very likely if that issue stays open long time!

**Comment by rolandschuetz** [comment]
@dfeyer I think this combines some aspects of #1561 and #1559
Could you help me push this feature to be accepted?

**Comment by dfeyer** [comment]
@rolandschuetz  I can try to push this during the sprint, rebase, calling hard for review and merge ;)

**Comment by dfeyer** [comment]
@robertlemke I will prefere to have a clean migration and not the compatibility layer, or if the compatibility layer is REALLY required, we should provide it in a separate package (and if possible an optional one).

**Comment by rolandschuetz** [comment]
@dfeyer This package would be the compatibility layer and the preferred way would be to include the necessary subpackages. That's why Intefactored everything usefull intonseparate packages.

I'll be at the whole sprint, so happy to help here during the sprint

**Comment by dfeyer** [comment]
Upmerged master, and TRUE/FALSE fixes, did quiet some test and I think it's merge ready, if we agree on the split level ;)

**Comment by kdambekalns** [comment]
So, I had a look at this, and to be honest: don't worry about Crowdin, that needs to be evaluated and re-enabled anyways…

As far as the split jobs go, you need to create the repositories for the new split targets and add the new packages to https://github.com/neos/slicer/blob/master/config.json.

**Comment by kdambekalns** [comment]
I had another look at this and discussed a bit with @dfeyer. The change is fine, and all the stuff I inquired about is taken care of, good work.

There is just one thing left: If you decide to follow through on clean code and want to get rid of the "legacy" NodeTypes package, you are left with the task of cleaning up. Usually for needed changes we'd provide migrations for code, DB, CR as needed. But In this case those migrations have no clear "home". And regardless of where you put them, you'd need to run them when removing the leagyc package, not earlier.

So I suggest to come up with clear instructions on the needed search/replace in Fusion and YAML files as well as SQL statements for the DB. Those instructions should be in the PR message (and thus release notes). This way we can clearly communicate when you need to apply them and not try to find some weird way to run them at the right point in time…

**Comment by dfeyer** [comment]
@rolandschuetz Can you writte down a short procedure how to migrate from the legacy, like @kdambekalns said two weeks ago ?

I think it's a good idea, and finally we can have this one merged ;)

**Comment by kitsunet** [comment]
Alright I merged master again. I will merge this if travis is green, migration documentation or not. IMHO this is more of a future invest for new projects. And as we don't have a good guide to get started with best practices this will need to be documented anyway.

**Comment by kdambekalns** [comment]
Thanks for merging and creating the new repositories and adjusting the slicer config! ❤️

**Comment by rolandschuetz** [comment]
@kdambekalns Sorry for writing back so later. Most people who use the old Neos NodeTypes do actually extend or modify their behavior. I don't have enough experience with writing DB migrations that I would feel comfortable providing a solution here.

**Pull request merged**
