### PR TITLE
[BUGFIX] Loading content dimensions for dimensions selector

### PR DESCRIPTION
**Pull request by aertmann**
Regression introduced with c8ee304082e4b5bea28beec33f1f7bd8f7730225

Resolves: NEOS-1722

### CODE REVIEW

**Comment by aertmann** [comment]
:+1: merging as it's simple and critical

sorry about breaking it :/

**Comment by hphoeksma** [comment]
I see this is still an issue on 2.0.5 ?

**Comment by aertmann** [comment]
highly doubt that, works fine for me on multiple sites

**Comment by kitsunet** [comment]
JS cache?

**Comment by aertmann** [comment]
argh a silent error :/ will push a fix

**Comment by aertmann** [comment]
@hphoeksma @kitsunet see #257

**Pull request merged**
