### PR TITLE
TASK: Homepage should hide uriPathSegment

### LINKED ISSUE #4621: `Neos.Neos:Site` NodeType should not show `uriPathSegment` property
We briefly discussed this in our weekly:
Actually the `uriPathSegment` property should not be part of the homepage.
It would be rather nasty to remove the property from this type even though it is declared in the super type.. But I would say that this is the most pragmatic solution in this case. _If_ the following works:

```yaml
Neos.Neos:Site:
  'Neos.Neos:Document': true
  properties:
    'uriPathSegment': ~
```

(untested!)

Otherwise we should at least disable the UI editor for this property

_Originally posted by @bwaidelich in https://github.com/neos/neos-development-collection/pull/4563#discussion_r1358029375_

### PR DESCRIPTION
**Pull request by mhsdesign**
Resolves #4621

Neos Ui adjustments: https://github.com/neos/neos-ui/pull/3686

instead of martins suggested solution https://github.com/neos/neos-development-collection/issues/4621#issuecomment-1772415808 i decided for a simpler and less hacky way: we just hide the property from the inspector but the node technically still has this property: https://github.com/neos/neos-development-collection/pull/4563#discussion_r1359860395

image

**Upgrade instructions**

**Review instructions**

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Comment by mhsdesign** [comment]
As discussed in todays weekly https://github.com/neos/neos-development-collection/issues/4621#issuecomment-1888913198 we rather want to use a mixin to make sure the property is not existent.

**Comment by mhsdesign** [comment]
Reopening as discussed https://github.com/neos/neos-development-collection/issues/4621#issuecomment-1896623060

**Review by bwaidelich — APPROVED** [review]

**Comment by kitsunet** [comment]
That branch name....

**Review by kitsunet — COMMENTED** [review]
ok ok, I guess I won't get my uriPath-less base type :/ sad panda.

**Review by kitsunet — APPROVED** [review]

**Comment by mhsdesign** [comment]
yes copy and paste error idk 😂

**Pull request merged**
