### PR TITLE
!!! TASK: Extract the `layout` root matcher from Neos.Neos and move it over to Neos.NodeTypes

### PR DESCRIPTION
**Pull request by mficzel**
Since the `layout` property is defined in `Neos.NodeTypes`, the `layout`-matcher is
moved to `Neos.NodeTypes` aswell.

If your project relies on the `layout` or `subpageLayout` property but does not use
`Neos.NodeTypes` you have to configure the layout matcher on your own.

### CODE REVIEW

**Comment by kdambekalns** [comment]
Is `layout` mentioned somewhere in the documentation?

**Comment by mficzel** [comment]
@kdambekalns i adjusted the section for http://neos.readthedocs.io/en/stable/HowTos/SelectingPageTemplate.html a bit to make it clear where that originates from. Other occurences of `layout` in the docs refer to fluid or are examples for node-properties in general.

**Comment by gerhard-boden** [comment]
Thanks! Tested this with our demo page (which is using the layout property) and everything seems to be working just fine. 
Strange side fact: Had to rebase this branch locally on master, otherwise I would run into an unrelated low level Flow exception when trying to test it.  Not sure if it will also brake after merging, but maybe just rebase on master just to be sure.

**Comment by signalwerk** [comment]
Hmmm... I'm not sure, but my UI is broke since version 4. I don't see the layout anymore. What am I missing?

NodeTypes.yaml
```
'Neos.NodeTypes:Page':
  childNodes:
    'main':
      type: 'Neos.Neos:ContentCollection'
      constraints:
        nodeTypes:
          'Neos.NodeTypes:TextWithImage': false
          'Neos.NodeTypes:TwoColumn': false
          'Neos.NodeTypes:ThreeColumn': false
          'Neos.NodeTypes:FourColumn': false
    'extra':
      type: 'Neos.Neos:ContentCollection'
      constraints:
        nodeTypes:
          '*': FALSE
          'signalwerk.sfgz:Space': TRUE
          'signalwerk.sfgz:Upload': TRUE
          'Neos.NodeTypes:ContentReferences': TRUE
          'Neos.NodeTypes:Headline': TRUE
          'Neos.NodeTypes:Text': TRUE
          'Neos.NodeTypes:Image': TRUE
          'Neos.NodeTypes:Menu': TRUE
  properties:
    'layout':
      ui:
        inspector:
          group: 'layout'
          editorOptions:
            values:
              'default':
                label: 'Normal'
              'wide':
                label: 'wide'
              'course':
                label: 'course'
    'style':
      type: string
      ui:
        label: 'Stil'
        inspector:
          group: 'layout'
          editor: 'Neos.Neos/Inspector/Editors/SelectBoxEditor'

          editorOptions:
            values:
              'default':
                label: 'Normal'
              'noBackground':
                label: 'kein Hintergrundbild'
              'hideL3':
                label: 'Verstecke L3-Navigation'
              'showSiblings':
                label: 'Nur selbes Level zeigen'

```

root.fusion
```
prototype(Neos.NodeTypes:Page) < prototype(Neos.Neos:Page) {
 ...
}

page = Neos.NodeTypes:Page
```

composer.json
```
    "require": {
        "neos/neos": "~4.1.0",
        "neos/nodetypes": "~4.1.0",
        ...
    },
```

image

**Comment by mficzel** [comment]
@signalwerk please contact us via slack or a new issue, this is a closed issue and you are struggeling with one of the breaking changes of 4.0. We will try to help but this is the wrong channel.

**Comment by signalwerk** [comment]
ok. sorry. didn't wanna bother anyone.

**Comment by signalwerk** [comment]
Just if someone finds this post through google:

my problem was that in my composer-file of the site I didn't require the correct `neos/nodetypes` but only in the globale composer-file. therefore the loading-order (`flow package:list --loading-order`) was not correct and nodetypes were loaded after my site-package.

thanks to @mficzel I was able to solve my problem!

**Pull request merged**
