### PR TITLE
FEATURE: Add settings to customize login screen stylesheets

### PR DESCRIPTION
**Pull request by dfeyer**
This change add a new setting to include custom stylesheets in the Neos
backend login form with documentation.

### CODE REVIEW

**Comment by dfeyer** [comment]
#284 retargeted to master

:+1: 

@bwaidelich I include your comments about the configuration synthax

**Comment by kdambekalns** [comment]
Thanks for re-targeting and adjusting to the comments. Looks good (did not test, though!).

**Comment by aertmann** [comment]
how would you unset the default stylesheet though? maybe `<f:if condition="{style}">` would help, then it can be set to an empty string or null to unset it..

**Comment by dfeyer** [comment]
@aertmann There is the array_filter, so setting to NULL or FALSE should disable the stylesheet, and less logic in the view is always good

**Comment by bwaidelich** [comment]
:+1: by reading
Great, thank you!

**Comment by aertmann** [comment]
@dfeyer: ah good, missed that.. what's the `array_values` good for though?

**Comment by aertmann** [comment]
a Jira ticket would be fitting for a feature, did you check if one exists already?

**Comment by dfeyer** [comment]
@aertmann The keys are useless in the view. I check now if an issue exist, if not, I create one

**Comment by aertmann** [comment]
okay, unnecessary if you ask me though..

anyway :+1: by reading

**Comment by dfeyer** [comment]
Last push remove array_values(), attach the commit to https://jira.neos.io/browse/NEOS-122 and add documentation on how to disable stylesheet

**Comment by dimaip** [comment]
Great!
:+1: by reading!

**Comment by bwaidelich** [comment]
\o/ thank you

**Comment by dimaip** [comment]
http://49.media.tumblr.com/d68c502d4c1b4739ec5ff3dee774da4b/tumblr_mzk8ggrOp41sj5h4oo1_500.gif

**Pull request merged**
