### PR TITLE
TASK: set sane defaults for `TYPO3.TypoScript:Collection`

### PR DESCRIPTION
**Pull request by dimaip**
May be breaking, but in super rare occurrences like:

```
test = T:Collection {
  collection = ${xyz}
  iteratorName = 'iterator'
  itemRenderer = T:Collection {
    collection = ${q(item).children().get()}
    itemRenderer = ${iterator.cycle}
  }
}
```

Still would like to have it in 2.3.

### CODE REVIEW

**Comment by hlubek** [comment]
@dimaip Well, 2.3 is LTS and released just now. What about merging that in master?

**Comment by kitsunet** [comment]
Would like to hear more opinions, I am currently torn. I don't think it's that important to risk regressions in 2.3, but then again it's really pretty unlikely to break.

**Comment by hlubek** [comment]
> but then again it's really pretty unlikely to break

You know, it _will_ happen if it _can_ happen ;) I don't think we lose much if we put it into master.

**Comment by dimaip** [comment]
@hlubek a agree! Changed base.

**Pull request merged**
