### PR TITLE
BUGFIX: #2664 set position to PHP_INT_MAX if nodeDimensionValue is no…

### PR DESCRIPTION
**Pull request by gjwnc**
Fix returning invalid nodes in reduceNodeVariantsByWorkspacesAndDimensions. See #2664 for further details.

### CODE REVIEW

**Comment by gjwnc** [comment]
I'll try to reinvestigate the source of this issue on our setup.

@kitsunet Since this method depends on the order of the nodes (prior this bugfix), wouldn't it be possible, that the database just returned the set of nodes for this method in some random order which could trigger this bug?

**Comment by davidspiola** [comment]
Hi Folks, is this ready for merging?

**Comment by gjwnc** [comment]
@davidspiola From my side, there is nothing left to do regarding code changes. I had no time yet to investigate the source of the issue in our setup, but I can say for sure that without these changes, a few error occurs in our setup because nodes and dimensions are not matched correctly. I'm not yet sure why this is triggered in the first place.

**Comment by davidspiola** [comment]
@thx @gjwnc! @kitsunet can you recomment a other reviewer just to make sure it works?

**Comment by kitsunet** [comment]
Not really, no, I guess @skurfuerst knows this part, or @kdambekalns could have a look.

**Comment by davidspiola** [comment]
@skurfuerst told me, that he will have time for a review later today. Let's wait for that before me merge it.

**Pull request merged**
