### PR TITLE
How to Contribute to the Neos Documentation

### PR DESCRIPTION
**Pull request by webappcreations**
This is a step by step Sphinx-Guide of how to Contribute to the Neos Documentation. Please check if that is a good workflow, if there is some steps missing or if you would change something.

### CODE REVIEW

**Comment by webappcreations** [comment]
btw.  I have found this two guidelines:
- [Commit Message Style](https://discuss.neos.io/t/commit-message-style/507) 
- [Creating a pull request](https://discuss.neos.io/t/creating-a-pull-request/506) 

I could/will integrate them into the Documentation as well and make the document more generic, describing the general workflow of Contributing... 

I also feel like since I am trying to be thorough I might add 1-2 lines about how to/or at least were to get the informations about setting up ssl for git too...

**Comment by kitsunet** [comment]
Good work! Much appreciated :)

**Comment by kdambekalns** [comment]
Nice one already. But you should also point out how one can do most of this via the Github website  (simple one-off file edit, creating a branch first, create PR).

**Comment by skurfuerst** [comment]
Hey @webappcreations,
Thanks a lot for your effort :-) Would you be willing to add a "short style" as well, like Karsten has suggested?

All the best,
Sebastian

**Comment by webappcreations** [comment]
Hey @skurfuerst ,
I know I keep thinking of finally finishing this, considering it's already more than two month already... wow
I will try to add the last changes some time next week.

Robin

**Comment by webappcreations** [comment]
Well I just thought what is better than the present :-)
I hope everything is fine now...

**Pull request merged**
