### PR TITLE
!!! TASK: Adjust class names for `Neos.NodeTypes:Image`

### PR DESCRIPTION
**Pull request by johannessteu**

### CODE REVIEW

**Comment by gerhard-boden** [comment]
could you point to the related SCSS update in the description? Thanks!

**Comment by ComiR** [comment]
Actually since https://github.com/neos/neos-development-collection/commit/102a0cb0a923faf75d226cf0fa0daab52b04ccdc#diff-f7e9d6429f4b7ce80495f9e168374761R26 (from 2013!) the SCSS already was out of sync. `typo3-image-alignment` became `typo3-neos-alignment`.

You can find the corresponding current SCSS [here](https://github.com/neos/neos-development-collection/blob/3.0/Neos.Neos/Resources/Private/Styles/RawContentMode.scss#L42).

**Comment by gerhard-boden** [comment]
Ah thanks, i thought we had a differnt PR for the SCSS change :D Looks like we need one, since this has not been working for a long time

**Comment by gerhard-boden** [comment]
@johannessteu could you change the SCSS selector within this PR so it's bundled with the markup change? Dunno if it makes sense to create a separate PR for online line of SCSS

**Comment by kdambekalns** [comment]
@gerhard-boden which SCSS should be changed?

**Comment by gerhard-boden** [comment]
@kdambekalns If it's not also used somewhere else it should be safe to adjust this: https://github.com/neos/neos-development-collection/blob/3.0/Neos.Neos/Resources/Private/Styles/RawContentMode.scss#L42

**Comment by gerhard-boden** [comment]
I mean if people used this class  in their custom styles this could also be considered breaking and would require a migration

**Comment by johannessteu** [comment]
@gerhard-boden updated the scss, @aertmann already flagged it as breaking. Don't think a we can really provide a code migration for this and i don't think we should  migrate users css at all

**Comment by daniellienert** [comment]
Close the PR after talking to @johannessteu

**Pull request closed without merging**
