### PR TITLE
FEATURE: Enhance dimension preset resolution

### PR DESCRIPTION
**Pull request by nezaniel**
This replaces the static, URI path segment based content dimension preset resolution with a framework to do so. There are two new resolution modes (subdomain and top level domain) as well as additional configuration options for URI path segment based resolution (order and delimiter).

Content dimension preset (and workspace) detection is now taken over from the FrontendNodeUriPartHandler by an HTTP component which is supposed to hand it over to routing.
Also, link postprocessing is extracted from the FrontendNodeUriPartHandler to a ContentSubgraphUriProcessorInterface.

The new features can be verified using the examples from the documentation.

Currently missing:
- Functional tests
- Usage of the Neos.Neos.contentDimensions.uriPathSegmentDelimiter configuration option
- Integration into https://github.com/neos/flow-development-collection/compare/master...bwaidelich:1120-extensible-routing

- [X] Code follows the PSR-2 coding style
- [~] Tests have been created, run and adjusted as needed
- [X] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)

### CODE REVIEW

**Comment by kitsunet** [comment]
The fusion changes (to tests eg.) seem unrelated though...

**Comment by bwaidelich** [comment]
42 commits?! o.O

Didn't look at the change yet, just a mini remark: please leave out the checklist when merging this so that the changelog won't get "polluted"

**Comment by mficzel** [comment]
I can confirm that the modes "subdomain" and "uriPathSegment" are working in Frontend and backend and in the old and the new ui. At least for me.

**Comment by mficzel** [comment]
I dislike the wording of the mode "subdomain" and "topLevelFomain" where internally this is used as hostNamePrefix and hostNameSuffix. 

Also i wonder why there is not a simple resolution mode "domain" or "hostname" that handles the entire hostname. The intended use-case for this where two different dimensions are mapped to the hostname is imho very specific and could be implemented as a resolution-mode in a third party package.

**Comment by nezaniel** [comment]
I prefer subdomain and TLD to prefix and suffix as they are more specific towards the intention.
Resolution mode domain could be added, but it's much less common than the other ones and has lots of implications (think of your development environment using different domains than the live environment).
Using both subdomain and TLD is something we should definitively support for language/market combinations which are probably **the** most common use case for multiple dimensions.
Resolution modes are not part of the public API because they are too heavily coupled to routing. Maybe we can decouple that, but probably not

**Comment by nezaniel** [comment]
This has been taken over by https://github.com/Flowpack/neos-dimensionresolver for now and might return for 4.1 or with the rewritten CR

**Pull request closed without merging**
